WITH PENDIENTES_FIRMA AS (
    SELECT 
        EXECUTION_,
        CREATE_,
        ACTIVITY_NAME_
    FROM GEDO_GED.JBPM4_TASK
    WHERE UPPER(ACTIVITY_NAME_) = 'FIRMAR DOCUMENTO'
    AND TRUNC(CREATE_) = TRUNC(SYSDATE)
    )
    
SELECT
    EXECUTION_,
    CREATE_,
    ACTIVITY_NAME_,
    SISTEMA_INICIADOR,
    USUARIO_FIRMANTE,
    SR.CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION
FROM (    
SELECT
    P.EXECUTION_,
    P.CREATE_,
    P.ACTIVITY_NAME_,
    (SELECT STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE WHERE EXECUTION_ = P.EXECUTION_
        AND KEY_ = 'sistemaIniciador') AS SISTEMA_INICIADOR,
    (SELECT STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE WHERE EXECUTION_ = P.EXECUTION_
        AND KEY_ = 'usuarioFirmante') AS USUARIO_FIRMANTE
FROM PENDIENTES_FIRMA P
)
INNER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON SU.NOMBRE_USUARIO = USUARIO_FIRMANTE
INNER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO
INNER JOIN TRACK_GED.SADE_REPARTICION SR ON SSI.CODIGO_REPARTICION = SR.ID_REPARTICION

WHERE SISTEMA_INICIADOR IN (
    'ws_gdeba_prod_dimggp_certdi', 
    'ws_gdeba_prod_dimggp_pol'
    )
ORDER BY CREATE_ ASC;