WITH TAREAS_SIN_REFERENCIA AS (
SELECT
R.ID_REGISTRO,
REP.CODIGO_REPARTICION,
COALESCE(C.NOMBRE,REP.NOMBRE_REPARTICION) AS DELEGACION,
T.NAME_ AS NOMBRE_TAREA,
TO_CHAR(R.FECHA_ULTIMA_MODIFICACION,'DD/MM/YYYY HH24:MI:SS') AS FECHA_ULTIMA_MODIFICACION,
TR.DESCRIPCION AS TIPO_REGISTRO,
SR.DESCRIPCION AS SUBTIPO_REGISTRO
FROM
RCE_GED.JBPM4_PARTICIPATION P
INNER JOIN RCE_GED.JBPM4_TASK T ON P.TASK_ = T.DBID_
INNER JOIN RCE_GED.RCE_REGISTRO R ON T.EXECUTION_ID_ = R.ID_FLUJO_JBPM
INNER JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SR ON R.FK_SUBTIPO_REGISTRO = SR.ID_SUBTIPO_REGISTRO 
INNER JOIN RCE_GED.SYS_TIPO_REGISTRO TR ON SR.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO
INNER JOIN TRACK_GED.SADE_REPARTICION REP ON REP.CODIGO_REPARTICION = REGEXP_SUBSTR(P.GROUPID_, '[^.]+', 1, 1)
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON R.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
WHERE REP.CODIGO_REPARTICION LIKE 'DL%MGGP'
)
SELECT
TSR.CODIGO_REPARTICION,
TSR.DELEGACION,
TSR.NOMBRE_TAREA,
TSR.FECHA_ULTIMA_MODIFICACION,
TSR.TIPO_REGISTRO,
TSR.SUBTIPO_REGISTRO,
LISTAGG(
    CASE WHEN PER.NUMERO_DOCUMENTO IS NULL THEN 'No disponible'
    ELSE 'DNI: '||PER.NUMERO_DOCUMENTO END, ' / ') 
    WITHIN GROUP (ORDER BY RP.ID_REGISTRO_PERSONA ASC
    ) REFERENCIA 
FROM
TAREAS_SIN_REFERENCIA TSR
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RP ON RP.FK_REGISTRO = TSR.ID_REGISTRO 
    AND RP.ROL IN ('Hijo','Difunto','Contrayente 1','Contrayente 2','Solicitante')
LEFT JOIN RCE_GED.RCE_PERSONA PER ON PER.ID_PERSONA = RP.FK_PERSONA
GROUP BY
TSR.CODIGO_REPARTICION,
TSR.DELEGACION,
TSR.NOMBRE_TAREA,
TSR.FECHA_ULTIMA_MODIFICACION,
TSR.TIPO_REGISTRO,
TSR.SUBTIPO_REGISTRO