SELECT
P.ID_PERSONA,
P.PRIMER_NOMBRE || ' ' || P.SEGUNDO_NOMBRE || ' ' || P.TERCER_NOMBRE AS NOMBRES,
P.PRIMER_APELLIDO || ' ' || P.SEGUNDO_APELLIDO || ' ' || P.TERCER_APELLIDO AS APELLIDOS,
P.FECHA_NACIMIENTO,
SC.DESCRIPCION AS SITUACION_CONYUGAL,
TD.DESCRIPCION AS TIPO_DOCUMENTO,
P.NUMERO_DOCUMENTO,
N.DESCRIPCION_NACIONALIDAD AS NACIONALIDAD,
S.DESCRIPCION AS SEXO,
D.LOCALIDAD AS DOMICILIO_LOCALIDAD,
P.CUIL,
P.PROFESION,
P.ESTADO_CIVIL,
P.VALIDADO_RENAPER,
RP.ROL,
R.ID_REGISTRO,
R.FECHA_INUTILIZACION,
RVA.ID_REGISTRO_ANTECESOR,
RVS.ID_REGISTRO_SUCESOR,
R.NUMERO AS NUMERO_REGISTRO,
COALESCE(SCIR.ID_CIRCUNSCRIPCION,SCDT.ID_CIRCUNSCRIPCION) AS ID_CIRCUNSCRIPCION,
COALESCE(SCIR.NOMBRE,SCDT.NOMBRE) AS NOMBRE_CIRCUNSCRIPCION,
COALESCE(SCIR.CODIGO_DELEGACION_RENAPER,SCDT.CODIGO_DELEGACION_RENAPER) AS CODIGO_DELEGACION_RENAPER,
COALESCE(TR.ID_TIPO_REGISTRO,TRDT.ID_TIPO_REGISTRO) AS ID_TIPO_REGISTRO,
COALESCE(TR.DESCRIPCION,TRDT.DESCRIPCION) AS TIPO_REGISTRO,
SR.ID_SUBTIPO_REGISTRO,
SR.DESCRIPCION AS SUBTIPO_REGISTRO,
R.ID_FLUJO_JBPM,
NVL(JBPMT.ACTIVITY_NAME_,'Cerrado') AS ESTADO_REGISTRO,
TO_CHAR(R.FECHA_ULTIMA_MODIFICACION,'DD/MM/YYYY HH24:MM') AS ULTIMA_MODIF,
JBPMT.ASSIGNEE_ AS USUARIO_ASIGNADO,
SUBSTR(JBPMP.GROUPID_, 0, INSTR(JBPMP.GROUPID_, '.')-1) AS REPARTICION_ASIGNADA,
SUBSTR(JBPMP.GROUPID_, - INSTR(REVERSE(JBPMP.GROUPID_), '.') + 1) AS SECTOR_ASIGNADO,
AR.ID_ACTA_REGISTRO,
COALESCE(AR.ANIO,DT.ANIO) AS ACTA_ANIO,
COALESCE(AR.TOMO||AR.LETRA_TOMO, DT.TOMO) AS ACTA_TOMO,
NVL(AR.FOLIO,0) AS ACTA_FOLIO,
COALESCE(AR.NUMERO_ACTA,DT.ACTA) AS ACTA_NUMERO,
AR.FECHA_CREACION,
DV.ID_DOCUMENTO_VINCULADO,
DV.NUMERO AS GEDO_VINCULADO,
TDOC.TIPO_DOCUMENTO_OFICIAL,
TDOC.DESCRIPCION AS DESCRIPCION_TIPO_DOC,
JBPM4V.STRING_VALUE_ AS ID_FLUJO_FIRMA,
GD.NUMERO AS NUMERO_EN_GEDO_DOCUMENTO,
GD.MOTIVO,
TO_CHAR(GD.FECHACREACION, 'DD/MM/YYYY HH24:MM') AS FECHA_CREACION_GEDO

FROM            RCE_GED.RCE_PERSONA P
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO TD       ON P.FK_TIPO_DOCUMENTO = TD.ID_TIPO_DOCUMENTO
LEFT OUTER JOIN RCE_GED.SYS_SITUACION_CONYUGAL SC   ON P.FK_SITUACION_CONYUGAL = SC.ID_SITUACION_CONYUGAL
LEFT OUTER JOIN RCE_GED.SYS_NACIONALIDAD N          ON P.FK_NACIONALIDAD = N.ID_NACIONALIDAD
LEFT OUTER JOIN RCE_GED.SYS_SEXO S                  ON P.FK_SEXO = S.ID_SEXO
LEFT OUTER JOIN RCE_GED.RCE_DOMICILIO D             ON P.FK_DOMICILIO = D.ID_DOMICILIO
LEFT OUTER JOIN RCE_GED.RCE_REGISTRO_PERSONA RP     ON P.ID_PERSONA = RP.FK_PERSONA
LEFT OUTER JOIN RCE_GED.RCE_REGISTRO R              ON RP.FK_REGISTRO = R.ID_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_DIGITAL RD              ON R.ID_REGISTRO = RD.ID_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT     ON RD.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO
LEFT OUTER JOIN RCE_GED.RCE_VINCULACION RVA         ON R.ID_REGISTRO = RVA.ID_REGISTRO_SUCESOR
LEFT OUTER JOIN RCE_GED.RCE_VINCULACION RVS         ON R.ID_REGISTRO = RVS.ID_REGISTRO_ANTECESOR
LEFT OUTER JOIN RCE_GED.JBPM4_TASK JBPMT            ON R.ID_FLUJO_JBPM = JBPMT.EXECUTION_ID_
LEFT OUTER JOIN RCE_GED.JBPM4_PARTICIPATION JBPMP   ON JBPMT.DBID_ = JBPMP.TASK_
LEFT OUTER JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCIR    ON R.FK_ID_CIRCUNSCRIPCION = SCIR.ID_CIRCUNSCRIPCION
LEFT OUTER JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCDT    ON DT.FK_CIRCUNSCRIPCION = SCDT.ID_CIRCUNSCRIPCION
LEFT OUTER JOIN RCE_GED.SYS_TIPO_REGISTRO TR        ON SCIR.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO
LEFT OUTER JOIN RCE_GED.SYS_TIPO_REGISTRO TRDT      ON SCDT.FK_TIPO_REGISTRO = TRDT.ID_TIPO_REGISTRO
LEFT OUTER JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SR     ON R.FK_SUBTIPO_REGISTRO = SR.ID_SUBTIPO_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_ACTA_REGISTRO AR        ON R.ID_REGISTRO = AR.FK_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DV  ON AR.FK_DOCUMENTO_VINCULADO = DV.ID_DOCUMENTO_VINCULADO
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTACION TDOC ON DV.FK_TIPO_DOCUMENTACION = TDOC.ID_TIPO_DOCUMENTACION
LEFT OUTER JOIN RCE_GED.JBPM4_VARIABLE JBPM4V       ON JBPMT.EXECUTION_ = JBPM4V.EXECUTION_ AND JBPM4V.KEY_ = 'idFlujoFirma'
LEFT OUTER JOIN GEDO_GED.GEDO_DOCUMENTO GD          ON JBPM4V.STRING_VALUE_ = GD.WORKFLOWORIGEN
WHERE 
SCIR.CODIGO_DELEGACION_RENAPER = 276
;