-- VISTA --
SELECT 
    G.NUMERO AS "NUMERO GEDO",
    G.REPARTICION,
    G.MOTIVO,
    TO_CHAR(G.FECHACREACION, 'YYYY/MM/DD') AS "FECHA DE CREACION",
    T.ACRONIMO AS "TIPO GEDO",
    G.SISTEMAORIGEN AS "SISTEMA ORIGEN",
    G.SISTEMAINICIADOR AS "SISTEMA INICIADOR",
    ROUND((G.PESO / 1024),2) AS "PESO (KB)"
    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
WHERE G.REPARTICION != 'TESTGDEBA';

---------------------------------------

SELECT DISTINCT G.SISTEMAINICIADOR AS "SISTEMA INICIADOR"
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
WHERE G.REPARTICION != 'TESTGDEBA';
--EE
--GEDO
--ws_gdeba_prod_gob_aopee
--RCE

---------------------------------------

SELECT DISTINCT G.SISTEMAORIGEN AS "SISTEMA ORIGEN"
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
WHERE G.REPARTICION != 'TESTGDEBA';
--GEDO
--ws_gdeba_prod_gob_aopee
--RCE

---------------------------------------

SELECT DISTINCT G.SISTEMAINICIADOR || ' - ' ||  G.SISTEMAORIGEN AS "INICIADOR - ORIGEN"
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
WHERE G.REPARTICION != 'TESTGDEBA';
--EE-GEDO
--RCE-GEDO
--RCE-RCE
--ws_gdeba_prod_gob_aopee-ws_gdeba_prod_gob_aopee
--GEDO-GEDO

---------------------------------------

-- PESO PROMEDIO EN KB (KBYTES)--
SELECT
    ROUND((AVG(G.PESO) / 1024),2) AS "PROMEDIO (KB)"    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
WHERE G.REPARTICION != 'TESTGDEBA'; 

---------------------------------------

-- CANTIDAD TOTAL DE GEDOS DOC VINCULADO --
SELECT
    COUNT(G.NUMERO) AS "TOTAL GEDOS"    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
WHERE G.REPARTICION != 'TESTGDEBA';  

---------------------------------------

-- CANTIDAD TOTAL DE GEDOS GEDO DOCUMENTO --
SELECT
    COUNT(G.NUMERO) AS "TOTAL GEDOS"    
FROM GEDO_GED.GEDO_DOCUMENTO G
WHERE G.REPARTICION != 'TESTGDEBA' AND G.SISTEMAINICIADOR = 'RCE'; 

---------------------------------------

-- PESO TOTAL EN TB (TERABYTES) RCE_GED.RCE_DOCUMENTO_VINCULADO --
SELECT
    ROUND(SUM(G.PESO) / 1024 / 1024 / 1024 / 1024, 2) AS "TOTAL (TB)"
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
WHERE G.REPARTICION != 'TESTGDEBA';

---------------------------------------

-- PESO TOTAL EN TB (TERABYTES) RCE_GED.RCE_DOCUMENTO_VINCULADO --
SELECT
    ROUND(SUM(G.PESO) / 1024 / 1024 / 1024 / 1024, 2) AS "TOTAL (TB)"
FROM GEDO_GED.GEDO_DOCUMENTO G
WHERE G.REPARTICION != 'TESTGDEBA' AND G.SISTEMAINICIADOR = 'RCE';      