SELECT NOTIFICADO, TOTAL-NOTIFICADO SIN_NOTIFICAR, TOTAL, ROUND((NOTIFICADO/TOTAL)*100,2)||'%' PORCENTAJE
FROM (
    SELECT
    NVL(SUM(CASE WHEN (ID_TRAMITE_RENAPER > 0) OR (INFORME_FALLECIMIENTO_CODIGO = 99) THEN 1 END), 0) NOTIFICADO,
    COUNT(*) AS TOTAL
    FROM RCE_GED.RCE_IFAZ_DEFUNCION_RENAPER WHERE TRUNC(FECHA_INICIO_IFAZ)
    BETWEEN '01/05/2021' AND '30/06/2021'
);