SELECT
R.ID_REGISTRO,
R.FECHA_INUTILIZACION,
RVA.ID_REGISTRO_ANTECESOR,
RVS.ID_REGISTRO_SUCESOR,
R.NUMERO AS NUMERO_REGISTRO,
C.NOMBRE AS DELEGACION_INSCRIPCION,
L.ID AS ID_LOCALIDAD_INSCRIPCION,
L.NOMBRE AS LOCALIDAD_INSCRIPCION,
DL.ID AS ID_PARTIDO_INSCRIPCION,
DL.NOMBRE AS PARTIDO_INSCRIPCION,
TR.ID_TIPO_REGISTRO AS ID_TIPO_REGISTRO,
TR.DESCRIPCION AS TIPO_REGISTRO,
SR.ID_SUBTIPO_REGISTRO,
SR.DESCRIPCION AS SUBTIPO_REGISTRO,
R.ID_FLUJO_JBPM,
NVL(JBPMT.ACTIVITY_NAME_,'Cerrado') AS ESTADO_REGISTRO,
TO_CHAR(R.FECHA_ULTIMA_MODIFICACION,'DD/MM/YYYY HH24:MM') AS ULTIMA_MODIF,
JBPMT.ASSIGNEE_ AS USUARIO_ASIGNADO,
SUBSTR(JBPMP.GROUPID_, 0, INSTR(JBPMP.GROUPID_, '.')-1) AS REPARTICION_ASIGNADA,
SUBSTR(JBPMP.GROUPID_, - INSTR(REVERSE(JBPMP.GROUPID_), '.') + 1) AS SECTOR_ASIGNADO,
AR.ID_ACTA_REGISTRO,
AR.ANIO AS ACTA_ANIO,
AR.TOMO||AR.LETRA_TOMO AS ACTA_TOMO,
AR.FOLIO AS ACTA_FOLIO,
AR.NUMERO_ACTA AS ACTA_NUMERO,
AR.FECHA_CREACION,
DV.ID_DOCUMENTO_VINCULADO AS ID_DOCUMENTO_VINCULADO,
DV.NUMERO AS GEDO_VINCULADO,
TDOC.TIPO_DOCUMENTO_OFICIAL AS TIPO_DOCUMENTO_OFICIAL,
TDOC.DESCRIPCION AS DESCRIPCION_TIPO_DOC,
JBPM4V.STRING_VALUE_ AS ID_FLUJO_FIRMA,
GD.NUMERO AS NUMERO_EN_GEDO_DOCUMENTO,
GD.MOTIVO,
TO_CHAR(GD.FECHACREACION, 'DD/MM/YYYY HH24:MM') AS FECHA_CREACION_GEDO

FROM            
RCE_GED.RCE_REGISTRO R
LEFT JOIN RCE_GED.RCE_DIGITAL RD              ON R.ID_REGISTRO = RD.ID_REGISTRO
LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT     ON RD.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO
LEFT JOIN RCE_GED.RCE_VINCULACION RVA         ON R.ID_REGISTRO = RVA.ID_REGISTRO_SUCESOR
LEFT JOIN RCE_GED.RCE_VINCULACION RVS         ON R.ID_REGISTRO = RVS.ID_REGISTRO_ANTECESOR
LEFT JOIN RCE_GED.JBPM4_TASK JBPMT            ON R.ID_FLUJO_JBPM = JBPMT.EXECUTION_ID_
LEFT JOIN RCE_GED.JBPM4_PARTICIPATION JBPMP   ON JBPMT.DBID_ = JBPMP.TASK_
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C       ON R.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.EU_LOCALIDAD L              ON C.FK_LOCALIDAD = L.ID
LEFT JOIN RCE_GED.EU_DEPARTAMENTO DL          ON L.ID_DEPARTAMENTO = DL.ID
LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TR        ON C.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO
LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SR     ON R.FK_SUBTIPO_REGISTRO = SR.ID_SUBTIPO_REGISTRO
LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO AR        ON R.ID_REGISTRO = AR.FK_REGISTRO
LEFT JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DV  ON AR.FK_DOCUMENTO_VINCULADO = DV.ID_DOCUMENTO_VINCULADO
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTACION TDOC ON DV.FK_TIPO_DOCUMENTACION = TDOC.ID_TIPO_DOCUMENTACION
LEFT JOIN RCE_GED.JBPM4_VARIABLE JBPM4V       ON JBPMT.EXECUTION_ = JBPM4V.EXECUTION_ AND JBPM4V.KEY_ = 'idFlujoFirma'
LEFT JOIN GEDO_GED.GEDO_DOCUMENTO GD          ON JBPM4V.STRING_VALUE_ = GD.WORKFLOWORIGEN

WHERE
EXTRACT(YEAR FROM AR.FECHA_CREACION) = '2021' AND
JBPMT.ACTIVITY_NAME_ = 'Esperar Firma Digital' AND
DV.ID_DOCUMENTO_VINCULADO IS NULL AND
GD.WORKFLOWORIGEN IS NOT NULL;