SELECT
COUNT(*) CANTIDAD,
COALESCE(TRA.DESCRIPCION,TRDTA.DESCRIPCION) AS TIPO_REGISTRO

FROM
    RCE_GED.RCE_VINCULACION RV
    
    --INFO REGISTRO ANTECESOR
    LEFT JOIN RCE_GED.RCE_REGISTRO RA              ON RA.ID_REGISTRO = RV.ID_REGISTRO_ANTECESOR
    LEFT JOIN RCE_GED.RCE_DIGITAL RDA              ON RA.ID_REGISTRO = RDA.ID_REGISTRO
    LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DTA     ON RDA.FK_DATO_TOPOGRAFICO = DTA.ID_DATO_TOPOGRAFICO    
    LEFT JOIN RCE_GED.JBPM4_TASK JBPMTA            ON RA.ID_FLUJO_JBPM = JBPMTA.EXECUTION_ID_
    LEFT JOIN RCE_GED.JBPM4_PARTICIPATION JBPMPA   ON JBPMTA.DBID_ = JBPMPA.TASK_
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCIRA    ON RA.FK_ID_CIRCUNSCRIPCION = SCIRA.ID_CIRCUNSCRIPCION
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCDTA    ON DTA.FK_CIRCUNSCRIPCION = SCDTA.ID_CIRCUNSCRIPCION
    LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TRA        ON SCIRA.FK_TIPO_REGISTRO = TRA.ID_TIPO_REGISTRO
    LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TRDTA      ON SCDTA.FK_TIPO_REGISTRO = TRDTA.ID_TIPO_REGISTRO
    LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SRA     ON RA.FK_SUBTIPO_REGISTRO = SRA.ID_SUBTIPO_REGISTRO
    LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO ARA        ON RA.ID_REGISTRO = ARA.FK_REGISTRO
    LEFT JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DVA  ON ARA.FK_DOCUMENTO_VINCULADO = DVA.ID_DOCUMENTO_VINCULADO
    LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTACION TDOCA ON DVA.FK_TIPO_DOCUMENTACION = TDOCA.ID_TIPO_DOCUMENTACION
    LEFT JOIN RCE_GED.JBPM4_VARIABLE JBPM4VA       ON JBPMTA.EXECUTION_ = JBPM4VA.EXECUTION_ AND JBPM4VA.KEY_ = 'idFlujoFirma'
    LEFT JOIN GEDO_GED.GEDO_DOCUMENTO GDA          ON JBPM4VA.STRING_VALUE_ = GDA.WORKFLOWORIGEN   
    
    --INFO REGISTRO SUCESOR
    LEFT JOIN RCE_GED.RCE_REGISTRO RS              ON RS.ID_REGISTRO = RV.ID_REGISTRO_SUCESOR
    LEFT JOIN RCE_GED.RCE_DIGITAL RDS              ON RS.ID_REGISTRO = RDS.ID_REGISTRO
    LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DTS     ON RDS.FK_DATO_TOPOGRAFICO = DTS.ID_DATO_TOPOGRAFICO    
    LEFT JOIN RCE_GED.JBPM4_TASK JBPMTS            ON RS.ID_FLUJO_JBPM = JBPMTS.EXECUTION_ID_
    LEFT JOIN RCE_GED.JBPM4_PARTICIPATION JBPMPS   ON JBPMTS.DBID_ = JBPMPS.TASK_
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCIRS    ON RS.FK_ID_CIRCUNSCRIPCION = SCIRS.ID_CIRCUNSCRIPCION
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCDTS    ON DTS.FK_CIRCUNSCRIPCION = SCDTS.ID_CIRCUNSCRIPCION
    LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TRS        ON SCIRS.FK_TIPO_REGISTRO = TRS.ID_TIPO_REGISTRO
    LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TRDTS      ON SCDTS.FK_TIPO_REGISTRO = TRDTS.ID_TIPO_REGISTRO
    LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SRS     ON RS.FK_SUBTIPO_REGISTRO = SRS.ID_SUBTIPO_REGISTRO
    LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO ARS        ON RS.ID_REGISTRO = ARS.FK_REGISTRO
    LEFT JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DVS  ON ARS.FK_DOCUMENTO_VINCULADO = DVS.ID_DOCUMENTO_VINCULADO
    LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTACION TDOCS ON DVS.FK_TIPO_DOCUMENTACION = TDOCS.ID_TIPO_DOCUMENTACION
    LEFT JOIN RCE_GED.JBPM4_VARIABLE JBPM4VS       ON JBPMTS.EXECUTION_ = JBPM4VS.EXECUTION_ AND JBPM4VS.KEY_ = 'idFlujoFirma'
    LEFT JOIN GEDO_GED.GEDO_DOCUMENTO GDS          ON JBPM4VS.STRING_VALUE_ = GDS.WORKFLOWORIGEN

WHERE
    JBPMTS.ACTIVITY_NAME_ = 'Esperar Firma Digital'
    AND GDS.NUMERO is not null
    AND TO_DATE(GDS.FECHACREACION,'DD/MM/YYYY') < TO_DATE(SYSDATE-5,'DD/MM/YYYY')
    AND EXTRACT(YEAR FROM GDS.FECHACREACION) IN (2020,2021)
    AND RA.FECHA_INUTILIZACION IS NULL
    AND RS.FECHA_INUTILIZACION IS NULL

GROUP BY COALESCE(TRA.DESCRIPCION,TRDTA.DESCRIPCION)

ORDER BY COUNT(*) DESC;