SELECT
R.ID_REGISTRO,
R.FECHA_INUTILIZACION,
RVA.ID_REGISTRO_ANTECESOR,
RVS.ID_REGISTRO_SUCESOR,
R.NUMERO AS NUMERO_REGISTRO,
COALESCE(SCIR.ID_CIRCUNSCRIPCION,SCDT.ID_CIRCUNSCRIPCION) AS ID_CIRCUNSCRIPCION,
COALESCE(SCIR.NOMBRE,SCDT.NOMBRE) AS NOMBRE_CIRCUNSCRIPCION,
COALESCE(SCIR.CODIGO_DELEGACION_RENAPER,SCDT.CODIGO_DELEGACION_RENAPER) AS CODIGO_DELEGACION_RENAPER,
COALESCE(TR.ID_TIPO_REGISTRO,TRDT.ID_TIPO_REGISTRO) AS ID_TIPO_REGISTRO,
COALESCE(TR.DESCRIPCION,TRDT.DESCRIPCION) AS TIPO_REGISTRO,
SR.ID_SUBTIPO_REGISTRO,
SR.DESCRIPCION AS SUBTIPO_REGISTRO,
R.ID_FLUJO_JBPM,
NVL(JBPMT.ACTIVITY_NAME_,'Cerrado') AS ESTADO_REGISTRO,
TO_CHAR(R.FECHA_ULTIMA_MODIFICACION,'DD/MM/YYYY HH24:MM') AS ULTIMA_MODIF,
JBPMT.ASSIGNEE_ AS USUARIO_ASIGNADO,
SUBSTR(JBPMP.GROUPID_, 0, INSTR(JBPMP.GROUPID_, '.')-1) AS REPARTICION_ASIGNADA,
SUBSTR(JBPMP.GROUPID_, - INSTR(REVERSE(JBPMP.GROUPID_), '.') + 1) AS SECTOR_ASIGNADO,
AR.ID_ACTA_REGISTRO,
COALESCE(AR.ANIO,DT.ANIO) AS ACTA_ANIO,
COALESCE(AR.TOMO||AR.LETRA_TOMO, DT.TOMO) AS ACTA_TOMO,
NVL(AR.FOLIO,0) AS ACTA_FOLIO,
COALESCE(AR.NUMERO_ACTA,DT.ACTA) AS ACTA_NUMERO,
AR.FECHA_CREACION,
DV.ID_DOCUMENTO_VINCULADO,
DV.NUMERO AS GEDO_VINCULADO,
TDOC.TIPO_DOCUMENTO_OFICIAL,
TDOC.DESCRIPCION AS DESCRIPCION_TIPO_DOC,
JBPM4V.STRING_VALUE_ AS ID_FLUJO_FIRMA,
GD.NUMERO AS NUMERO_EN_GEDO_DOCUMENTO,
GD.MOTIVO,
TO_CHAR(GD.FECHACREACION, 'DD/MM/YYYY HH24:MM') AS FECHA_CREACION_GEDO

FROM            
RCE_GED.RCE_REGISTRO R
LEFT JOIN RCE_GED.RCE_DIGITAL RD              ON R.ID_REGISTRO = RD.ID_REGISTRO
LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT     ON RD.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO
LEFT JOIN RCE_GED.RCE_VINCULACION RVA         ON R.ID_REGISTRO = RVA.ID_REGISTRO_SUCESOR
LEFT JOIN RCE_GED.RCE_VINCULACION RVS         ON R.ID_REGISTRO = RVS.ID_REGISTRO_ANTECESOR
LEFT JOIN RCE_GED.JBPM4_TASK JBPMT            ON R.ID_FLUJO_JBPM = JBPMT.EXECUTION_ID_
LEFT JOIN RCE_GED.JBPM4_PARTICIPATION JBPMP   ON JBPMT.DBID_ = JBPMP.TASK_
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCIR    ON R.FK_ID_CIRCUNSCRIPCION = SCIR.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCDT    ON DT.FK_CIRCUNSCRIPCION = SCDT.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TR        ON SCIR.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO
LEFT JOIN RCE_GED.SYS_TIPO_REGISTRO TRDT      ON SCDT.FK_TIPO_REGISTRO = TRDT.ID_TIPO_REGISTRO
LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SR     ON R.FK_SUBTIPO_REGISTRO = SR.ID_SUBTIPO_REGISTRO
LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO AR        ON R.ID_REGISTRO = AR.FK_REGISTRO
LEFT JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DV  ON AR.FK_DOCUMENTO_VINCULADO = DV.ID_DOCUMENTO_VINCULADO
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTACION TDOC ON DV.FK_TIPO_DOCUMENTACION = TDOC.ID_TIPO_DOCUMENTACION
LEFT JOIN RCE_GED.JBPM4_VARIABLE JBPM4V       ON JBPMT.EXECUTION_ = JBPM4V.EXECUTION_ AND JBPM4V.KEY_ = 'idFlujoFirma'
LEFT JOIN GEDO_GED.GEDO_DOCUMENTO GD          ON JBPM4V.STRING_VALUE_ = GD.WORKFLOWORIGEN

WHERE
R.ID_REGISTRO IN (19926327,19926010,19926622,19930493);

;