SELECT * FROM RCE_GED.RCE_IFAZ_DEFUNCION_RENAPER IFAZ
LEFT JOIN RCE_GED.RCE_PERSONA PERS ON PERS.ID_PERSONA = IFAZ.FK_PERSONA

WHERE (id_tramite_renaper = 0 OR id_tramite_renaper IS NULL)
      AND fecha_inicio_ifaz BETWEEN TO_DATE('01-ago-19') AND TO_DATE('01-oct-19')