SELECT 
    G.NUMERO NUMERO_GEDO,
    G.REPARTICION CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION NOMBRE_REPARTICION,
    SR1.CODIGO_REPARTICION CODIGO_MINISTERIO,
    SR1.NOMBRE_REPARTICION NOMBRE_MINISTERIO,
    G.ANIO AÑO,
    G.MOTIVO,
    G.USUARIOGENERADOR USUARIO_GENERADOR,
    G.DATOS_USUARIO DATOS_USUARIO,
    G.FECHACREACION FECHA_CREACION,
    T.ACRONIMO TIPO_GEDO,
    T.NOMBRE NOMBRE_GEDO,
    G.SISTEMAORIGEN,
    G.SISTEMAINICIADOR,
    ROUND(G.PESO/1024/1024,2) PESO_MB
    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO_FAMILIA F ON T.FAMILIA = F.ID 
INNER JOIN TRACK_GED.SADE_REPARTICION SR ON G.REPARTICION = SR.CODIGO_REPARTICION  
INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

WHERE
    T.ACRONIMO IN ('RESOL', 'RESOC', 'DISPO', 'DISPC') AND
    EXTRACT(YEAR FROM G.FECHACREACION) = EXTRACT(YEAR FROM SYSDATE)
ORDER BY G.FECHACREACION DESC;