WITH ID_DOCUMENTOS AS (
    SELECT TD.ID FROM GEDO_GED.GEDO_TIPODOCUMENTO TD
    WHERE TD.ACRONIMO IN ('PANA','PANAT','PAMA','PAMAT','PAUC','PAUCT','PADE','PADET')
),

GEDOS AS ( 
    SELECT GD.*
    FROM GEDO_GED.GEDO_DOCUMENTO GD
    INNER JOIN ID_DOCUMENTOS TD ON TD.ID = GD.TIPO
    WHERE GD.FECHACREACION > SYSDATE-7
)    

SELECT GD.*
FROM GEDOS GD
WHERE NOT EXISTS (SELECT '?'
FROM GEDO_GED.GEDO_DOCUMENTO_ADJUNTO ADJ
WHERE GD.WORKFLOWORIGEN = ADJ.IDTASK);