SELECT 
GD.ANIO AÑO,
EXTRACT(MONTH FROM GD.FECHACREACION) MES_NUM,
TO_CHAR(GD.FECHACREACION, 'MONTH') MES_NOMBRE,

SUM(CASE WHEN
    SR.CODIGO_REPARTICION NOT LIKE 'DL%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDDR%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDSR%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDZ%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE '%RDLP'
    THEN 1 ELSE 0 END) AS "TOTAL GEDOS (SIN REDIP)",

SUM(CASE WHEN
    SR.CODIGO_REPARTICION LIKE 'DL%MGGP'
    OR SR.CODIGO_REPARTICION LIKE 'SDDR%MGGP'
    OR SR.CODIGO_REPARTICION LIKE 'SDSR%MGGP'
    OR SR.CODIGO_REPARTICION LIKE 'SDZ%MGGP'
    OR SR.CODIGO_REPARTICION LIKE '%RDLP'
    THEN 1 ELSE 0 END) AS "TOTAL GEDOS (SOLO REDIP)",
    
COUNT(*) AS TOTAL    

FROM 
GEDO_GED.GEDO_DOCUMENTO GD 
LEFT JOIN GEDO_GED.GEDO_TIPODOCUMENTO GT ON GD.TIPO = GT.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON GD.REPARTICION = SR.CODIGO_REPARTICION  
LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

WHERE
EXTRACT(YEAR FROM GD.FECHACREACION) IN (2019,2020,2021)
AND EXTRACT(MONTH FROM GD.FECHACREACION) IN (1,2,3,4)
AND SR.CODIGO_REPARTICION != 'TESTGDEBA'
GROUP BY GD.ANIO,EXTRACT(MONTH FROM GD.FECHACREACION),TO_CHAR(GD.FECHACREACION, 'MONTH')
ORDER BY GD.ANIO, EXTRACT(MONTH FROM GD.FECHACREACION) ASC;
