SELECT 
	gd.NUMERO ,
	gd.MOTIVO ,
	gd.FECHACREACION 

FROM 
	GEDO_GED.GEDO_DOCUMENTO gd 

INNER JOIN 
	GEDO_GED.GEDO_TIPODOCUMENTO gt ON gt.ID = gd.TIPO
	
WHERE 
	gd.FECHACREACION > TRUNC(SYSDATE) 
	AND gt.ACRONIMO IN ('PANA','PANAT','PAMA','PAMAT','PAUC','PAUCT','PADE','PADET')
	AND NOT EXISTS (
		SELECT 1
		FROM 
			GEDO_GED.GEDO_DOCUMENTO_ADJUNTO gda
		WHERE 
			gda.IDTASK = gd.WORKFLOWORIGEN
	)
;