SELECT 
	gt.ACRONIMO,
	gt.NOMBRE,
	gt.VERSION

FROM (
	SELECT 
		gt.*,
		ROW_NUMBER() OVER (PARTITION BY gt.ACRONIMO ORDER BY gt.FECHA_CREACION desc) AS rn
	FROM 
		GEDO_GED.GEDO_TIPODOCUMENTO gt
	) gt
WHERE 
	gt.rn = 1
	AND gt.ESTADO = 'ALTA'
		