SELECT * 
FROM (
	SELECT
		'EX-'||EE.ANIO||'-'||EE.NUMERO||'- -GDEBA-'||EE.CODIGO_REPARTICION_USUARIO AS NUMERO_EXPEDIENTE ,
	    EE.FECHA_CREACION ,
	    EEDOC.NUMERO_SADE ,
	    DFVALUE.INPUT_NAME ,
	    DFVALUE.VALUE_STR     
	FROM
	    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
	    INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EE.ID = EEDOCS.ID
	    INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
	    INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
	WHERE
		EE.FECHA_CREACION > TRUNC(SYSDATE) AND
	    EE.ID_TRATA = 408
)
PIVOT (
	MAX(VALUE_STR) FOR INPUT_NAME IN (
		'nombreactor' AS "Nombre del Actor" ,
		'nombredemandado' AS "Nombre del Demandado" ,
		'tematica' AS "Temática de la Causa" ,
		'tribunalojuzgado' AS "Tribunal o Juzgado Interv" ,
		'ndeexpedientejudicial' AS "N° de Expediente Judicial"
	)	
)