SELECT * FROM (
SELECT
TASK.DBID_,
TASK.NAME_ AS TAREA,
DECODE(TASK.STATE_,'open','pendiente') AS ESTADO,
TASK.ASSIGNEE_ AS USUARIO_ASIGNADO,
TO_CHAR(TASK.CREATE_,'DD/MM/YYYY') AS FECHA_CREACION,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'acronimoTipoDocumento' 
AND VAR.EXECUTION_ = TASK.EXECUTION_)  AS ACRONIMO,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'motivo'
AND VAR.EXECUTION_ = TASK.EXECUTION_) AS MOTIVO
FROM GEDO_GED.JBPM4_TASK TASK WHERE TASK.ASSIGNEE_ IN ('USERT','USERT.PF')
ORDER BY TASK.CREATE_ DESC
);