WITH DOCUMENTOS_ACTIVOS AS (
SELECT
    id,
    acronimo,
    nombre,
    version ULTIMA_VERSION,    
    DECODE(tipoproduccion,1,'LIBRE',2,'IMPORTADO',3,'TEMPLATE',4,'IMPORTADO-TEMPLATE') TIPO_PRODUCCION,
    DECODE(esespecial,0,'NO','SI') ES_ESPECIAL,
    DECODE(tienetoken,0,'NO','SI') TIENE_TOKEN

FROM ( 
    SELECT
        id,
        acronimo,
        nombre,
        version,
        tipoproduccion,
        MAX (version) OVER (PARTITION BY acronimo) AS ultima_version,
        esespecial,
        tienetoken
    FROM
        gedo_ged.gedo_tipodocumento
    WHERE
        estado = 'ALTA'
    )
WHERE
    version = ultima_version 
    
ORDER BY
    acronimo
)

SELECT
REPA.CODIGOREPARTICION CODIGO_REPARTICION,
SR.NOMBRE_REPARTICION,
DECODE(REPA.CODIGOREPARTICION,'--TODAS--','--TODAS--',SR1.CODIGO_REPARTICION) CODIGO_MINISTERIO,
SR1.NOMBRE_REPARTICION NOMBRE_MINISTERIO,
DC.ACRONIMO,
DC.NOMBRE,
DECODE(REPA.PERMISOINICIAR, 1, 'SI', 0 ,'NO') PERMISO_INICIAR,
DECODE(REPA.PERMISOFIRMAR, 1, 'SI', 0 ,'NO') PERMISO_FIRMAR,
DC.ULTIMA_VERSION,
DC.TIPO_PRODUCCION,
DC.ES_ESPECIAL,
DC.TIENE_TOKEN

FROM DOCUMENTOS_ACTIVOS DC
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO_REPARTICION REPA ON REPA.TIPODOCUMENTO = DC.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON REPA.CODIGOREPARTICION = SR.CODIGO_REPARTICION  
LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

ORDER BY REPA.CODIGOREPARTICION;