SELECT 
    G.NUMERO AS NUMERO_GEDO,
    G.REPARTICION AS CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION AS NOMBRE_REPARTICION,
    SR1.CODIGO_REPARTICION AS CODIGO_MINISTERIO,
    SR1.NOMBRE_REPARTICION AS NOMBRE_MINISTERIO,
    G.ANIO AS AÑO,
    G.MOTIVO,
    G.USUARIOGENERADOR AS USUARIO_GENERADOR,
    TO_CHAR(G.FECHACREACION, 'DD/MM/YYYY') AS FECHA_CREACION,
    T.ACRONIMO AS TIPO_GEDO,
    T.NOMBRE AS NOMBRE_GEDO,
    HIST.USUARIO AS USUARIO_ORIGEN,
    HIST.ACTIVIDAD,
    TO_CHAR(HIST.FECHA_INICIO, 'DD/MM/YYYY') AS FECHA_INICIO,
    TO_CHAR(HIST.FECHA_INICIO, 'HH24:MI:SS') AS HORA_INICIO,
    TO_CHAR(HIST.FECHA_FIN, 'DD/MM/YYYY') AS FECHA_FIN,
    TO_CHAR(HIST.FECHA_FIN, 'HH24:MI:SS') AS HORA_FIN,
    HIST.MENSAJE

FROM GEDO_GED.GEDO_DOCUMENTO G
LEFT JOIN GEDO_GED.GEDO_HISTORIAL HIST ON G.WORKFLOWORIGEN = HIST.WORKFLOWORIGEN
LEFT JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON G.REPARTICION = SR.CODIGO_REPARTICION  
LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

WHERE
HIST.USUARIO IN ('CMATURANA','DJALO','VMACLEN')
AND
TRUNC(HIST.FECHA_INICIO) BETWEEN TO_DATE('01/08/2017','DD/MM/YYYY') AND TO_DATE('08/12/2018','DD/MM/YYYY')
ORDER BY HIST.USUARIO, HIST.ID ASC;