SELECT 
    EEDOC.NUMERO_SADE, 
    EEDOC.NOMBRE_USUARIO_GENERADOR,
    TO_CHAR(EEDOC.FECHA_CREACION, 'YYYY/MM/DD') AS "FECHA_CREACION",
	TO_CHAR(EEDOC.FECHA_CREACION, 'HH24:MM') AS "HORA_CREACION",
    LISTAGG(DFVALUE.INPUT_NAME || ' : ' || DFVALUE.VALUE_STR, ' | ') WITHIN GROUP (ORDER BY DFVALUE.ID_FORM_COMPONENT) AS "VALORES_CARATULA",
    (EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || LPAD(EE.NUMERO, 8, '0') || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO ) AS EXPEDIENTE,
    EE.USUARIO_CREADOR

FROM
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EE.ID = EEDOCS.ID
    INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
    INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
WHERE
    EE.ID_TRATA = 408 AND 
    --EE.ANIO = 2020 AND 
    DFVALUE.INPUT_NAME NOT IN ('Sseparador','Scaratula')
GROUP BY 
    EEDOC.NUMERO_SADE, 
    EEDOC.NOMBRE_USUARIO_GENERADOR, 
    EEDOC.FECHA_CREACION, 
    (EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || LPAD(EE.NUMERO, 8, '0') || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO ), 
    EE.USUARIO_CREADOR;