SELECT 
    G.NUMERO AS NUMERO_GEDO,
    G.REPARTICION AS CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION AS NOMBRE_REPARTICION,
    SR1.CODIGO_REPARTICION AS CODIGO_MINISTERIO,
    SR1.NOMBRE_REPARTICION AS NOMBRE_MINISTERIO,
    G.ANIO AS AÑO,
    G.MOTIVO,
    G.USUARIOGENERADOR AS USUARIO_GENERADOR,
    G.DATOS_USUARIO AS DATOS_USUARIO,
    G.FECHACREACION AS FECHA_CREACION,
    T.ACRONIMO AS TIPO_GEDO,
    T.NOMBRE AS NOMBRE_GEDO,
    G.SISTEMAORIGEN,
    G.SISTEMAINICIADOR,
    ROUND(G.PESO/1024/1024,2) AS PESO_MB
    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO_FAMILIA F ON T.FAMILIA = F.ID 
INNER JOIN TRACK_GED.SADE_REPARTICION SR ON G.REPARTICION = SR.CODIGO_REPARTICION  
INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

WHERE
    T.ACRONIMO IN ('RESOL', 'RESOC', 'DISPO', 'DISPC') AND
    G.FECHACREACION > TRUNC(SYSDATE)
ORDER BY G.FECHACREACION DESC;