SELECT 
    G.NUMERO NUMERO_GEDO,
    G.NUMEROESPECIAL NUMERO_ESPECIAL,
    G.REPARTICION CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION NOMBRE_REPARTICION,
    SR1.CODIGO_REPARTICION CODIGO_MINISTERIO,
    SR1.NOMBRE_REPARTICION NOMBRE_MINISTERIO,
    TO_CHAR(G.FECHACREACION, 'DD/MM/YYYY') FECHA_CREACION,
    T.ACRONIMO TIPO_GEDO,
    T.NOMBRE NOMBRE_GEDO
    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO_FAMILIA F ON T.FAMILIA = F.ID 
INNER JOIN TRACK_GED.SADE_REPARTICION SR ON G.REPARTICION = SR.CODIGO_REPARTICION  
INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR.MINISTERIO = SR1.ID_REPARTICION

WHERE
    T.ACRONIMO IN ('DECRE','DECRI','DECTO','DI','DISFC','DISPC','DISPO','RESFC',
    'RESFO','RESO','RESOL','RESOC') AND
    G.FECHACREACION >= SYSDATE-20
ORDER BY G.FECHACREACION DESC;