SELECT 
RR.ID_REGISTRO AS ID_REGISTRO,
TO_CHAR (RR.FECHA_INUTILIZACION, 'YYYY-MM-DD') AS FECHA_INUTILIZACION,
RAR.CIRCUNSCRIPCION AS DELEGACION_INSCRIPCION,
L.NOMBRE AS LOCALIDAD_INSCRIPCION,
DL.NOMBRE AS PARTIDO_INSCRIPCION,
RAR.ANIO,
CONCAT (RAR.TOMO,RAR.LETRA_TOMO) AS TOMO,
RAR.FOLIO,
RAR.NUMERO_ACTA,
RR.REPARTICION_USUARIO,
TO_CHAR (RAR.FECHA_CREACION, 'YYYY-mm-dd') AS FECHA_CREACION,
SSR.ID_SUBTIPO_REGISTRO AS ID_SUBTIPO,
SSR.DESCRIPCION AS SUBTIPO,
NVL(F.ACTIVITY_NAME_, 'Cerrado') ESTADO,
PSG.CODIGO_PAGO AS COD_PAGO_SIEP,
PG.CODIGO_PAGO AS COD_PAGO,
CASE WHEN PG.CODIGO_PAGO IS NULL THEN 'SI' ELSE 'NO' END EXENTO,    
TC.DESCRIPCION AS DESCRIPCION_CONDICION,
RAR.ID_ACTA_REGISTRO AS ID_ACTA,
RP1.ID_PERSONA AS ID_SOLICITANTE,
STD2.DESCRIPCION AS TIPO_DOC_SOLICITANTE,
RP1.NUMERO_DOCUMENTO AS NRO_DOC_SOLICITANTE,
CONCAT ( RP1.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP1.SEGUNDO_NOMBRE), CONCAT (' ', RP1.TERCER_NOMBRE))) AS NOMBRES_SOLICITANTE,
CONCAT ( RP1.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP1.SEGUNDO_APELLIDO), CONCAT (' ', RP1.TERCER_APELLIDO))) AS APELLIDOS_SOLICITANTE,
NACPM1.DESCRIPCION_NACIONALIDAD AS NACIONALIDAD_SOLICITANTE,
SEXPM1.DESCRIPCION AS SEXO_SOLICITANTE,
RP1.EMAIL AS MAIL_SOLICITANTE,
RP1.TELEFONO AS TELEFONO_SOLICITANTE,
TO_CHAR (RP1.FECHA_NACIMIENTO, 'YYYY-mm-dd') AS FECHA_NACIMIENTO_SOLICITANTE,
RP1.CUIL AS CUIL_SOLICITANTE,
RP1.ESTADO_CIVIL AS ESTADO_CIVIL_SOLICITANTE,
RP1.PROFESION AS PROFESION_SOLICITANTE,
CASE DOMPM1.FK_TIPO_DOMICILIO
    WHEN 1 THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (', ', DOMPM1.CALLE_ALTURA)))))
    WHEN 2 THEN TO_CHAR (DOMPM1.OBSERVACIONES)
    WHEN 3 THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4 THEN CONCAT ( 'Nombre de la Villa/Asentamiento: ', CONCAT ( ASEPM1.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM1.MANZANA, CONCAT (', Casa: ', DOMPM1.CASA)))))
    WHEN 5 THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7 THEN CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (' - ', DOMPM1.CALLE_ALTURA))))
END AS DOMICILIO_SOLICITANTE,
OBS1.DESCRIPCION AS ACLARACIONES_SOLICITANTE,
RP2.ID_PERSONA AS ID_TRAMITANTE,
STD3.descripcion AS TIPO_DOC_TRAMITANTE,
RP2.NUMERO_DOCUMENTO AS NRO_TRAMITANTE,
CONCAT ( RP2.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP2.SEGUNDO_NOMBRE), CONCAT (' ', RP2.TERCER_NOMBRE))) AS NOMBRES_TRAMITANTE,
CONCAT ( RP2.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP2.SEGUNDO_APELLIDO), CONCAT (' ', RP2.TERCER_APELLIDO))) AS APELLIDOS_TRAMITANTE,
NACPM2.DESCRIPCION_NACIONALIDAD AS NACIONALIDAD_TRAMITANTE,
SEXPM2.DESCRIPCION AS SEXO_TRAMITANTE,
RP2.EMAIL AS MAIL_TRAMITANTE,
RP2.TELEFONO AS TELEFONO_TRAMITANTE,
TO_CHAR (RP2.FECHA_NACIMIENTO, 'YYYY-mm-dd') AS FECHA_NACIMIENTO_TRAMITANTE,
RP2.CUIL AS CUIL_TRAMITANTE,
RP2.ESTADO_CIVIL AS ESTADO_CIVIL_TRAMITANTE,
RP2.PROFESION  AS PROFESION_TRAMITANTE,
CASE DOMPM2.FK_TIPO_DOMICILIO
    WHEN 1 THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (', ', DOMPM2.CALLE_ALTURA)))))
    WHEN 2 THEN TO_CHAR (DOMPM2.OBSERVACIONES)
    WHEN 3 THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4 THEN CONCAT ( 'Nombre de la Villa/Asentamiento: ', CONCAT ( ASEP2.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM2.MANZANA, CONCAT (', Casa: ', DOMPM2.CASA)))))
    WHEN 5 THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7 THEN CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (' - ', DOMPM2.CALLE_ALTURA))))
END AS DOMICILIO_TRAMITANTE,
OBS2.DESCRIPCION AS ACLARACIONES_TRAMITANTE,
CERT.DECLARACION_EXTRAVIO AS DECLARACION_EXTRAVIO,
PRE.OTRO_OBSERVACION AS PRESENTADO_ANTE,
MED.TIPO_MATRICULA AS TIPO_MAT_MED,
MED.MATRICULA AS MAT_MEDICO,
MED.NOMBRE AS NOMBRE_MEDICO,
MED.APELLIDO AS APELLIDO_MEDICO,
TO_CHAR (CERT.FECHA_CERTIFICADO_MEDICO, 'YYYY-mm-dd') AS FECHA_CERTI_MEDICO,
CERT.MOTIVO_INMOVILIZACION

FROM
RCE_GED.RCE_CERTIFICADO CERT 
INNER JOIN RCE_GED.RCE_REGISTRO RR ON CERT.ID_REGISTRO = RR.ID_REGISTRO
LEFT JOIN RCE_GED.JBPM4_TASK F ON RR.ID_FLUJO_JBPM = F.EXECUTION_ID_
LEFT OUTER JOIN  RCE_GED.RCE_PAGO_REGISTRO PG ON PG.FK_REGISTRO = RR.ID_REGISTRO
LEFT OUTER JOIN  RCE_GED.RCE_PAGO_REGISTRO_SIEP PSG ON PSG.FK_REGISTRO = RR.ID_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_MEDICO MED ON MED.ID_MEDICO = CERT.FK_MEDICO
LEFT OUTER JOIN RCE_GED.RCE_PRESENTADO_ANTE PRE ON PRE.ID_PRESENTADO_ANTE = CERT.FK_PRESENTADO_ANTE
INNER JOIN RCE_GED.RCE_ACTA_REGISTRO RAR ON (RR.ID_REGISTRO = RAR.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM1 ON RPM1.FK_REGISTRO = RR.ID_REGISTRO AND RPM1.EVENTO = 'onSolicitante'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP1 ON (RPM1.FK_PERSONA = RP1.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD2 ON (RP1.FK_TIPO_DOCUMENTO = STD2.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM1 ON NACPM1.ID_NACIONALIDAD = RP1.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM1 ON SEXPM1.ID_SEXO = RP1.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM1 ON DOMPM1.ID_DOMICILIO = RP1.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM1 ON ASEPM1.ID_ASENTAMIENTO = DOMPM1.FK_ASENTAMIENTO
LEFT OUTER JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SSR ON (RR.FK_SUBTIPO_REGISTRO = SSR.ID_SUBTIPO_REGISTRO)
LEFT OUTER JOIN RCE_GED.RCE_CONDICION_REGISTRO CONDR ON (CONDR.FK_REGISTRO = RR.ID_REGISTRO AND CONDR.VALOR = 1 
    AND CONDR.FK_TIPO_CONDICION NOT IN (434,435,7,11,12,16,17,21,22,1,2,6))
LEFT OUTER JOIN RCE_GED.SYS_TIPO_CONDICION TC ON  RR.FK_SUBTIPO_REGISTRO = TC.FK_SUBTIPO_REGISTRO
    AND TC.ID_TIPO_CONDICION = CONDR.FK_TIPO_CONDICION
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS1 ON RPM1.FK_OBSERVACIONES = OBS1.ID_OBSERVACIONES
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM2 ON RPM2.FK_REGISTRO = RR.ID_REGISTRO
    AND RPM2.EVENTO = 'onTramitante'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP2 ON (RPM2.FK_PERSONA = RP2.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD3 ON (RP2.FK_TIPO_DOCUMENTO = STD3.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM2 ON NACPM2.ID_NACIONALIDAD = RP2.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM2 ON SEXPM2.ID_SEXO = RP2.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM2 ON DOMPM2.ID_DOMICILIO = RP2.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP2 ON ASEP2.ID_ASENTAMIENTO = DOMPM2.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS2 ON RPM2.FK_OBSERVACIONES = OBS2.ID_OBSERVACIONES
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON RR.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
INNER JOIN RCE_GED.EU_LOCALIDAD L ON C.FK_LOCALIDAD = L.ID
INNER JOIN RCE_GED.EU_DEPARTAMENTO DL ON L.ID_DEPARTAMENTO = DL.ID  
------------
WHERE reparticion_usuario != 'TESTGDEBA'
AND rr.FK_SUBTIPO_REGISTRO IN (6,3,4,5,1,2);
