CREATE VIEW CONSULTA_APP_REDIP.DETALLE_GEDOS_VINCULADOS
AS SELECT 
    G.NUMERO AS NUMERO_GEDO,
    G.REPARTICION,
    G.MOTIVO,
    TO_CHAR(G.FECHACREACION, 'YYYY/MM/DD') AS FECHA_CREACION,
    T.ACRONIMO AS TIPO_GEDO,
    G.SISTEMAORIGEN AS SISTEMA_ORIGEN,
    G.SISTEMAINICIADOR AS SISTEMA_INICIADOR,
    ROUND((G.PESO / 1024),2) AS PESO_KB
    
FROM GEDO_GED.GEDO_DOCUMENTO G
INNER JOIN RCE_GED.RCE_DOCUMENTO_VINCULADO DM ON G.NUMERO = DM.NUMERO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO T ON T.ID = G.TIPO
WHERE G.REPARTICION != 'TESTGDEBA'