SELECT
    DOC.NUMERO AS NUMERO_GEDO,
    DOC.MOTIVO,
    DECODE(COM.TIENE_ADJUNTOS, 1, 'SI', 'NO') AS TIENE_ADJUNTOS,
    COM.FECHA_CREACION AS FECHA_CREACION,
    COM.FECHA_ELIMINACION_BANDEJA AS FECHA_ELIM_BANDEJA_USR,
    COM.USUARIO_CREADOR AS USUARIO_CREADOR_COM,
    DOC.REPARTICION AS REPARTICION_INICIAL,
    DOC.USUARIOGENERADOR AS USUARIO_FIRMANTE,
    COM.NRO_COMUNICACION_RESPONDIDA,
    DES.NOMBRE_USUARIO AS DESTINATARIO,
    DES.LEIDO,
    DES.FECHA_ELIMINACION_BANDEJA AS FECHA_ELIM_BANDEJA_DEST

FROM
    GEDO_GED.CCOO_COMUNICACION COM
    INNER JOIN GEDO_GED.CCOO_COMUNICACION_DESTINO DES ON COM.ID = DES.ID_COMUNICACION
    INNER JOIN GEDO_GED.GEDO_DOCUMENTO DOC ON COM.ID_DOCUMENTO = DOC.ID
WHERE
    DES.NOMBRE_USUARIO = 'NAULLUA'

ORDER BY COM.FECHA_CREACION DESC;