SELECT
    DOC.NUMERO AS NRO_GEDO,
    DOC.MOTIVO,
    TRUNC(DOC.FECHACREACION) AS FECHA_CREACION,
    DOC.ANIO AS AÑO,
    DOC.USUARIOGENERADOR AS USUARIO_ORIGEN,
    COM.NOMBRE_COMPLETO_USUARIO AS NOMBRE_USUARIO_ORIGEN,
    DOC.REPARTICION AS REPARTICION_ORIGEN,
    REP_ORIGEN.NOMBRE_REPARTICION AS NOMBRE_REP_ORIGEN,
    MIN_ORIGEN.CODIGO_REPARTICION AS MINISTERIO_ORIGEN,
    MIN_ORIGEN.NOMBRE_REPARTICION AS NOMBRE_MIN_ORIGEN,
    
    DECODE(COM.TIENE_ADJUNTOS,1,'SI','NO') AS TIENE_ADJUNTOS,
    COM.NRO_COMUNICACION_RESPONDIDA,
    
    COM_DEST.NOMBRE_USUARIO AS USUARIO_DESTINO,
    COM_DEST.NOMBRE_COMPLETO_USUARIO AS NOMBRE_USUARIO_DESTINO,
    
    REP_DESTINO.CODIGO_REPARTICION AS REPARTICION_DESTINO,
    REP_DESTINO.NOMBRE_REPARTICION AS NOMBRE_REP_DESTINO,
    MIN_DESTINO.CODIGO_REPARTICION AS MINISTERIO_DESTINO,
    MIN_DESTINO.NOMBRE_REPARTICION AS NOMBRE_MIN_DESTINO,
    TRUNC(COM_DEST.LEIDO) AS LEIDO
    
FROM
    GEDO_GED.CCOO_COMUNICACION COM
    LEFT JOIN GEDO_GED.CCOO_COMUNICACION_DESTINO COM_DEST ON COM.ID = COM_DEST.ID_COMUNICACION
    LEFT JOIN GEDO_GED.GEDO_DOCUMENTO DOC ON COM.ID_DOCUMENTO = DOC.ID
    
	LEFT JOIN TRACK_GED.SADE_REPARTICION REP_ORIGEN ON DOC.REPARTICION = REP_ORIGEN.CODIGO_REPARTICION
	LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_ORIGEN ON REP_ORIGEN.MINISTERIO = MIN_ORIGEN.ID_REPARTICION
    
    LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON COM_DEST.NOMBRE_USUARIO = SU.NOMBRE_USUARIO
        AND SU.ID_SECTOR_USUARIO = (
            SELECT MAX(Z.ID_SECTOR_USUARIO) FROM TRACK_GED.SADE_SECTOR_USUARIO Z 
            WHERE Z.NOMBRE_USUARIO = COM_DEST.NOMBRE_USUARIO
        )
	LEFT JOIN CO_GED.DATOS_USUARIO DU ON DU.USUARIO = SU.NOMBRE_USUARIO
	LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO
    LEFT JOIN TRACK_GED.SADE_REPARTICION REP_DESTINO ON SSI.CODIGO_REPARTICION = REP_DESTINO.ID_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_DESTINO ON MIN_DESTINO.ID_REPARTICION = REP_DESTINO.MINISTERIO   

WHERE
    DOC.REPARTICION IN ('VRATEEHTC','VADCEHTC','VMUAHTC','VMUBHTC','SAYPHTC')
    OR
    REP_DESTINO.CODIGO_REPARTICION IN ('VRATEEHTC','VADCEHTC','VMUAHTC','VMUBHTC','SAYPHTC')

ORDER BY DOC.FECHACREACION ASC
;
    
    