SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
    TYPE USUARIO IS RECORD (
        CUIT NUMBER(11),
        NOMBRE VARCHAR2(50)
    );    
    TYPE TABLA_USUARIOS IS TABLE OF USUARIO;

    L_USUARIOS TABLA_USUARIOS;

BEGIN
    SELECT
        DU.NUMERO_CUIT CUIT,
        SU.NOMBRE_USUARIO    
    BULK COLLECT INTO L_USUARIOS

    FROM 
        TRACK_GED.SADE_SECTOR_USUARIO SU 
        LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
        LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
        LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)
        LEFT JOIN CO_GED.DATOS_USUARIO DU ON (DU.USUARIO = SU.NOMBRE_USUARIO)
    WHERE SR.CODIGO_REPARTICION = 'DIPMJGM' AND SU.ESTADO_REGISTRO = 1 AND DU.ACEPTACION_TYC = 1;

    FOR REG IN L_USUARIOS LOOP
        DBMS_OUTPUT.PUT_LINE( REG.CUIT||'-'||REG.NOMBRE );
    END LOOP;
END;