SET SERVEROUTPUT ON 
SET DEFINE OFF

DECLARE

-- CURSOR PARA OBTENER REPARTICIONES --
CURSOR C_REPARTICIONES IS
	SELECT 
		SR.CODIGO_REPARTICION AS CODIGO_VIEJO,
		MT.DESTINO_REPARTICION AS CODIGO_NUEVO
	FROM (
		SELECT DISTINCT 
		REGEXP_SUBSTR(GROUPID_,'[^.]+') AS CODIGO_REPA
		FROM RCE_GED.JBPM4_PARTICIPATION
	) AUX
	
	INNER JOIN TRACK_GED.SADE_REPARTICION SR 
		ON SR.CODIGO_REPARTICION = AUX.CODIGO_REPA
	INNER JOIN EU_GED.MIG_TAREA MT
		ON MT.ORIGEN_REPARTICION = SR.CODIGO_REPARTICION 

	WHERE 
		SR.ESTADO_REGISTRO = 0
		AND SR.VIGENCIA_HASTA > TO_DATE('01/01/2024','DD/MM/YYYY')
		AND MT.TIPO_MIGRACION = 'MIGRACION_REPARTICION'
		AND MT.ESTADO = 'FINALIZADA'
		AND MT.MODULO = 'EU';

-- PROCEDIMIENTO PARA ACTUALIZAR BUZONES --
PROCEDURE ACTUALIZAR_BUZON(
	P_COD_REPARTICION_ORIGEN IN VARCHAR2,
	P_COD_REPARTICION_DESTINO IN VARCHAR2) 
IS 
	L_REGISTROS_MODIFICADOS NUMBER := 0;

BEGIN
	DBMS_OUTPUT.PUT_LINE('ACTUALIZANDO: '||P_COD_REPARTICION_ORIGEN||' -> '||P_COD_REPARTICION_DESTINO);
	
	-- INICIO BLOQUE UPDATE: JBPM4_PARTICIPATION
	UPDATE RCE_GED.JBPM4_PARTICIPATION
	SET GROUPID_ = REPLACE(GROUPID_, P_COD_REPARTICION_ORIGEN, P_COD_REPARTICION_DESTINO)
	WHERE GROUPID_ LIKE P_COD_REPARTICION_ORIGEN||'.%';
	-- FIN BLOQUE UPDATE
	
	L_REGISTROS_MODIFICADOS := L_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;

	-- INICIO BLOQUE UPDATE: JBPM4_VARIABLE
	UPDATE RCE_GED.JBPM4_VARIABLE
	SET STRING_VALUE_ = REPLACE(STRING_VALUE_, P_COD_REPARTICION_ORIGEN, P_COD_REPARTICION_DESTINO)
	WHERE KEY_ = 'grupoAsignado' AND STRING_VALUE_ LIKE P_COD_REPARTICION_ORIGEN||'.%';
	-- FIN BLOQUE UPDATE
	
	L_REGISTROS_MODIFICADOS := L_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;

	COMMIT; 
	DBMS_OUTPUT.PUT_LINE('SE MODIFICARON '||L_REGISTROS_MODIFICADOS||' REGISTROS');
	DBMS_OUTPUT.PUT_LINE('COMMIT REALIZADO');
	DBMS_OUTPUT.NEW_LINE;

EXCEPTION		
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE('    ' || SUBSTR(SQLERRM,1, 200));
		DBMS_OUTPUT.NEW_LINE;

END ACTUALIZAR_BUZON;


-- MODULO PRINCIPAL --
BEGIN
	DBMS_OUTPUT.PUT_LINE('***COMIENZA SCRIPT***');
	DBMS_OUTPUT.NEW_LINE;

	FOR R_REPARTICION IN C_REPARTICIONES LOOP
		ACTUALIZAR_BUZON(R_REPARTICION.CODIGO_VIEJO, R_REPARTICION.CODIGO_NUEVO);		
	END LOOP;

	DBMS_OUTPUT.PUT_LINE('***SCRIPT FINALIZADO***');

EXCEPTION		
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE('    ' || SUBSTR(SQLERRM,1, 200));
		
END;

