SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE

-- TABLA CON VALORES A ACTUALIZAR
TYPE REC_CODIGOS IS RECORD (
	COD_ORIGEN VARCHAR2(100),
	COD_DESTINO VARCHAR2(100)
);
TYPE TABLE_CODIGOS IS TABLE OF REC_CODIGOS;
T_CODIGOS TABLE_CODIGOS;

-- FUNCION PARA INICIALIZAR RECORD
FUNCTION INIT_REC(
	COD_ORIGEN VARCHAR2, 
	COD_DESTINO VARCHAR2
)
RETURN REC_CODIGOS
IS 
    R REC_CODIGOS;
BEGIN
    R.COD_ORIGEN := COD_ORIGEN;
    R.COD_DESTINO := COD_DESTINO;
    RETURN R;
END INIT_REC;

-- PROCEDIMIENTO PARA ACTUALIZAR BUZONES
PROCEDURE ACTUALIZAR_BUZONES(
    P_COD_REPARTICION_ORIGEN IN VARCHAR2,
    P_COD_REPARTICION_DESTINO IN VARCHAR2
) 
IS 
    L_REGISTROS_MODIFICADOS NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('ACTUALIZANDO: ' || P_COD_REPARTICION_ORIGEN || ' -> ' || P_COD_REPARTICION_DESTINO);
    
    -- INICIO BLOQUE UPDATE: JBPM4_PARTICIPATION
    UPDATE RCE_GED.JBPM4_PARTICIPATION
    SET GROUPID_ = REPLACE(GROUPID_, P_COD_REPARTICION_ORIGEN, P_COD_REPARTICION_DESTINO)
    WHERE GROUPID_ LIKE P_COD_REPARTICION_ORIGEN || '.%';
    -- FIN BLOQUE UPDATE
    
	L_REGISTROS_MODIFICADOS := L_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;

    -- INICIO BLOQUE UPDATE: JBPM4_VARIABLE
    UPDATE RCE_GED.JBPM4_VARIABLE
    SET STRING_VALUE_ = REPLACE(STRING_VALUE_, P_COD_REPARTICION_ORIGEN, P_COD_REPARTICION_DESTINO)
    WHERE KEY_ = 'grupoAsignado' AND STRING_VALUE_ LIKE P_COD_REPARTICION_ORIGEN || '.%';
    -- FIN BLOQUE UPDATE
    
	L_REGISTROS_MODIFICADOS := L_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;

    COMMIT; 
    DBMS_OUTPUT.PUT_LINE('SE MODIFICARON ' || L_REGISTROS_MODIFICADOS || ' REGISTROS');
    DBMS_OUTPUT.PUT_LINE('COMMIT REALIZADO');
    DBMS_OUTPUT.NEW_LINE;

EXCEPTION		
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE('    ' || SUBSTR(SQLERRM,1, 200));
		DBMS_OUTPUT.NEW_LINE;
	   
END ACTUALIZAR_BUZONES;


-- MODULO PRINCIPAL
BEGIN		

DBMS_OUTPUT.PUT_LINE('***COMIENZA SCRIPT***');
DBMS_OUTPUT.NEW_LINE;

-- CODIGOS DE REPARTICIONES A ACTUALIZAR
T_CODIGOS := TABLE_CODIGOS(
	INIT_REC('DL7664MGGP','DL7664JAGGP'),
	INIT_REC('DL7665MGGP','DL7665JAGGP'),
	INIT_REC('DL2609MGGP','DL2609JAGGP')
);

FOR REC IN T_CODIGOS LOOP
	ACTUALIZAR_BUZONES(REC.COD_ORIGEN, REC.COD_DESTINO);
END LOOP;	

DBMS_OUTPUT.PUT_LINE('***SCRIPT FINALIZADO***');

EXCEPTION		
	WHEN OTHERS THEN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE('    ' || SUBSTR(SQLERRM,1, 200));

END;