SELECT DISTINCT
    SU.NOMBRE_USUARIO,
    DU.APELLIDO_NOMBRE APELLIDO_NOMBRE,
    DECODE(SU.ESTADO_REGISTRO, 0, 'BAJA', 1, 'ALTA') ESTADO,
    DU.NUMERO_CUIT CUIT,
    DU.MAIL,
    C.CARGO,
    TO_CHAR(SU.FECHA_CREACION,'DD/MM/YYYY') FECHA_CREACION,
    DECODE(DU.ACEPTACION_TYC, 0, 'NO', 1, 'SI') PRIMER_INGRESO,
    SSI.CODIGO_SECTOR_INTERNO CODIGO_SECTOR_INTERNO,
    SSI.NOMBRE_SECTOR_INTERNO NOMBRE_SECTOR_INTERNO,
    SR.CODIGO_REPARTICION CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION  NOMBRE_REPARTICION,
    SR1.CODIGO_REPARTICION CODIGO_MINISTERIO,
    SR1.NOMBRE_REPARTICION  NOMBRE_MINISTERIO,
    SRH.CODIGO_REPARTICION CODIGO_REP_HABILITADA,
    SRH.NOMBRE_REPARTICION  NOMBRE_REP_HABILITADA,
    SR1H.CODIGO_REPARTICION CODIGO_MIN_HABILITADA,
    SR1H.NOMBRE_REPARTICION  NOMBRE_MIN_HABILITADA
FROM 
    TRACK_GED.SADE_SECTOR_USUARIO SU 
    LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)
    LEFT JOIN CO_GED.DATOS_USUARIO DU ON (DU.USUARIO = SU.NOMBRE_USUARIO)
    LEFT JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    LEFT JOIN TRACK_GED.SADE_USR_REPA_HABILITADA RH ON RH.NOMBRE_USUARIO = SU.NOMBRE_USUARIO    
    LEFT JOIN TRACK_GED.SADE_REPARTICION SRH ON (RH.ID_REPARTICION = SRH.ID_REPARTICION) 
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR1H ON (SRH.MINISTERIO = SR1H.ID_REPARTICION)

WHERE
    SU.ESTADO_REGISTRO = 1 AND SRH.CODIGO_REPARTICION IS NOT NULL
    

ORDER BY SR.CODIGO_REPARTICION, SU.NOMBRE_USUARIO;