SELECT
    DISTINCT U.USUARIO,
    U.MAIL AS "MAIL USUARIOS ACTIVOS"

FROM GEDO_GED.GEDO_HISTORIAL GH
INNER JOIN CO_GED.DATOS_USUARIO U ON GH.USUARIO = U.USUARIO
LEFT  JOIN  CO_GED.CARGOS C ON C.ID = U.CARGO
INNER JOIN TRACK_GED.SADE_SECTOR_USUARIO S ON S.NOMBRE_USUARIO = U.USUARIO

WHERE S.ESTADO_REGISTRO = 1 AND U.ACEPTACION_TYC = 1

UNION

SELECT
    DISTINCT U.USUARIO,
    U.MAIL AS "MAIL USUARIOS ACTIVOS"

FROM EE_GED.HISTORIALOPERACION HO
INNER JOIN CO_GED.DATOS_USUARIO U ON HO.USUARIO = U.USUARIO
LEFT  JOIN  CO_GED.CARGOS C ON C.ID = U.CARGO
INNER JOIN TRACK_GED.SADE_SECTOR_USUARIO S ON S.NOMBRE_USUARIO = U.USUARIO

WHERE S.ESTADO_REGISTRO = 1 AND U.ACEPTACION_TYC = 1
;