WITH INFO_IPS AS (
SELECT
    MINIS.CODIGO_REPARTICION AS MINISTERIO,
    REPA.CODIGO_REPARTICION AS REPARTICION,
    SECTOR.CODIGO_SECTOR_INTERNO AS SECTOR,
    SECTOR_USUARIO.NOMBRE_USUARIO,
    DECODE(SECTOR_USUARIO.ESTADO_REGISTRO, 0, 'BAJA', 1, 'ALTA') ESTADO_USUARIO,
    --DECODE(DATOS_USUARIO.ACEPTACION_TYC, 0, 'NO', 1, 'SI') PRIMER_INGRESO,
    DECODE(SECTOR_USUARIO.ESTADO_REGISTRO, 1, 1, 0) AS AUX_SUMA
FROM
    TRACK_GED.SADE_REPARTICION MINIS
    LEFT JOIN TRACK_GED.SADE_REPARTICION REPA ON MINIS.ID_REPARTICION = REPA.MINISTERIO
    LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SECTOR ON SECTOR.CODIGO_REPARTICION = REPA.ID_REPARTICION
    LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SECTOR_USUARIO ON SECTOR_USUARIO.ID_SECTOR_INTERNO = SECTOR.ID_SECTOR_INTERNO
    LEFT JOIN CO_GED.DATOS_USUARIO DATOS_USUARIO ON (DATOS_USUARIO.USUARIO = SECTOR_USUARIO.NOMBRE_USUARIO)
WHERE
    MINIS.CODIGO_REPARTICION = 'IPS'
    AND MINIS.VIGENCIA_HASTA > SYSDATE
    AND REPA.VIGENCIA_HASTA > SYSDATE
    AND SECTOR.VIGENCIA_HASTA > SYSDATE
)
SELECT
    REPARTICION,
    SECTOR,
    SUM(AUX_SUMA) AS CANTIDAD_USUARIOS
FROM INFO_IPS
WHERE (ESTADO_USUARIO = 'ALTA' OR ESTADO_USUARIO IS NULL)
GROUP BY REPARTICION, SECTOR
ORDER BY CANTIDAD_USUARIOS
;