SELECT 
DISTINCT LOWER(REGEXP_REPLACE(REGEXP_SUBSTR(DU.MAIL, '[^@]+', 1, 2),'[^A-Z0-9-.]' , '')) AS DOMINIOS

FROM TRACK_GED.SADE_SECTOR_USUARIO SU
INNER JOIN CO_GED.DATOS_USUARIO DU ON DU.USUARIO = SU.NOMBRE_USUARIO
WHERE DU.ACEPTACION_TYC = 1 AND SU.ESTADO_REGISTRO = 1
ORDER BY DOMINIOS ASC;