SELECT
    GH.ACTIVIDAD,
    COUNT (DISTINCT GH.USUARIO) AS TOTAL_USUARIOS_ACTIVOS

FROM GEDO_GED.GEDO_HISTORIAL GH
INNER JOIN CO_GED.DATOS_USUARIO U ON GH.USUARIO = U.USUARIO
LEFT  JOIN  CO_GED.CARGOS C ON C.ID = U.CARGO
INNER JOIN TRACK_GED.SADE_SECTOR_USUARIO S ON S.NOMBRE_USUARIO = U.USUARIO

WHERE S.ESTADO_REGISTRO = 1 AND U.ACEPTACION_TYC = 1
GROUP BY GH.ACTIVIDAD
;

SELECT COUNT(*) AS "CON PRIMER INGRESO"

FROM 
    CO_GED.DATOS_USUARIO DU
    LEFT OUTER JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON (DU.USUARIO = SU.NOMBRE_USUARIO) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)

WHERE 
    SU.ESTADO_REGISTRO = 1 AND ACEPTACION_TYC = 1;