SELECT
    MINIS.CODIGO_REPARTICION AS CODIGO_MINISTERIO,
    MINIS.NOMBRE_REPARTICION AS NOMBRE_MINISTERIO,
    REPA.CODIGO_REPARTICION AS CODIGO_REPARTICION,
    REPA.NOMBRE_REPARTICION,    
    SI.CODIGO_SECTOR_INTERNO,
    SI.NOMBRE_SECTOR_INTERNO,
    REPA.VIGENCIA_DESDE,
    REPA.VIGENCIA_HASTA
    
FROM 
TRACK_GED.SADE_SECTOR_INTERNO SI
INNER JOIN TRACK_GED.SADE_REPARTICION REPA ON REPA.ID_REPARTICION = SI.CODIGO_REPARTICION
INNER JOIN  TRACK_GED.SADE_REPARTICION MINIS ON MINIS.ID_REPARTICION = REPA.MINISTERIO

WHERE REPA.ESTADO_REGISTRO = 1 AND MINIS.ESTADO_REGISTRO = 1 AND
TRUNC(REPA.VIGENCIA_HASTA) > TRUNC(SYSDATE) AND TRUNC(MINIS.VIGENCIA_HASTA) > TRUNC(SYSDATE)
ORDER BY MINIS.NOMBRE_REPARTICION, REPA.NOMBRE_REPARTICION