SELECT
    DU.USUARIO,
    DU.APELLIDO_NOMBRE AS "APELLIDO NOMBRE",
    DU.NUMERO_CUIT AS "NUMERO CUIT",
    DU.MAIL,
    C.CARGO,
    TO_CHAR(SU.FECHA_CREACION,'DD/MM/YYYY') AS "FECHA CREACION",
    DECODE(DU.ACEPTACION_TYC, 0, 'NO', 1, 'SI') AS "PRIMER INGRESO",
    SSI.CODIGO_SECTOR_INTERNO AS "CODIGO SECTOR INTERNO",
    SSI.NOMBRE_SECTOR_INTERNO AS "NOMBRE SECTOR INTERNO",
    SR.CODIGO_REPARTICION AS "CODIGO REPARTICION",
    SR.NOMBRE_REPARTICION AS "NOMBRE REPARTICION"

FROM
    CO_GED.DATOS_USUARIO DU
    LEFT OUTER JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON (DU.USUARIO = SU.NOMBRE_USUARIO) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)

WHERE 
    SU.ESTADO_REGISTRO = 1
    AND SR1.CODIGO_REPARTICION = 'ADA'
    AND SU.FECHA_CREACION BETWEEN TO_DATE('2019/01/01','YYYY/MM/DD') AND TO_DATE('2019/12/31','YYYY/MM/DD');