WITH USUARIOS AS (
SELECT 
SU.NOMBRE_USUARIO AS USUARIO,
SR.CODIGO_REPARTICION CODIGO_REPARTICION
FROM 
TRACK_GED.SADE_SECTOR_USUARIO SU 
LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)
LEFT JOIN CO_GED.DATOS_USUARIO DU ON (DU.USUARIO = SU.NOMBRE_USUARIO)
WHERE SR1.CODIGO_REPARTICION = 'CGP' AND DU.ACEPTACION_TYC = 1
)

-- ACTIVIDADES GEDO
SELECT
    U.USUARIO,
    U.CODIGO_REPARTICION,
    HIST.ACTIVIDAD,
    HIST.FECHA_INICIO,
    HIST.FECHA_FIN,
    GEDO.NUMERO NRO_GEDO,
    '----' AS NRO_EXPEDIENTE,
    '----' AS CODIGO_TRATA,
    -- DESTINO
	null AS DESTINATARIO,
	null AS CODIGO_SECTOR_DESTINO,
	null AS CODIGO_REPARTICION_DESTINO,
	null AS CODIGO_MINISTERIO_DESTINO

FROM
    --TAREA
    GEDO_GED.GEDO_HISTORIAL HIST
	INNER JOIN USUARIOS U ON HIST.USUARIO = U.USUARIO
    INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON HIST.WORKFLOWORIGEN = GEDO.WORKFLOWORIGEN

WHERE
    TRUNC(HIST.FECHA_INICIO) = TRUNC(SYSDATE-1)


UNION


-- ASOCIACIONES DE DOCUMENTOS A EXPEDIENTES
SELECT
	U.USUARIO,
    U.CODIGO_REPARTICION,
    'Asociar Documento' AS ACTIVIDAD,
    D.FECHA_ASOCIACION AS FECHA_INICIO,
    D.FECHA_ASOCIACION AS FECHA_FIN,
    D.NUMERO_SADE NRO_GEDO,
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'-'||
        EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    TRATA.CODIGO_TRATA,
    -- DESTINO
	null AS DESTINATARIO,
	null AS CODIGO_SECTOR_DESTINO,
	null AS CODIGO_REPARTICION_DESTINO,
	null AS CODIGO_MINISTERIO_DESTINO

FROM
    -- TAREA
    EE_GED.DOCUMENTO D
	INNER JOIN USUARIOS U ON D.USUARIO_ASOCIADOR = U.USUARIO
    INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS ED ON ED.ID_DOCUMENTO = D.ID
    INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = ED.ID
    INNER JOIN EE_GED.TRATA TRATA ON TRATA.ID = EE.ID_TRATA 

WHERE
    TRUNC(D.FECHA_ASOCIACION) = TRUNC(SYSDATE-1)    

UNION

--ACTIVIDADES EXPEDIENTE ELECTRONICO
SELECT
    U.USUARIO,
    U.CODIGO_REPARTICION,
    HIST.TIPO_OPERACION ACTIVIDAD,
    HIST.FECHA_OPERACION FECHA_INICIO,
    HIST.FECHA_OPERACION FECHA_FIN,
    '----' NRO_GEDO,
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'-'||
        EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    TRATA.CODIGO_TRATA,
    --DESTINO 
	REGEXP_REPLACE(HIST.DESTINATARIO,'[^A-Z0-9-#-]','') AS DESTINATARIO,
	HIST.CODIGO_SECTOR_DESTINO,
	REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') AS CODIGO_REPARTICION_DESTINO,
	HIST.CODIGO_JURISDICCION_DESTINO AS CODIGO_MINISTERIO_DESTINO
FROM
    EE_GED.HISTORIALOPERACION HIST
    INNER JOIN USUARIOS U ON HIST.USUARIO = U.USUARIO
    INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
    INNER JOIN EE_GED.TRATA TRATA ON TRATA.ID = EE.ID_TRATA
WHERE
    TRUNC(HIST.FECHA_OPERACION) = TRUNC(SYSDATE-1)