SELECT
    SR.CODIGO_REPARTICION,
    SR.NOMBRE_REPARTICION,
    (SELECT CODIGO_REPARTICION FROM TRACK_GED.SADE_REPARTICION WHERE ID_REPARTICION=SR.REP_PADRE) REP_PADRE,
    (SELECT CODIGO_REPARTICION FROM TRACK_GED.SADE_REPARTICION WHERE ID_REPARTICION=SR.MINISTERIO) MINISTERIO,
    LEVEL NIVEL,
    SYS_CONNECT_BY_PATH(CODIGO_REPARTICION, '/') RUTA

FROM TRACK_GED.SADE_REPARTICION SR
WHERE SR.ESTADO_REGISTRO = 1 AND TRUNC(SR.VIGENCIA_HASTA) > TRUNC(SYSDATE)
--START WITH SR.CODIGO_REPARTICION = 'MJGM'
CONNECT BY NOCYCLE PRIOR SR.ID_REPARTICION = SR.REP_PADRE
ORDER SIBLINGS BY CODIGO_REPARTICION ASC;