SELECT * FROM (

SELECT
-- TASK RCE --
T.EXECUTION_ID_,
T.EXECUTION_,
T.ACTIVITY_NAME_,
T.CREATE_,

-- VARIABLE RCE --
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'fechaEnvioFirmaDigital' 
AND V.EXECUTION_ = T.EXECUTION_)  AS fechaEnvioFirmaDigital,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_)  AS idFlujoFirma,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'creador' 
AND V.EXECUTION_ = T.EXECUTION_)  AS creador,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'firmaInterviniente' 
AND V.EXECUTION_ = T.EXECUTION_)  AS firmaInterviniente,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'firmaFuncionario' 
AND V.EXECUTION_ = T.EXECUTION_)  AS firmaFuncionario,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idTemporalActa' 
AND V.EXECUTION_ = T.EXECUTION_)  AS idTemporalActa,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'actaFirmadaConDocumentoDigitalizado' 
AND V.EXECUTION_ = T.EXECUTION_)  AS actaFirmadaConDocDigitalizado,
(SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'grupoAsignado' 
AND V.EXECUTION_ = T.EXECUTION_)  AS grupoAsignado,

-- VARIABLE GEDO --
(SELECT VAR.LONG_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'reintentosCierre' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) reintentosCierre,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'timeoutReintentosCierre' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) timeoutReintentosCierre,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'acronimoTipoDocumento' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) acronimoTipoDocumento,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioCreador' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) usuarioCreador,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'motivo' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) motivo,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioFirmante' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) usuarioFirmante,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'mensajeUsuario' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) mensajeUsuario,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'fecha_pedido_firma' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) fecha_pedido_firma,

(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'numero_documento_original' 
AND VAR.EXECUTION_ = 
REGEXP_SUBSTR((SELECT V.STRING_VALUE_ FROM RCE_GED.JBPM4_VARIABLE V WHERE V.KEY_ = 'idFlujoFirma' 
AND V.EXECUTION_ = T.EXECUTION_), '[^.]+', 1, 2)) numero_documento_original

FROM  RCE_GED.JBPM4_TASK T
)    
WHERE 
ACTIVITY_NAME_ = 'Esperar Firma Digital';