SELECT
      TR.DESCRIPCION AS TIPO
    , SR.DESCRIPCION AS SUBTIPO
    --, COALESCE(SCIR.NOMBRE,SCDT.NOMBRE) AS NOMBRE_CIRCUNSCRIPCION
    , COUNT(*) AS CANTIDAD
    
FROM
    RCE_GED.RCE_REGISTRO R
    INNER JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SR ON R.FK_SUBTIPO_REGISTRO = SR.ID_SUBTIPO_REGISTRO
    INNER JOIN RCE_GED.SYS_TIPO_REGISTRO TR ON SR.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO
    
    /*
    ----------
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCIR ON R.FK_ID_CIRCUNSCRIPCION = SCIR.ID_CIRCUNSCRIPCION
    ----------
    LEFT JOIN RCE_GED.RCE_DIGITAL RD ON R.ID_REGISTRO = RD.ID_REGISTRO
    LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT ON RD.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO
    LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SCDT ON DT.FK_CIRCUNSCRIPCION = SCDT.ID_CIRCUNSCRIPCION
    */

WHERE
    R.FECHA_ANULACION IS NULL 
    AND R.FECHA_INUTILIZACION IS NULL

GROUP BY ROLLUP (
          TR.DESCRIPCION
        , SR.DESCRIPCION
        --, COALESCE(SCIR.NOMBRE,SCDT.NOMBRE)
        )
;