SELECT
    EE.ID,
    EE.ID_TRATA,
    H.ULTIMA_OPERACION
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
INNER JOIN (
    SELECT H.ID_EXPEDIENTE, MAX(H.FECHA_OPERACION) AS ULTIMA_OPERACION
    FROM EE_GED.HISTORIALOPERACION H
    GROUP BY H.ID_EXPEDIENTE
) H ON H.ID_EXPEDIENTE = EE.ID
WHERE EE.FECHA_CREACION > TRUNC(SYSDATE);

-------------------------------------------------------------------------

SELECT
    EE.ID,
    EE.ID_TRATA,
    UO.FECHA_OPERACION AS ULTIMA_OPERACION
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
INNER JOIN (
	SELECT 
        H.ID_EXPEDIENTE, 
        H.FECHA_OPERACION,
        ROW_NUMBER() OVER (PARTITION BY H.ID_EXPEDIENTE ORDER BY H.ID DESC) AS rn
    	FROM EE_GED.HISTORIALOPERACION H
) UltimaOperacion UO 
    ON UO.ID_EXPEDIENTE = EE.ID AND UO.rn = 1
WHERE EE.FECHA_CREACION > TRUNC(SYSDATE);