-- "ERROR DE NACIONALIDAD" REGISTROS PARA SER TOMADOS EN EL REPROCESO

SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
V_REGISTROS_MODIFICADOS NUMBER (30);
V_NUMERO_ESPERADO NUMBER (30);
REG_ACT_EXCEPTION EXCEPTION;

TYPE TABLA_ID_IFAZ IS TABLE OF NUMBER(10);
L_ID_IFAZ TABLA_ID_IFAZ;

BEGIN

    SELECT ID_IFAZ_DEFUNCION_RENAPER BULK COLLECT INTO L_ID_IFAZ
    FROM RCE_GED.RCE_IFAZ_DEFUNCION_RENAPER
    WHERE INFORME_FALLECIMIENTO_CODIGO = 6;    
    
	V_NUMERO_ESPERADO := L_ID_IFAZ.COUNT;
	V_REGISTROS_MODIFICADOS := 0;

	DBMS_OUTPUT.PUT_LINE ('***COMIENZA SCRIPT***');
	DBMS_OUTPUT.PUT_LINE ('SE ESPERAN MODIFICAR '||V_NUMERO_ESPERADO ||' REGISTROS');

-- BLOQUE UPDATE

FOR I IN 1..L_ID_IFAZ.COUNT LOOP
    UPDATE RCE_GED.RCE_IFAZ_DEFUNCION_RENAPER
    SET INFORME_FALLECIMIENTO_CODIGO = NULL,
    INFORME_FALLECIMIENTO_MENSAJE = NULL
    WHERE ID_IFAZ_DEFUNCION_RENAPER = L_ID_IFAZ(I);
    V_REGISTROS_MODIFICADOS := V_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;
END LOOP;

-- BLOQUE UPDATE END

COMMIT;
DBMS_OUTPUT.PUT_LINE ('SE MODIFICARON '||V_REGISTROS_MODIFICADOS||' REGISTROS');
DBMS_OUTPUT.PUT_LINE ('***COMMIT REALIZADO***');

EXCEPTION
	WHEN REG_ACT_EXCEPTION THEN
	BEGIN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE ('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE ('LA CANTIDAD DE REGISTROS MODIFICADOS NO COINCIDE CON LA ESPERADA ' || V_REGISTROS_MODIFICADOS);
	END;

	WHEN OTHERS THEN
	BEGIN
		ROLLBACK;
		DBMS_OUTPUT.PUT_LINE ('SE REALIZA ROLLBACK DE TRANSACCION: ');
		DBMS_OUTPUT.PUT_LINE (' ' || SUBSTR (SQLERRM,1, 200));
	END;

END;