
--CANTIDAD DE EXPEDIENTES CARATULADOS--
SELECT COUNT (*) AS "TOTAL CARATULADOS" FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO;

--CANTIDAD DE EXPEDIENTES CARATULADOS (SOLO REDIP)--
SELECT COUNT (*) AS "CARATULADOS (SOLO REDIP)"
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO WHERE USUARIO_CREADOR = 'TADCARATULADORRPP';

--CANTIDAD DE EXPEDIENTES CARATULADOS (SIN REDIP)--
SELECT COUNT (*) AS "CARATULADOS (SIN REDIP)"
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO WHERE USUARIO_CREADOR <> 'TADCARATULADORRPP';

--CANTIDAD DE EXPEDIENTES CARATULADOS ULTIMOS 30 DIAS--
SELECT COUNT (*) AS "CARATULADOS ULTIMOS 30 DIAS"
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO WHERE FECHA_CREACION BETWEEN (SYSDATE - 30) AND SYSDATE;

--------------------------------------------------------------------------------------------------------------------------------

--CANTIDAD DE MOVIMIENTOS--
SELECT COUNT(*) AS "TOTAL MOVIMIENTOS"
FROM EE_GED.HISTORIALOPERACION;

--CANTIDAD DE MOVIMIENTOS ULTIMOS 30 DIAS--
SELECT COUNT(*) AS "MOVIMIENTOS ULTIMOS 30 DIAS"
FROM EE_GED.HISTORIALOPERACION WHERE FECHA_OPERACION BETWEEN (SYSDATE - 30) AND SYSDATE;

--------------------------------------------------------------------------------------------------------------------------------

--CANTIDAD DE EXPEDIENTES ARCHIVADOS (SIN REDIP)--
SELECT COUNT (*) AS  "ARCHIVADOS (SIN REDIP)"
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO 
WHERE 
    ESTADO = 'Guarda Temporal'
    AND USUARIO_CREADOR <> 'TADCARATULADORRPP';
--------------------------------------------------------------------------------------------------------------------------------

--CANTIDAD DE ALTAS DE USUARIOS (CON PRIMER INGRESO / SIN PRIMER INGRESO / TOTAL)--

SELECT COUNT(*) AS "ALTA DE USUARIOS (TOTAL)"

FROM
    CO_GED.DATOS_USUARIO DU
    LEFT OUTER JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    left outer join TRACK_GED.SADE_SECTOR_USUARIO SU on (DU.USUARIO = SU.NOMBRE_USUARIO) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)

WHERE 
    SU.ESTADO_REGISTRO = 1;


SELECT COUNT(*) AS "CON PRIMER INGRESO"

FROM 
    CO_GED.DATOS_USUARIO DU
    LEFT OUTER JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON (DU.USUARIO = SU.NOMBRE_USUARIO) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)

WHERE 
    SU.ESTADO_REGISTRO = 1 AND ACEPTACION_TYC = 1;


SELECT COUNT(*) AS "SIN PRIMER INGRESO"

FROM
    CO_GED.DATOS_USUARIO DU
    LEFT OUTER JOIN CO_GED.CARGOS C ON (DU.CARGO = C.ID) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON (DU.USUARIO = SU.NOMBRE_USUARIO) 
    LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)

WHERE
    SU.ESTADO_REGISTRO = 1 AND ACEPTACION_TYC = 0;

--------------------------------------------------------------------------------------------------------------------------------

--TOTAL DE GEDOS CREADOS (SIN REDIP)--
SELECT COUNT(*) AS "TOTAL GEDOS (SIN REDIP)"

FROM 
    GEDO_GED.GEDO_DOCUMENTO GD 
    INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GT ON ( GD.TIPO = GT.ID  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR ON ( GD.REPARTICION = SR.CODIGO_REPARTICION  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON ( SR.MINISTERIO = SR1.ID_REPARTICION  )
           
WHERE 
    GT.ACRONIMO NOT IN ('NOTA','MEMO')  /* PARA VISUALIZAR SOLO CCOO, REEMPLAZAR "NOT IN" POR "IN" */
    AND SR.CODIGO_REPARTICION NOT LIKE 'DL%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDDR%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDSR%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'SDZ%MGGP'
    AND SR.CODIGO_REPARTICION NOT LIKE '%RDLP'
    AND SR.CODIGO_REPARTICION NOT LIKE 'TESTGDEBA';


--TOTAL GEDOS CREADOS (CON REDIP)--
SELECT COUNT(*) AS "TOTAL GEDOS (CON REDIP)"

FROM
    GEDO_GED.GEDO_DOCUMENTO GD 
    INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GT ON ( GD.TIPO = GT.ID  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR ON ( GD.REPARTICION = SR.CODIGO_REPARTICION  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON ( SR.MINISTERIO = SR1.ID_REPARTICION  )
           
WHERE 
    GT.ACRONIMO NOT IN ('NOTA','MEMO') /* PARA VISUALIZAR SOLO CCOO, REEMPLAZAR "NOT IN" POR "IN" */
    AND SR.CODIGO_REPARTICION NOT LIKE 'TESTGDEBA';
    
--------------------------------------------------------------------------------------------------------------------------------    
         
--TOTAL DE COMUNICACIONES CREADAS (CCOO)--                  
SELECT COUNT(*) AS "TOTAL CCOO"

FROM 
    GEDO_GED.GEDO_DOCUMENTO GD 
    INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GT ON ( GD.TIPO = GT.ID  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR ON ( GD.REPARTICION = SR.CODIGO_REPARTICION  )  
    INNER JOIN TRACK_GED.SADE_REPARTICION SR1 ON ( SR.MINISTERIO = SR1.ID_REPARTICION  )

WHERE 
    GT.ACRONIMO IN ('NOTA','MEMO') /* PARA VISUALIZAR SOLO CCOO, REEMPLAZAR "NOT IN" POR "IN" */
    AND SR.CODIGO_REPARTICION NOT LIKE 'TESTGDEBA'
    