SELECT
    CODIGO,
    DECODE(CONSULTA,0,'NO','SI') AS CONSULTA,
    DECODE(HABILITADA,0,'NO','SI') AS HABILITADA,
    DECODE(INICIADORA,0,'NO','SI') AS INICIADORA
    
FROM (
    SELECT TR.CODIGO, 'CONSULTA' AS PERMISO FROM RLM_GED.RLM_REPARTICION_CONSULTA R
    INNER JOIN RLM_GED.SIS_TIPO_REGISTRO TR ON R.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO WHERE REPARTICION = 'TESTGDEBA'
UNION
    SELECT TR.CODIGO, 'HABILITADA' AS PERMISO FROM RLM_GED.RLM_REPARTICION_HABILITADA R
    INNER JOIN RLM_GED.SIS_TIPO_REGISTRO TR ON R.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO WHERE REPARTICION = 'TESTGDEBA'
UNION
    SELECT TR.CODIGO, 'INICIADORA' AS PERMISO FROM RLM_GED.RLM_REPARTICION_INICIADORA R
    INNER JOIN RLM_GED.SIS_TIPO_REGISTRO TR ON R.FK_TIPO_REGISTRO = TR.ID_TIPO_REGISTRO WHERE REPARTICION = 'TESTGDEBA'
)

PIVOT
(
    COUNT(PERMISO) FOR PERMISO IN (
            'HABILITADA' AS HABILITADA,
            'INICIADORA' AS INICIADORA,
            'CONSULTA' AS CONSULTA
            )
)
ORDER BY CODIGO;