SELECT

REG.FECHA_ALTA,
REV_P.CUIT,
REV_PJ.RAZON_SOCIAL,

(SELECT DFVAL.VALUE_STR FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'band_seleccionar_actividad' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS ACTIVIDAD,

(SELECT DFVAL.VALUE_STR FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'departamento_40' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS DEPARTAMENTO,

(SELECT DFVAL.VALUE_STR FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'localidad_40' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS LOCALIDAD,

(SELECT DFVAL.VALUE_STR FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'calle' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS CALLE,

(SELECT DFVAL.VALUE_INT FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'altura' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS ALTURA,

(SELECT DFVAL.VALUE_STR FROM RLM_GED.RLM_EXPEDIENTE_REGISTRO REGEE
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.NUMERO = SUBSTR(REGEE.CODIGOEE,9,8)
INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID = EE.ID
INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOC.ID = EEDOCS.ID_DOCUMENTO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO GEDO ON GEDO.NUMERO = EEDOC.NUMERO_SADE
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO GEDOTIPO ON GEDOTIPO.ID = GEDO.TIPO
INNER JOIN GEDO_GED.GEDO_DOCUMENTO_SOLICITUD SOLICITUD ON SOLICITUD.NUMERO_SADE = GEDO.NUMERO
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVAL ON DFVAL.ID_TRANSACTION = SOLICITUD.ID_TRANSACCION
INNER JOIN GEDO_GED.DF_FORM_COMPONENT DFCOMP ON DFCOMP.ID = DFVAL.ID_FORM_COMPONENT
WHERE DFCOMP.NAME = 'codigo_postal' AND
REGEE.FK_REGISTRO = REG.ID FETCH FIRST 1 ROWS ONLY) AS CODIGO_POSTAL,

(SELECT CASE TIPO.ACRONIMO 
    WHEN 'ELSFT' THEN 'DPPJ'
    WHEN 'ITCFD' THEN 'Escribano'
    WHEN 'FOELF' THEN 'Firma Digital' END   
FROM RLM_GED.RLM_DOC_VIN_REGISTRO_HIST RLMDOC
INNER JOIN GEDO_GED.GEDO_DOCUMENTO DOC ON DOC.NUMERO = RLMDOC.NUMERO_GEDO
INNER JOIN GEDO_GED.GEDO_TIPODOCUMENTO TIPO ON DOC.TIPO = TIPO.ID 
WHERE TIPO.ACRONIMO IN ('ITCFD','ELSFT','FOELF') AND RLMDOC.FK_REGISTRO = REG.ID
FETCH FIRST 1 ROWS ONLY) AS TIPO

FROM RLM_GED.REGISTROS REG
LEFT JOIN RLM_GED.SIS_TIPO_REGISTRO TIPO_REG ON TIPO_REG.ID_TIPO_REGISTRO = REG.TIPO_REGISTRO
LEFT JOIN RLM_GED.REGISTROS_PERSONA REG_PER ON REG_PER.REGISTRO = REG.ID
LEFT JOIN RLM_GED.REV_PERSONA REV_P ON REG_PER.REV = REV_P.ID
LEFT JOIN RLM_GED.REV_PERSONA_JURIDICA REV_PJ ON REV_PJ.REVISION_PERSONA = REV_P.ID

WHERE TIPO_REG.CODIGO = 'RLSOC0001'