SET SERVEROUTPUT ON
SET DEFINE OFF

DECLARE
    
    V_REGISTROS_MODIFICADOS NUMBER (30);
    V_NUMERO_ESPERADO       NUMBER (30);
    REG_ACT_EXCEPTION       EXCEPTION;
    
    TYPE SAS IS RECORD (
        ID NUMBER(10),
        DESCRIPCION VARCHAR2(100),
        NUMERO_EE VARCHAR(100)
        );    
    
    TYPE TABLA_SAS IS TABLE OF SAS;

    L_SAS TABLA_SAS;

BEGIN
    
    SELECT EXPEDIENTE.ID_EXTERNO ID, TRA.REFERENCIA DESCRIPCION,
    EXPEDIENTE.TIPO_DOCUMENTO||'-'||EXPEDIENTE.ANIO||'-'||TO_CHAR(EXPEDIENTE.NUMERO, 'FM00000000')||'-   -'
    ||EXPEDIENTE.CODIGO_REPARTICION_ACTUACION||'-'||EXPEDIENTE.CODIGO_REPARTICION_USUARIO AS NUMERO_EE 
    BULK COLLECT INTO L_SAS
    FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EXPEDIENTE
    LEFT JOIN TAD2_GED.TAD_TRAMITE TRA ON TRA.ID = EXPEDIENTE.ID_EXTERNO WHERE 
    TRA.NUMERO_EE IS NULL AND 
    TRA.ID_TIPO_TRAMITE NOT IN (2,1368) AND EXPEDIENTE.CODIGO_REPARTICION_USUARIO = 'DLMJYDHGP';

    V_NUMERO_ESPERADO       := L_SAS.COUNT; --CANTIDAD DE UPDATES EN LA BASE DE DATOS
    V_REGISTROS_MODIFICADOS := 0;
    DBMS_OUTPUT.PUT_LINE ('***COMIENZA SCRIPT***');
    DBMS_OUTPUT.PUT_LINE ('SE ESPERAN MODIFICAR '||V_NUMERO_ESPERADO ||' REGISTROS');

--BEGIN UPDATE
    FOR I IN 1 .. L_SAS.COUNT
    LOOP
        UPDATE TAD2_GED.TAD_TRAMITE SET NUMERO_EE = L_SAS(I).NUMERO_EE WHERE ID = L_SAS(I).ID; 
        V_REGISTROS_MODIFICADOS := V_REGISTROS_MODIFICADOS + SQL%ROWCOUNT;
    END LOOP;
--FIN UPDATE

IF (V_REGISTROS_MODIFICADOS != V_NUMERO_ESPERADO) THEN
    RAISE REG_ACT_EXCEPTION;
END IF;

COMMIT; --!!!PARA EJECUTAR PASAR A COMMIT!!!
DBMS_OUTPUT.PUT_LINE ('SE MODIFICARON '||V_REGISTROS_MODIFICADOS||' REGISTROS');
DBMS_OUTPUT.PUT_LINE ('***COMMIT REALIZADO***');

EXCEPTION
WHEN REG_ACT_EXCEPTION THEN
BEGIN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE ('SE REALIZA ROLLBACK DE TRANSACCION: ');
    DBMS_OUTPUT.PUT_LINE ('LA CANTIDAD DE REGISTROS INSERTADOS NO COINCIDE CON LA ESPERADA ' || V_REGISTROS_MODIFICADOS);
END;

WHEN OTHERS THEN
BEGIN
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE ('SE REALIZA ROLLBACK DE TRANSACCION: ');
    DBMS_OUTPUT.PUT_LINE ('    ' || SUBSTR (SQLERRM,1, 200));
END;

END;