WITH USUARIOS AS (
SELECT 
SU.NOMBRE_USUARIO AS USUARIO,
SR.CODIGO_REPARTICION AS CODIGO_REPARTICION
FROM 
TRACK_GED.SADE_SECTOR_USUARIO SU 
LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON (SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO) 
LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON (SSI.CODIGO_REPARTICION = SR.ID_REPARTICION) 
LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON (SR.MINISTERIO = SR1.ID_REPARTICION)
LEFT JOIN CO_GED.DATOS_USUARIO DU ON (DU.USUARIO = SU.NOMBRE_USUARIO)
WHERE SR1.CODIGO_REPARTICION = 'CGP' AND DU.ACEPTACION_TYC = 1
)

--ACTIVIDADES EXPEDIENTE ELECTRONICO
SELECT
    U.USUARIO,
    U.CODIGO_REPARTICION,
    HIST.TIPO_OPERACION ACTIVIDAD,
    TO_CHAR(HIST.FECHA_OPERACION, 'DD/MM/YYYY') AS FECHA_OPERACION,
	TO_CHAR(HIST.FECHA_OPERACION, 'HH24:MI:SS') AS HORA_OPERACION,
	HIST.ID AS ORDEN,
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||
        EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    TRATA.DESCRIPCION AS TRATA,
    --DESTINO 
	REGEXP_REPLACE(HIST.DESTINATARIO,'[^A-Z0-9-#-]','') AS DESTINATARIO,
	HIST.CODIGO_SECTOR_DESTINO,
	REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') AS CODIGO_REPARTICION_DESTINO,
	HIST.CODIGO_JURISDICCION_DESTINO AS CODIGO_MINISTERIO_DESTINO
FROM
    EE_GED.HISTORIALOPERACION HIST
    INNER JOIN USUARIOS U ON HIST.USUARIO = U.USUARIO
    INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
    INNER JOIN EE_GED.TRATA TRATA ON TRATA.ID = EE.ID_TRATA
WHERE
	EXTRACT(YEAR FROM HIST.FECHA_OPERACION) = 2021

UNION

SELECT
    U.USUARIO,
    U.CODIGO_REPARTICION,
    'Recepción' AS ACTIVIDAD,
    TO_CHAR(HIST.FECHA_OPERACION, 'DD/MM/YYYY') AS FECHA_OPERACION,
	TO_CHAR(HIST.FECHA_OPERACION, 'HH24:MI:SS') AS HORA_OPERACION,
	HIST.ID + 1 AS ORDEN,
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'-'||
        EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    TRATA.DESCRIPCION AS TRATA,
    --DESTINO 
	REGEXP_REPLACE(HIST.DESTINATARIO,'[^A-Z0-9-#-]','') AS DESTINATARIO,
	HIST.CODIGO_SECTOR_DESTINO,
	REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') AS CODIGO_REPARTICION_DESTINO,
	HIST.CODIGO_JURISDICCION_DESTINO AS CODIGO_MINISTERIO_DESTINO
FROM
    EE_GED.HISTORIALOPERACION HIST
    INNER JOIN USUARIOS U ON HIST.USUARIO_SELECCIONADO = U.USUARIO
    INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
    INNER JOIN EE_GED.TRATA TRATA ON TRATA.ID = EE.ID_TRATA
WHERE
    EXTRACT(YEAR FROM HIST.FECHA_OPERACION) = 2021