WITH TAREAS_PENDIENTES AS (
    SELECT PROCESSINSTANCE_, DUEDATE_ FROM GEDO_GED.JBPM4_JOB WHERE STATE_ = 'waiting')
    
SELECT
TAREAS_PENDIENTES.PROCESSINSTANCE_,
(SELECT VAR.LONG_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'reintentosCierre' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) reintentosCierre,
TAREAS_PENDIENTES.DUEDATE_,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioProductorApeNom' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioProductorApeNom,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioProductor' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioProductor,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'tipoDocumento' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) tipoDocumento,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'solicitudEnvioCorreo' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) solicitudEnvioCorreo,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioCreador' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioCreador,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'archivoTemporalFirma' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) archivoTemporalFirma,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'solicitudEnvioCorreoFail' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) solicitudEnvioCorreoFail,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'tipoDocumentoComunicable' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) tipoDocumentoComunicable,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'sistemaIniciador' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) sistemaIniciador,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'motivo' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) motivo,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioCreadorApeNom' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioCreadorApeNom,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'acronimoTipoDocumento' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) acronimoTipoDocumento,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'reparticion' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) reparticion,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'idHashTemplate' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) idHashTemplate,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'workflow_lista' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) workflow_lista,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'tarea_actual' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) tarea_actual,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioDerivadorApeNom' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioDerivadorApeNom,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'solicitudEnvioCorreoFailPF' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) solicitudEnvioCorreoFailPF,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'codigoEcosistema' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) codigoEcosistema,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuario_actual' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuario_actual,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioFirmante' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioFirmante,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'timeoutReintentosCierre' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) timeoutReintentosCierre,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'mensajeUsuario' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) mensajeUsuario,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioDerivador' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioDerivador,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'fecha_pedido_firma' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) fecha_pedido_firma,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioDerivadorTareaPF' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioDerivadorTareaPF,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'estadoTareaPF' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) estadoTareaPF,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioRevisor' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioRevisor,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioApoderador' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioApoderador,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'numeroSADE_documento1_original' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) numeroSADE_documento1_original,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'nombreTemporal_documento1' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) nombreTemporal_documento1,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioVerificador' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioVerificador,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'usuarioVerificadorOriginal' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) usuarioVerificadorOriginal,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'mensajeDestinatario' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) mensajeDestinatario,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'tareaRechazoDocumento' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) tareaRechazoDocumento,
(SELECT VAR.STRING_VALUE_ FROM GEDO_GED.JBPM4_VARIABLE VAR WHERE VAR.KEY_ = 'motivoRechazo' 
AND VAR.EXECUTION_ = TAREAS_PENDIENTES.PROCESSINSTANCE_) motivoRechazo


FROM TAREAS_PENDIENTES ORDER BY TAREAS_PENDIENTES.DUEDATE_ DESC;
