WITH REPARTICIONES_INICIADORAS AS
(
SELECT
    FK_TIPO_REGISTRO,
    LISTAGG(REPARTICION, ',') WITHIN GROUP (ORDER BY REPARTICION) AS REPARTICIONES_INICIADORAS
FROM RLM_GED.RLM_REPARTICION_INICIADORA
GROUP BY FK_TIPO_REGISTRO
)
, REPARTICIONES_CONSULTA AS
(
SELECT
    FK_TIPO_REGISTRO,
    LISTAGG(REPARTICION, ',') WITHIN GROUP (ORDER BY REPARTICION) AS REPARTICIONES_CONSULTA
FROM RLM_GED.RLM_REPARTICION_CONSULTA
GROUP BY FK_TIPO_REGISTRO
)
, REPARTICIONES_HABILITADAS AS
(
SELECT
    FK_TIPO_REGISTRO,
    LISTAGG(REPARTICION, ',') WITHIN GROUP (ORDER BY REPARTICION) AS REPARTICIONES_HABILITADAS
FROM RLM_GED.RLM_REPARTICION_HABILITADA
GROUP BY FK_TIPO_REGISTRO
)

SELECT
TR.ID_TIPO_REGISTRO,
TR.CODIGO,
TR.DESCRIPCION,
TR.ORGANO_RECTOR,
RI.REPARTICIONES_INICIADORAS,
RC.REPARTICIONES_CONSULTA,
RH.REPARTICIONES_HABILITADAS

FROM RLM_GED.SIS_TIPO_REGISTRO TR
LEFT JOIN REPARTICIONES_INICIADORAS RI ON TR.ID_TIPO_REGISTRO = RI.FK_TIPO_REGISTRO
LEFT JOIN REPARTICIONES_CONSULTA RC ON TR.ID_TIPO_REGISTRO = RC.FK_TIPO_REGISTRO
LEFT JOIN REPARTICIONES_HABILITADAS RH ON TR.ID_TIPO_REGISTRO = RH.FK_TIPO_REGISTRO

ORDER BY TR.ID_TIPO_REGISTRO;