SELECT
    TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION,
    TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
    EE.SISTEMA_CREADOR AS SISTEMA_CREADOR,
    EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    EE.CODIGO_REPARTICION_USUARIO AS COD_REP_CARATULACION,
    REP_CARATULA.NOMBRE_REPARTICION as NOMBRE_REP_CARATULACION,
    MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION,
    MIN_CARATULA.NOMBRE_rEPARTICION AS NOMBRE_ORGANISMO_CARATULACION,
    TRATAS.CODIGO_TRATA AS CODIGO_TRATA_CARATULACION,
    TRATAS.DESCRIPCION AS DESCRIPCION_TRATA,
    
    (
    SELECT 'SI' FROM DUAL
    WHERE EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    UNION
    SELECT 'NO' FROM DUAL
    WHERE NOT EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    ) AS PERMISO
    
FROM 
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    INNER JOIN EE_GED.TRATA TRATAS ON EE.ID_TRATA = TRATAS.ID
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

WHERE    
    EE.ANIO = 2020
    AND EE.CODIGO_REPARTICION_USUARIO <> 'TESTGDEBA';
------------------------------------------------------------------------------

SELECT * FROM (
SELECT
    TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION,
    TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
    EE.SISTEMA_CREADOR AS SISTEMA_CREADOR,
    EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    EE.CODIGO_REPARTICION_USUARIO AS COD_REP_CARATULACION,
    REP_CARATULA.NOMBRE_REPARTICION as NOMBRE_REP_CARATULACION,
    MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION,
    MIN_CARATULA.NOMBRE_rEPARTICION AS NOMBRE_ORGANISMO_CARATULACION,
    TRATAS.CODIGO_TRATA AS CODIGO_TRATA_CARATULACION,
    TRATAS.DESCRIPCION AS DESCRIPCION_TRATA,
    
    (
    SELECT 'SI' FROM DUAL
    WHERE EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    UNION
    SELECT 'NO' FROM DUAL
    WHERE NOT EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    ) AS PERMISO
    
FROM 
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    INNER JOIN EE_GED.TRATA TRATAS ON EE.ID_TRATA = TRATAS.ID
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

WHERE    
    EE.ANIO = 2020
    AND EE.CODIGO_REPARTICION_USUARIO <> 'TESTGDEBA') TEMP
    
WHERE TEMP.PERMISO = 'NO';

------------------------------------------------------------------------------

SELECT COUNT(*) AS CARATULADOS_CON_BUG FROM
(
SELECT
        (
    SELECT 'SI' FROM DUAL
    WHERE EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    UNION
    SELECT 'NO' FROM DUAL
    WHERE NOT EXISTS (
    SELECT HABILITACION FROM EE_GED.TRATA_REPARTICION
        WHERE CODIGOREPARTICION IN (EE.CODIGO_REPARTICION_USUARIO, '--TODAS--') AND ID_TRATA = EE.ID_TRATA AND HABILITACION = 1
        )
    ) AS PERMISO
       
FROM 
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    INNER JOIN EE_GED.TRATA TRATAS ON EE.ID_TRATA = TRATAS.ID

WHERE    
    EE.ANIO = 2020
    AND EE.CODIGO_REPARTICION_USUARIO <> 'TESTGDEBA'
) TEMP

WHERE TEMP.PERMISO = 'NO';