WITH CANTIDAD_INTENTOS AS (
SELECT 
ID_NOTIFICACION, 
COUNT(*) AS CANTIDAD_INTENTOS 
FROM EE_GED.EE_NOTIFICACION_RECIBIDA
WHERE ID_NOTIFICACION IN (SELECT ID_NOTIFICACION
FROM EE_GED.EE_NOTIFICACION_RECIBIDA WHERE FECHA_CREACION > TO_DATE('01/01/2023','DD/MM/YYYY'))
GROUP BY ID_NOTIFICACION
),

NOTIFICACION_INTENTOS AS (
SELECT 
NR.DOMICILIO_ELECTRONICO,
NR.ID_NOTIFICACION,
NR.ID_CAUSA,
NR.USUARIO_CARATULADOR,
NR.ESTADO_NOTIFICACION,
NR.MOTIVO AS MOTIVO_REINTENTO,
NR.ID_ORGANISMO,
TO_CHAR(NR.FECHA_ENVIO, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_ENVIO,
CI.CANTIDAD_INTENTOS
FROM EE_GED.EE_NOTIFICACION_RECIBIDA NR
INNER JOIN CANTIDAD_INTENTOS CI ON NR.ID_NOTIFICACION = CI.ID_NOTIFICACION
WHERE 
NR.ID_NOTIFICACION_RECIBIDA = (
SELECT MAX(ID_NOTIFICACION_RECIBIDA) FROM EE_GED.EE_NOTIFICACION_RECIBIDA
WHERE ID_NOTIFICACION = NR.ID_NOTIFICACION)
)

SELECT
NI.ID_NOTIFICACION,
NI.ID_CAUSA,
NI.USUARIO_CARATULADOR,
NI.ESTADO_NOTIFICACION,
NI.MOTIVO_REINTENTO,
NI.CANTIDAD_INTENTOS,
NI.FECHA_ENVIO,
NI.ID_ORGANISMO,
CASE EE.TIPO_DOCUMENTO WHEN 'EX' THEN 
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||
    '-'||EE.CODIGO_REPARTICION_USUARIO END AS NRO_EXPEDIENTE, 
EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION, 
MIN_CARATULA.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION, 
TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION, 
TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
TRATAS.CODIGO_TRATA,
TRATAS.DESCRIPCION AS DESCRIPCION_TRATA,  
EE.DESCRIPCION AS DESCRIPCION, 
SOLEX.MOTIVO, 
EE.ESTADO AS ESTADO_EXPEDIENTE

FROM NOTIFICACION_INTENTOS NI
LEFT JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID_EXTERNO = NI.ID_NOTIFICACION
LEFT JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLEX ON SOLEX.ID = EE.SOLICITUD_INICIADORA
LEFT JOIN EE_GED.TRATA TRATAS ON TRATAS.ID = EE.ID_TRATA
--Caratulacion--
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

ORDER BY ID_NOTIFICACION DESC;