SELECT
EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION,
TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
MIN_CARATULA.CODIGO_REPARTICION AS COD_MINISTERIO_CARATULACION, 
MIN_CARATULA.NOMBRE_REPARTICION AS MINISTERIO_CARATULACION, 
HIST.TIPO_OPERACION,
HIST.MOTIVO,
HIST.ORD_HIST AS ORDEN,
HIST.ESTADO,
HIST.USUARIO AS USUARIO_ORIGEN,
TO_CHAR(HIST.FECHA_OPERACION, 'DD/MM/YYYY') AS FECHA_OPERACION,
TO_CHAR(HIST.FECHA_OPERACION, 'HH24:MI:SS') AS HORA_OPERACION,
TO_CHAR(HIST.FECHA_OPERACION, 'MONTH') AS MES_OPERACION,
EE.ANIO AS AÑO_OPERACION

FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
LEFT JOIN EE_GED.HISTORIALOPERACION HIST ON EE.ID = HIST.ID_EXPEDIENTE
LEFT JOIN EE_GED.TRATA T ON EE.ID_TRATA = T.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

WHERE
HIST.USUARIO IN ('CMATURANA','DJALO','VMACLEN')
AND
TRUNC(HIST.FECHA_OPERACION) BETWEEN TO_DATE('01/08/2017','DD/MM/YYYY') AND TO_DATE('08/12/2018','DD/MM/YYYY')
ORDER BY HIST.USUARIO, HIST.ID ASC;