SELECT 
    EEDOC.NUMERO_SADE, 
    EEDOC.NOMBRE_USUARIO_GENERADOR,
    TO_CHAR(EEDOC.FECHA_CREACION, 'YYYY/MM/DD') AS "FECHA_CREACION",
    TO_CHAR(EEDOC.FECHA_CREACION, 'HH24:MM') AS "HORA_CREACION",
    LISTAGG(DFVALUE.INPUT_NAME || ' : ' || DFVALUE.VALUE_STR || DFVALUE.VALUE_INT , ' | ') WITHIN GROUP (ORDER BY DFVALUE.ID_FORM_COMPONENT) AS "VALORES_CARATULA",
    (EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || LPAD(EE.NUMERO, 8, '0') || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO ) AS EXPEDIENTE,
    EE.USUARIO_CREADOR
    
FROM 
    EE_GED.DOCUMENTO EEDOC
    JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
    JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
    JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = EEDOCS.ID
    JOIN EE_GED.TRATA EETRATA ON EETRATA.ID = EE.ID_TRATA

WHERE  
    EETRATA.CODIGO_TRATA = 'SLYT0006'
    AND eetrata.acronimo_doc_gedo = 'CVOJU'

GROUP BY 
    EEDOC.NUMERO_SADE, 
    EEDOC.NOMBRE_USUARIO_GENERADOR, 
    EEDOC.FECHA_CREACION, 
    (EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || LPAD(EE.NUMERO, 8, '0') || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO ), 
    EE.USUARIO_CREADOR;
