SELECT
T.ASSIGNEE_ AS USUARIO,
DU.APELLIDO_NOMBRE AS NOMBRE_APELLIDO,
EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
TO_CHAR(EE.FECHA_CREACION,'DD/MM/YYYY') AS FECHA_CARATULACION,
TO_CHAR(EE.FECHA_MODIFICACION,'DD/MM/YYYY') AS ULTIMA_MODIFICACION,
EE.ESTADO

FROM EE_GED.JBPM4_TASK T
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID_WORKFLOW = T.EXECUTION_ID_
LEFT JOIN CO_GED.DATOS_USUARIO DU ON DU.USUARIO = REGEXP_SUBSTR(ASSIGNEE_, '[^.]+', 1, 1)
WHERE
REGEXP_SUBSTR(ASSIGNEE_, '[^.]+', 1, 1) IN (
'SVARGAS',
'PDIAS',
'MASANCHEZ',
'MQUINTAVALLE',
'NNAVAS',
'LPELITTI',
'CDEFELITTO',
'CBARRETO',
'MVILLANUEVA',
'MBERTERRETCHE'
)

ORDER BY T.ASSIGNEE_;