WITH ID_EXPEDIENTES_SALIENTES AS (
SELECT
HIST.ID_EXPEDIENTE ID,
COALESCE(HIST.CODIGO_JURISDICCION_DESTINO,MIN.CODIGO_REPARTICION) COD_MINISTERIO_DESTINO

FROM EE_GED.HISTORIALOPERACION HIST
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
INNER JOIN TRACK_GED.SADE_REPARTICION REP ON REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') 
    = REP.CODIGO_REPARTICION
INNER JOIN TRACK_GED.SADE_REPARTICION MIN ON REP.MINISTERIO = MIN.ID_REPARTICION

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO = 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') != 'DPPMJGM' AND

TRUNC(HIST.FECHA_OPERACION) >=
    (CASE WHEN TO_CHAR(SYSDATE, 'D') = 1 THEN TRUNC(SYSDATE-3) ELSE TRUNC(SYSDATE-1) END)
    AND  TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
),

ID_EXP_SALIENTES_SIN_REP AS (
SELECT DISTINCT * FROM ID_EXPEDIENTES_SALIENTES
),

CANTIDAD_EGRESOS AS (
SELECT
SAL.ID,
SAL.COD_MINISTERIO_DESTINO,
COUNT(*) CANT_EGRESOS

FROM ID_EXP_SALIENTES_SIN_REP SAL
INNER JOIN EE_GED.HISTORIALOPERACION HIST ON HIST.ID_EXPEDIENTE = SAL.ID
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO = 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') != 'DPPMJGM' AND
TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
GROUP BY SAL.ID, SAL.COD_MINISTERIO_DESTINO
)

SELECT
TO_CHAR(SYSDATE-1,'DD/MM/YYYY') PERIODO,
COD_MINISTERIO_DESTINO,
MIN.NOMBRE_REPARTICION AS MINISTERIO_DESTINO,
T.CODIGO_TRATA,
T.DESCRIPCION AS TRATA,
NVL(SUM(CASE WHEN CANT_EGRESOS = 1 THEN 1 END),0) NUEVOS,
NVL(SUM(CASE WHEN CANT_EGRESOS > 1 THEN 1 END),0) AS CON_OBSERVACIONES

FROM CANTIDAD_EGRESOS CANT
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = CANT.ID
LEFT JOIN EE_GED.TRATA T ON EE.ID_TRATA = T.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN ON MIN.CODIGO_REPARTICION = CANT.COD_MINISTERIO_DESTINO

GROUP BY TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 
COD_MINISTERIO_DESTINO, MIN.NOMBRE_REPARTICION,T.CODIGO_TRATA,T.DESCRIPCION
ORDER BY COD_MINISTERIO_DESTINO,T.CODIGO_TRATA