WITH ID_EXPEDIENTES_SALIENTES AS (
SELECT
HIST.ID_EXPEDIENTE ID,
COALESCE(MIG.DESTINO_REPARTICION, MIN_CARATULA.CODIGO_REPARTICION) AS COD_ORGANISMO_CARATULACION

FROM EE_GED.HISTORIALOPERACION HIST
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
--caratulador--
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION
LEFT JOIN EU_GED.MIG_TAREA MIG ON MIG.ORIGEN_REPARTICION = MIN_CARATULA.CODIGO_REPARTICION AND MIG.TIPO_MIGRACION = 'MIGRACION_REPARTICION' 
        AND MIG.MODULO = 'EE'
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_MIG ON REP_MIG.CODIGO_REPARTICION = MIG.DESTINO_REPARTICION

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO = 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') != 'DPPMJGM' AND

TRUNC(HIST.FECHA_OPERACION) >=
    (CASE WHEN TO_CHAR(SYSDATE, 'D') = 1 THEN TRUNC(SYSDATE-3) ELSE TRUNC(SYSDATE-1) END)
    AND  TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
),

ID_EXP_SALIENTES_SIN_REP AS (
SELECT DISTINCT * FROM ID_EXPEDIENTES_SALIENTES
),

CANTIDAD_EGRESOS AS (
SELECT 
SAL.ID,
SAL.COD_ORGANISMO_CARATULACION,
COUNT(*) CANT_EGRESOS

FROM ID_EXP_SALIENTES_SIN_REP SAL
INNER JOIN EE_GED.HISTORIALOPERACION HIST ON HIST.ID_EXPEDIENTE = SAL.ID
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO = 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') != 'DPPMJGM' AND
TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
GROUP BY SAL.ID, SAL.COD_ORGANISMO_CARATULACION
)

SELECT
TO_CHAR(SYSDATE-1,'DD/MM/YYYY') PERIODO,
COD_ORGANISMO_CARATULACION,
MIN.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION,
T.CODIGO_TRATA,
T.DESCRIPCION AS TRATA,
NVL(SUM(CASE WHEN CANT_EGRESOS = 1 THEN 1 END),0) NUEVOS,
NVL(SUM(CASE WHEN CANT_EGRESOS > 1 THEN 1 END),0) AS CON_OBSERVACIONES

FROM CANTIDAD_EGRESOS CANT
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = CANT.ID
LEFT JOIN EE_GED.TRATA T ON EE.ID_TRATA = T.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN ON MIN.CODIGO_REPARTICION = CANT.COD_ORGANISMO_CARATULACION

GROUP BY TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 
COD_ORGANISMO_CARATULACION, MIN.NOMBRE_REPARTICION, T.CODIGO_TRATA, T.DESCRIPCION
ORDER BY COD_ORGANISMO_CARATULACION,T.CODIGO_TRATA