SELECT  
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE, 
    EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
    REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
    MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION, 
    MIN_CARATULA.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION, 
	TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION, 
	TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
    TRATAS.CODIGO_TRATA,
	TRATAS.DESCRIPCION AS TRATA,  
    EE.DESCRIPCION AS DESCRIPCION, 
    SOLEX.USUARIO_CREACION AS USUARIO_SOLICITANTE,
    SRC.CODIGO_REPARTICION AS COD_REPARTICION_SOLICITANTE,
    SRC.NOMBRE_REPARTICION AS NOMBRE_REPARTICION_SOLICITANTE,
    SOLEX.MOTIVO, 
    EE.ESTADO AS ESTADO_EXPEDIENTE,
    REGEXP_SUBSTR(T.ASSIGNEE_, '[^.]+', 1, 1) AS USUARIO_ASIGNADO,
	DU.APELLIDO_NOMBRE AS NOMBRE_APELLIDO,
    COALESCE(REPA.CODIGO_REPARTICION,SR.CODIGO_REPARTICION) AS COD_REPARTICION_ACTUAL,
    REPFIN.NOMBRE_REPARTICION AS REPARTICION_ACTUAL,
    COALESCE(MINISTERIO.CODIGO_REPARTICION,SR1.CODIGO_REPARTICION) AS COD_ORGANISMO_ACTUAL,  
    MINFIN.NOMBRE_REPARTICION AS ORGANISMO_ACTUAL,
    EE.USUARIO_MODIFICACION,
	TO_CHAR(EE.FECHA_MODIFICACION, 'DD/MM/YYYY') AS FECHA_ULTIMA_MODIFICACION, 
	TO_CHAR(EE.FECHA_MODIFICACION, 'HH24:MI:SS') AS HORA_ULTIMA_MODIFICACION,
	ROUND(SYSDATE - EE.FECHA_CREACION) AS DIAS_ABIERTO
    
FROM 
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    LEFT JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLEX ON SOLEX.ID = EE.SOLICITUD_INICIADORA
    LEFT JOIN EE_GED.TRATA TRATAS ON TRATAS.ID = EE.ID_TRATA
    LEFT JOIN EE_GED.JBPM4_TASK T ON T.EXECUTION_ID_ = EE.ID_WORKFLOW
    LEFT JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_
    
    --Caratulación--
    LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION
    
    --Es tramitación conjunta--
    LEFT JOIN TRACK_GED.SADE_REPARTICION REPA ON REGEXP_SUBSTR(P.GROUPID_, '[^-]+', 1, 1) = REPA.CODIGO_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MINISTERIO ON MINISTERIO.ID_REPARTICION = REPA.MINISTERIO
    
    --Es tramitación simple--
    LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON T.ASSIGNEE_ = SU.NOMBRE_USUARIO
        AND SU.ID_SECTOR_USUARIO = (
            SELECT MAX(Z.ID_SECTOR_USUARIO) FROM TRACK_GED.SADE_SECTOR_USUARIO Z 
            WHERE Z.NOMBRE_USUARIO = T.ASSIGNEE_
        )
	LEFT JOIN CO_GED.DATOS_USUARIO DU ON DU.USUARIO = SU.NOMBRE_USUARIO
	LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON SSI.CODIGO_REPARTICION = SR.ID_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR1.ID_REPARTICION = SR.MINISTERIO

    LEFT JOIN TRACK_GED.SADE_REPARTICION REPFIN ON REPFIN.CODIGO_REPARTICION = COALESCE(REPA.CODIGO_REPARTICION,SR.CODIGO_REPARTICION)
    LEFT JOIN TRACK_GED.SADE_REPARTICION MINFIN ON MINFIN.CODIGO_REPARTICION = COALESCE(MINISTERIO.CODIGO_REPARTICION,SR1.CODIGO_REPARTICION)

    --usuario solicitante--
    LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SUC ON SOLEX.USUARIO_CREACION = SUC.NOMBRE_USUARIO
        AND SUC.ID_SECTOR_USUARIO = (
            SELECT MAX(ZC.ID_SECTOR_USUARIO) FROM TRACK_GED.SADE_SECTOR_USUARIO ZC 
            WHERE ZC.NOMBRE_USUARIO = SOLEX.USUARIO_CREACION
        )
	LEFT JOIN CO_GED.DATOS_USUARIO DUC ON DUC.USUARIO = SUC.NOMBRE_USUARIO
	LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSIC ON SUC.ID_SECTOR_INTERNO = SSIC.ID_SECTOR_INTERNO
    LEFT JOIN TRACK_GED.SADE_REPARTICION SRC ON SSIC.CODIGO_REPARTICION = SRC.ID_REPARTICION

WHERE
    MIN_CARATULA.CODIGO_REPARTICION = 'IVMIYSPGP'
    AND SRC.CODIGO_REPARTICION = 'DPTDPIV'