SELECT
EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
EE.FECHA_CREACION AS FECHA_CARATULACION, 
H.TIPO_OPERACION,
H.FECHA_OPERACION,
H.MOTIVO,
H.USUARIO AS USUARIO_ORIGEN,
H.REPARTICION_USUARIO AS COD_REPARTICION_ORIGEN,
H.DESCRIPCION_REPARTICION_ORIGEN AS NOMBRE_REPARTICION_ORIGEN,
H.CODIGO_JURISDICCION_ORIGEN AS COD_MINISTERIO_ORIGEN,
H.DESTINATARIO AS USUARIO_REPA_DESTINO,
H.CODIGO_REPARTICION_DESTINO AS COD_REPARTICION_DESTINO,
H.DESCRIPCION_REPARTICION_DESTIN AS NOMBRE_REPARTICION_DESTINO,
H.CODIGO_JURISDICCION_DESTINO AS COD_MINISTERIO_DESTINO

FROM
EE_GED.HISTORIALOPERACION H
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = H.ID_EXPEDIENTE

WHERE 
H.FECHA_OPERACION >= TO_DATE('07/08/2020', 'DD/MM/YYYY')
AND H.TIPO_OPERACION = 'Pase'
AND H.CODIGO_JURISDICCION_ORIGEN = 'IVMIYSPGP'
AND H.CODIGO_JURISDICCION_DESTINO = 'CGP'

ORDER BY H.FECHA_OPERACION ASC
;