SELECT
    COUNT(*)
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
INNER JOIN TRACK_GED.SADE_REPARTICION R ON R.CODIGO_REPARTICION = EE.CODIGO_REPARTICION_USUARIO
INNER JOIN TRACK_GED.SADE_REPARTICION R1 ON R1.ID_REPARTICION = R.MINISTERIO
WHERE R1.CODIGO_REPARTICION = 'IPS';