SELECT  
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE, 
    EE.USUARIO_CREADOR AS USUARIO_CARATULADOR,
    EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
    REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
    MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION, 
    MIN_CARATULA.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION, 
	EE.FECHA_CREACION AS FECHA_CARATULACION,
    TRATAS.CODIGO_TRATA,
	TRATAS.DESCRIPCION AS TRATA,  
    EE.DESCRIPCION AS DESCRIPCION, 
    SOLEX.MOTIVO, 
    EE.ESTADO AS ESTADO_EXPEDIENTE,
    NVL(REGEXP_SUBSTR(T.ASSIGNEE_, '[^.]+', 1, 2),'simple') AS TIPO_TRAMITACION,
    REGEXP_SUBSTR(T.ASSIGNEE_, '[^.]+', 1, 1) AS USUARIO_ASIGNADO,
	DU.APELLIDO_NOMBRE AS NOMBRE_APELLIDO,
    COALESCE(REGEXP_SUBSTR(REGEXP_SUBSTR(P.GROUPID_, '[^-]+', 1, 2),'[^.]+', 1, 1),SSI.CODIGO_SECTOR_INTERNO) AS SECTOR_ACTUAL,
    REPFIN.CODIGO_REPARTICION AS COD_REPARTICION_ACTUAL,
    REPFIN.NOMBRE_REPARTICION AS REPARTICION_ACTUAL,
    MINFIN.CODIGO_REPARTICION AS COD_ORGANISMO_ACTUAL,  
    MINFIN.NOMBRE_REPARTICION AS ORGANISMO_ACTUAL,
    EE.USUARIO_MODIFICACION,
	EE.FECHA_MODIFICACION AS FECHA_ULTIMA_MODIFICACION, 
	ROUND(SYSDATE - EE.FECHA_CREACION) AS DIAS_ABIERTO,

(SELECT DFVALUE.VALUE_STR FROM
EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
AND DFVALUE.INPUT_NAME = 'idorganismo' WHERE EEDOCS.ID = EE.ID AND EEDOCS.POSICION = 1) AS ID_ORGANISMO,

(SELECT DFVALUE.VALUE_STR FROM
EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
AND DFVALUE.INPUT_NAME = 'organismoorigen' WHERE EEDOCS.ID = EE.ID AND EEDOCS.POSICION = 1) AS ORGANISMO_ORIGEN,

(SELECT DFVALUE.VALUE_STR FROM
EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
AND DFVALUE.INPUT_NAME = 'idcausanumero' WHERE EEDOCS.ID = EE.ID AND EEDOCS.POSICION = 1) AS ID_CAUSA_NUMERO,

(SELECT DFVALUE.VALUE_STR FROM
EE_GED.EE_EXPEDIENTE_DOCUMENTOS EEDOCS INNER JOIN EE_GED.DOCUMENTO EEDOC ON EEDOCS.ID_DOCUMENTO = EEDOC.ID
INNER JOIN GEDO_GED.DF_FORM_COMP_VALUE DFVALUE ON DFVALUE.ID_TRANSACTION = EEDOC.ID_TRANSACCION_FC
AND DFVALUE.INPUT_NAME = 'idnotificacion' WHERE EEDOCS.ID = EE.ID AND EEDOCS.POSICION = 1) AS ID_NOTIFICACION

    
FROM 
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    LEFT JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLEX ON SOLEX.ID = EE.SOLICITUD_INICIADORA
    LEFT JOIN EE_GED.TRATA TRATAS ON TRATAS.ID = EE.ID_TRATA
    LEFT JOIN EE_GED.JBPM4_TASK T ON T.EXECUTION_ID_ = EE.ID_WORKFLOW
    LEFT JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_
    
    --Caratulacion--
    LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION
        
    --Esta asignado a usuario--
    LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON REGEXP_SUBSTR(T.ASSIGNEE_, '[^.]+', 1, 1) = SU.NOMBRE_USUARIO
        AND SU.ID_SECTOR_USUARIO = (
            SELECT MAX(Z.ID_SECTOR_USUARIO) FROM TRACK_GED.SADE_SECTOR_USUARIO Z 
            WHERE Z.NOMBRE_USUARIO = REGEXP_SUBSTR(T.ASSIGNEE_, '[^.]+', 1, 1)
        )
	LEFT JOIN CO_GED.DATOS_USUARIO DU ON DU.USUARIO = SU.NOMBRE_USUARIO
	LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR ON SSI.CODIGO_REPARTICION = SR.ID_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR1.ID_REPARTICION = SR.MINISTERIO

    --Sin asignar a usuario--
    LEFT JOIN TRACK_GED.SADE_REPARTICION REPA ON REGEXP_SUBSTR(P.GROUPID_, '[^-]+', 1, 1) = REPA.CODIGO_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MINISTERIO ON MINISTERIO.ID_REPARTICION = REPA.MINISTERIO

    --Reparticion/Ministerio actual
    LEFT JOIN TRACK_GED.SADE_REPARTICION REPFIN ON REPFIN.CODIGO_REPARTICION = COALESCE(SR.CODIGO_REPARTICION, REPA.CODIGO_REPARTICION)
    LEFT JOIN TRACK_GED.SADE_REPARTICION MINFIN ON MINFIN.CODIGO_REPARTICION = COALESCE(SR1.CODIGO_REPARTICION, MINISTERIO.CODIGO_REPARTICION)

WHERE
    TRATAS.CODIGO_TRATA = 'LEG0020' AND EE.CODIGO_REPARTICION_USUARIO != 'TESTGDEBA'

ORDER BY EE.FECHA_CREACION DESC