SELECT
T.DESCRIPCION AS TRATA,
EE.TIPO_DOCUMENTO||'-'|| EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION,
HIST.MOTIVO,
HIST.ORD_HIST AS ORDEN,
TO_CHAR(HIST.FECHA_OPERACION, 'DD/MM/YYYY') AS FECHA_OPERACION,
HIST.USUARIO AS USUARIO_ORIGEN,
HIST.DESCRIPCION_REPARTICION_ORIGEN,
REGEXP_REPLACE(HIST.DESTINATARIO,'[^A-Z0-9-#-]','') AS DESTINATARIO,
HIST.DESCRIPCION_REPARTICION_DESTIN AS DESC_REPARTICION_DESTINO,
HIST.DESCRIPCION_SECTOR_DESTINO AS DESC_SECTOR_DESTINO,
MIN_DESTINO.NOMBRE_REPARTICION AS DESC_MINISTERIO_DESTINO,
COALESCE(
(SELECT REGEXP_REPLACE((
TRUNC((H2.FECHA_OPERACION - HIST.FECHA_OPERACION)) || ' DIAS ' ||
TRUNC(MOD((H2.FECHA_OPERACION - HIST.FECHA_OPERACION) * 24, 24)) || ' HS ' ||
TRUNC(MOD((H2.FECHA_OPERACION - HIST.FECHA_OPERACION) * 24 * 60, 60)) || ' MIN'
), '[^A-Z0-9- ]', '')
FROM EE_GED.HISTORIALOPERACION H2
WHERE H2.ID_EXPEDIENTE = HIST.ID_EXPEDIENTE AND H2.ORD_HIST = HIST.ORD_HIST -1) 
,
'0 DIAS 0 HS 0 MIN'
) TIEMPO_ENTRE_OPERACIONES


FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
LEFT JOIN EE_GED.HISTORIALOPERACION HIST ON EE.ID = HIST.ID_EXPEDIENTE
LEFT JOIN EE_GED.TRATA T ON EE.ID_TRATA = T.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_ORIGEN ON MIN_ORIGEN.CODIGO_REPARTICION = HIST.CODIGO_JURISDICCION_ORIGEN
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_DESTINO ON MIN_DESTINO.CODIGO_REPARTICION = HIST.CODIGO_JURISDICCION_DESTINO
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

WHERE 
EXTRACT(YEAR FROM HIST.FECHA_OPERACION) >= 2020 AND
HIST.TIPO_OPERACION = 'Pase' AND
T.CODIGO_TRATA IN ('PER0022','PER0085') AND
EE.ESTADO = 'Guarda Temporal' AND
EE.CODIGO_REPARTICION_USUARIO IN ('DMGESYAMJGM','DSTAMJGM')

ORDER BY HIST.EXPEDIENTE, HIST.ORD_HIST ASC;