SELECT 
EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '- -' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
EE.FECHA_CREACION,
EE.USUARIO_MODIFICACION,
EE.FECHA_MODIFICACION,
TRATA.CODIGO_TRATA,
TRATA.DESCRIPCION AS TRATA,
EE.ESTADO,
SOLICITANTE.APELLIDO_SOLICITANTE,
SOLICITANTE.NOMBRE_SOLICITANTE,
SOLICITANTE.CUIT_CUIL,
SOLICITANTE.EMAIL,
SOLICITUD.MOTIVO,
REP_CARATULA.CODIGO_REPARTICION AS COD_REP_CAR, 
REP_CARATULA.NOMBRE_REPARTICION AS NOMBRE_REPARTICION,
MIN_CARATULA.CODIGO_REPARTICION AS COD_JURISDICCION, 
MIN_CARATULA.NOMBRE_REPARTICION AS NOMBRE_JURISDICCION

FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
LEFT JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLICITUD ON SOLICITUD.ID = EE.SOLICITUD_INICIADORA
LEFT JOIN EE_GED.SOLICITANTE SOLICITANTE ON SOLICITANTE.ID_SOLICITANTE = SOLICITUD.SOLICITANTE
LEFT JOIN EE_GED.TRATA TRATA ON TRATA.ID = EE.ID_TRATA
LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION
WHERE EE.SISTEMA_CREADOR IN ('ws_gdeba_prod_dpsitmjgm_md','ws_dsi_api_mesa_digital')
AND MIN_CARATULA.CODIGO_REPARTICION = 'DGCYE'
ORDER BY EE.FECHA_CREACION DESC