SELECT
    EA2.ID_CODIGO_CARATULA AS ID_EXPEDIENTE_ASOCIADO,
    EA1.POSICION,
    EA2.FECHA_ASOCIACION,
    EA2.TIPO_DOCUMENTO||'-'||EA2.ANIO||'-'||EA2.NUMERO ||'- -GDEBA-'||EA2.CODIGO_REPARTICION_USUARIO AS EXPEDIENTE_ASOCIADO,
    COUNT(*) CANTIDAD_DOCUMENTOS,
    EEA.ID_TRATA,
    EEA.ID_WORKFLOW,
    EEA.ESTADO,
    EEA.SISTEMA_CREADOR,
    EEA.SISTEMA_APODERADO,
    T.ASSIGNEE_
    
    
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
LEFT JOIN EE_GED.EE_EXPEDIENTE_ASOCIADO EA1 ON EE.ID = EA1.ID
LEFT JOIN EE_GED.EXPEDIENTEASOCIADO EA2 ON EA1.ID_EXPEDIENTEASOCIADO = EA2.ID
LEFT JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS ED ON EA2.ID = ED.ID
LEFT JOIN EE_GED.DOCUMENTO D ON ED.ID_DOCUMENTO = D.ID

LEFT JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EEA ON EEA.ID = EA2.ID_CODIGO_CARATULA
LEFT JOIN EE_GED.JBPM4_TASK T ON T.EXECUTION_ID_ = EEA.ID_WORKFLOW
LEFT JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_

WHERE 
--POR NRO EXPEDIENTE MADRE
EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -GDEBA-'||EE.CODIGO_REPARTICION_USUARIO = 'EX-2019-15837994- -GDEBA-HZGADIGIMSALGP'
AND EE.ES_CABECERA_TC = 1 AND EA2.DEFINITIVO = 1

GROUP BY
EA2.ID_CODIGO_CARATULA,
EA2.TIPO_DOCUMENTO||'-'||EA2.ANIO||'-'||EA2.NUMERO ||'- -GDEBA-'||EA2.CODIGO_REPARTICION_USUARIO,
EA1.POSICION,
EA2.FECHA_ASOCIACION,
EEA.ID_TRATA,
EEA.ID_WORKFLOW,
EEA.ESTADO,
EEA.SISTEMA_CREADOR,
EEA.SISTEMA_APODERADO,
T.ASSIGNEE_

ORDER BY EA1.POSICION

;