SELECT *
FROM EE_GED.HISTORIALOPERACION H
WHERE ID = (SELECT MAX (ho.id)
FROM EE_GED.HISTORIALOPERACION ho
WHERE ho.ID_EXPEDIENTE = (SELECT ee.id
FROM EE_GED.EE_EXPEDIENTE_ELECTRONICO ee
WHERE ee.NUMERO = 372458 AND ee.anio = 2021
AND ee.ECOSISTEMA_CREADOR = 'GDEBA'));