WITH AUX AS (
SELECT 
    ID_NOTIFICACION, 
    COUNT(*) AS CANTIDAD_INTENTOS 
FROM EE_GED.EE_NOTIFICACION_RECIBIDA
WHERE FECHA_CREACION > TO_DATE('01/01/2023','DD/MM/YYYY')
GROUP BY ID_NOTIFICACION
),

NOTIF_INTENTOS AS (
SELECT DISTINCT 
NR.ID_NOTIFICACION,
NR.ID_CAUSA,
AUX.CANTIDAD_INTENTOS
FROM EE_GED.EE_NOTIFICACION_RECIBIDA NR
INNER JOIN AUX ON AUX.ID_NOTIFICACION = NR.ID_NOTIFICACION
)

SELECT
NI.*,
DECODE(EE.TIPO_DOCUMENTO,'EX',1,0) AS CARATULADO,
CASE EE.TIPO_DOCUMENTO WHEN 'EX' THEN
EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION
    ||'-'||EE.CODIGO_REPARTICION_USUARIO END AS NRO_EXPEDIENTE
FROM NOTIF_INTENTOS NI
LEFT JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON NI.ID_NOTIFICACION = EE.ID_EXTERNO

ORDER BY ID_NOTIFICACION DESC;