WITH ID_EXPEDIENTES_ENTRANTES AS (
SELECT
HIST.ID_EXPEDIENTE ID,
COALESCE(HIST.CODIGO_JURISDICCION_ORIGEN,MIN.CODIGO_REPARTICION) AS COD_ORGANISMO_ORIGEN

FROM EE_GED.HISTORIALOPERACION HIST
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE
INNER JOIN TRACK_GED.SADE_REPARTICION REP ON HIST.REPARTICION_USUARIO = REP.CODIGO_REPARTICION
INNER JOIN TRACK_GED.SADE_REPARTICION MIN ON REP.MINISTERIO = MIN.ID_REPARTICION

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO != 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') = 'DPPMJGM' AND

TRUNC(HIST.FECHA_OPERACION) >=
    (CASE WHEN TO_CHAR(SYSDATE, 'D') = 1 THEN TRUNC(SYSDATE-3) ELSE TRUNC(SYSDATE-1) END)
    AND  TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
),

ID_EXP_ENTRANTES_SIN_REP AS (
SELECT DISTINCT * FROM ID_EXPEDIENTES_ENTRANTES
),

CANTIDAD_INGRESOS AS (
SELECT 
ENT.ID,
ENT.COD_ORGANISMO_ORIGEN,
COUNT(*) CANT_INGRESOS

FROM ID_EXP_ENTRANTES_SIN_REP ENT
INNER JOIN EE_GED.HISTORIALOPERACION HIST ON HIST.ID_EXPEDIENTE = ENT.ID
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIST.ID_EXPEDIENTE

WHERE
HIST.TIPO_OPERACION = 'Pase' AND
HIST.REPARTICION_USUARIO != 'DPPMJGM' AND
REGEXP_REPLACE(HIST.CODIGO_REPARTICION_DESTINO,'[^A-Z0-9-#-]','') = 'DPPMJGM' AND
TRUNC(HIST.FECHA_OPERACION) <= TRUNC(SYSDATE-1)
GROUP BY ENT.ID, ENT.COD_ORGANISMO_ORIGEN
)

SELECT
TO_CHAR(SYSDATE-1,'DD/MM/YYYY') PERIODO,
COD_ORGANISMO_ORIGEN,
MIN.NOMBRE_REPARTICION AS ORGANISMO_ORIGEN,
T.CODIGO_TRATA,
T.DESCRIPCION AS TRATA,
NVL(SUM(CASE WHEN CANT_INGRESOS = 1 THEN 1 END),0) NUEVOS,
NVL(SUM(CASE WHEN CANT_INGRESOS > 1 THEN 1 END),0) AS CON_OBSERVACIONES

FROM CANTIDAD_INGRESOS CANT
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = CANT.ID
LEFT JOIN EE_GED.TRATA T ON EE.ID_TRATA = T.ID
LEFT JOIN TRACK_GED.SADE_REPARTICION MIN ON MIN.CODIGO_REPARTICION = CANT.COD_ORGANISMO_ORIGEN

GROUP BY TO_CHAR(SYSDATE-1,'DD/MM/YYYY'), 
COD_ORGANISMO_ORIGEN, MIN.NOMBRE_REPARTICION, T.CODIGO_TRATA, T.DESCRIPCION
ORDER BY COD_ORGANISMO_ORIGEN,T.CODIGO_TRATA