SELECT
    EE.ID ID_EXP,
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'-'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
    COUNT(*) AS CANTIDAD_DOCUMENTOS,
    ROUND(SUM(GD.PESO)/1024/1024,2) AS PESO_TOTAL_MB 

FROM
    EE_GED.EE_EXPEDIENTE_ELECTRONICO EE
    INNER JOIN EE_GED.EE_EXPEDIENTE_DOCUMENTOS ED ON EE.ID = ED.ID
    INNER JOIN EE_GED.DOCUMENTO D ON ED.ID_DOCUMENTO = D.ID
    INNER JOIN GEDO_GED.GEDO_DOCUMENTO GD ON D.NUMERO_SADE = GD.NUMERO

WHERE
    EE.ID = 1569742

GROUP BY 
EE.ID,
EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'-'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO
;