SELECT  
	TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION, 
	TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION, 
	EE.SISTEMA_CREADOR AS SISTEMA_CREADOR,
	EE.TIPO_DOCUMENTO || '-' || EE.ANIO || '-' || EE.NUMERO || '-' || EE.CODIGO_REPARTICION_ACTUACION || '-' || EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE,
	EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
	REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
	MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION,
	MIN_CARATULA.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION, 
	TRATAS.CODIGO_TRATA AS CODIGO_TRATA,
	TRATAS.DESCRIPCION AS TRATA,  
	EE.DESCRIPCION AS DESCRIPCION, 
	SOLEX.MOTIVO, 
	EE.ESTADO AS ESTADO_EXPEDIENTE, 
	SUBSTR(P.GROUPID_, - INSTR(REVERSE(P.GROUPID_), '-') + 1) AS SECTOR_ACTUAL, 
	T.ASSIGNEE_ AS USUARIO_ASIGNADO,
 
	(CASE WHEN REPA.CODIGO_REPARTICION IS NOT NULL THEN REPA.CODIGO_REPARTICION
        ELSE SR.CODIGO_REPARTICION
		END) COD_REPARTICION_ACTUAL,
		
	REPFIN.NOMBRE_REPARTICION AS REPARTICION_ACTUAL,
 
	(CASE WHEN MINISTERIO.CODIGO_REPARTICION IS NOT NULL  THEN MINISTERIO.CODIGO_REPARTICION
		ELSE SR1.CODIGO_REPARTICION
		END) COD_ORGANISMO_ACTUAL,
   
	MINFIN.NOMBRE_REPARTICION AS ORGANISMO_ACTUAL,
	EE.USUARIO_MODIFICACION,
	TO_CHAR(EE.FECHA_MODIFICACION, 'DD/MM/YYYY') AS FECHA_ULTIMA_MODIFICACION, 
	TO_CHAR(EE.FECHA_MODIFICACION, 'HH24:MM:SS') AS HORA_ULTIMA_MODIFICACION, 
	
	ROUND(TEMP.DIAS_ABIERTO) DIAS_ABIERTO 
	
FROM 
	(SELECT ID_EXPEDIENTE, EE.ID_TRATA, SYSDATE - MIN(FECHA_OPERACION) DIAS_ABIERTO --, MAX(FECHA_OPERACION), MIN(FECHA_OPERACION)
	FROM EE_GED.HISTORIALOPERACION HIS
	RIGHT JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = HIS.ID_EXPEDIENTE --AND EE.ID_TRATA IN ()
	WHERE HIS.ID_EXPEDIENTE IS NOT NULL 
	GROUP BY ID_EXPEDIENTE, EE.ID_TRATA) TEMP
 
	LEFT JOIN EE_GED.TRATA ET ON ET.ID = TEMP.ID_TRATA
	LEFT JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID = TEMP.ID_EXPEDIENTE AND EE.CODIGO_REPARTICION_USUARIO <> 'TESTGDEBA'
	LEFT OUTER JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLEX ON SOLEX.ID = EE.SOLICITUD_INICIADORA 
	LEFT OUTER JOIN EE_GED.TRATA TRATAS ON TRATAS.ID = EE.ID_TRATA 
	LEFT OUTER JOIN EE_GED.JBPM4_TASK T ON T.EXECUTION_ID_ = EE.ID_WORKFLOW 
	LEFT OUTER JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_ 
	LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
	LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION
	LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION REPA ON (SUBSTR(P.GROUPID_, 1, INSTR(P.GROUPID_, '-')-1) = REPA.CODIGO_REPARTICION)  
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION MINISTERIO ON MINISTERIO.ID_REPARTICION = REPA.MINISTERIO
	LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_USUARIO SU ON T.ASSIGNEE_= SU.NOMBRE_USUARIO
       AND SU.ID_SECTOR_USUARIO = 
		(SELECT MAX(Z.ID_SECTOR_USUARIO) 
			FROM TRACK_GED.SADE_SECTOR_USUARIO Z 
			WHERE Z.NOMBRE_USUARIO = T.ASSIGNEE_)

	LEFT OUTER JOIN TRACK_GED.SADE_SECTOR_INTERNO SSI ON SU.ID_SECTOR_INTERNO = SSI.ID_SECTOR_INTERNO  
	LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR ON SSI.CODIGO_REPARTICION = SR.ID_REPARTICION 
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION SR1 ON SR1.ID_REPARTICION = SR.MINISTERIO
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION REPFIN ON REPFIN.CODIGO_REPARTICION = 
        CASE
			WHEN REPA.CODIGO_REPARTICION IS NOT NULL THEN REPA.CODIGO_REPARTICION
			ELSE SR.CODIGO_REPARTICION
        END
         
    LEFT OUTER JOIN TRACK_GED.SADE_REPARTICION MINFIN ON MINFIN.CODIGO_REPARTICION = 
		CASE
			WHEN MINISTERIO.CODIGO_REPARTICION IS NOT NULL  THEN MINISTERIO.CODIGO_REPARTICION
			ELSE SR1.CODIGO_REPARTICION
		END
            
WHERE
	MIN_CARATULA.CODIGO_REPARTICION IN ('MDCGP','MDSGP');