WITH INFO AS (
SELECT
REGEXP_SUBSTR(P.GROUPID_, '[^.]+', 1, 1) AS REPARTICION_SECTOR,
COUNT(*) AS CANTIDAD

FROM EE_GED.JBPM4_TASK T
INNER JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_
GROUP BY REGEXP_SUBSTR(P.GROUPID_, '[^.]+', 1, 1)
--HAVING COUNT(*) > 5000
ORDER BY COUNT(*) DESC
)

SELECT 
REGEXP_SUBSTR(I.REPARTICION_SECTOR, '[^-]+', 1, 2) CODIGO_SECTOR,
SI.NOMBRE_SECTOR_INTERNO NOMBRE_SECTOR,
REPA.CODIGO_REPARTICION,
REPA.NOMBRE_REPARTICION,
MINISTERIO.NOMBRE_REPARTICION NOMBRE_MINISTERIO,
CANTIDAD AS CANTIDAD_BUZON

FROM INFO I
LEFT JOIN TRACK_GED.SADE_REPARTICION REPA ON REGEXP_SUBSTR(I.REPARTICION_SECTOR, '[^-]+', 1, 1) = REPA.CODIGO_REPARTICION
LEFT JOIN TRACK_GED.SADE_REPARTICION MINISTERIO ON MINISTERIO.ID_REPARTICION = REPA.MINISTERIO

LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SI ON SI.CODIGO_SECTOR_INTERNO = REGEXP_SUBSTR(I.REPARTICION_SECTOR, '[^-]+', 1, 2)
        AND SI.CODIGO_REPARTICION = REPA.ID_REPARTICION

WHERE MINISTERIO.CODIGO_REPARTICION = 'MJGM'
;