WITH AUX AS (
SELECT 
    ID_NOTIFICACION, 
    COUNT(*) AS CANTIDAD_INTENTOS 
FROM EE_GED.EE_NOTIFICACION_RECIBIDA
WHERE ID_NOTIFICACION IN (SELECT ID_NOTIFICACION
    FROM EE_GED.EE_NOTIFICACION_RECIBIDA WHERE ESTADO_NOTIFICACION = 'OK'
    )
GROUP BY ID_NOTIFICACION
),
NOTIFICACION_INTENTOS AS (
SELECT NR.*, AUX.CANTIDAD_INTENTOS 
FROM EE_GED.EE_NOTIFICACION_RECIBIDA NR
INNER JOIN AUX ON NR.ID_NOTIFICACION = AUX.ID_NOTIFICACION
WHERE NR.ESTADO_NOTIFICACION = 'OK'
)

SELECT 
    EE.TIPO_DOCUMENTO||'-'||EE.ANIO||'-'||EE.NUMERO||'- -'||EE.CODIGO_REPARTICION_ACTUACION||'-'||EE.CODIGO_REPARTICION_USUARIO AS NRO_EXPEDIENTE, 
    EE.CODIGO_REPARTICION_USUARIO AS COD_REPARTICION_CARATULACION, 
    REP_CARATULA.NOMBRE_REPARTICION AS REPARTICION_CARATULACION, 
    MIN_CARATULA.CODIGO_REPARTICION AS COD_ORGANISMO_CARATULACION, 
    MIN_CARATULA.NOMBRE_REPARTICION AS ORGANISMO_CARATULACION, 
	TO_CHAR(EE.FECHA_CREACION, 'DD/MM/YYYY') AS FECHA_CARATULACION, 
	TO_CHAR(EE.FECHA_CREACION, 'HH24:MI:SS') AS HORA_CARATULACION,
    TRATAS.CODIGO_TRATA,
	TRATAS.DESCRIPCION AS DESCRIPCION_TRATA,  
    EE.DESCRIPCION AS DESCRIPCION, 
    SOLEX.MOTIVO, 
    EE.ESTADO AS ESTADO_EXPEDIENTE,
    NOTIF.ID_NOTIFICACION,
    NOTIF.DOMICILIO_ELECTRONICO,
    NOTIF.ID_CAUSA,
    NOTIF.ID_AVISO,
    NOTIF.USUARIO_CARATULADOR,
    NOTIF.CONFIDENCIALIDAD,
    TO_CHAR(NOTIF.FECHA_ENVIO, 'DD/MM/YYYY HH24:MI:SS') AS FECHA_ENVIO, 
    NOTIF.CANTIDAD_INTENTOS
    
FROM NOTIFICACION_INTENTOS NOTIF
INNER JOIN EE_GED.EE_EXPEDIENTE_ELECTRONICO EE ON EE.ID_EXTERNO = NOTIF.ID_NOTIFICACION
    LEFT JOIN EE_GED.SOLICITUD_EXPEDIENTE SOLEX ON SOLEX.ID = EE.SOLICITUD_INICIADORA
    LEFT JOIN EE_GED.TRATA TRATAS ON TRATAS.ID = EE.ID_TRATA
    LEFT JOIN EE_GED.JBPM4_TASK T ON T.EXECUTION_ID_ = EE.ID_WORKFLOW
    LEFT JOIN EE_GED.JBPM4_PARTICIPATION P ON P.TASK_ = T.DBID_
    
    --Caratulacion--
    LEFT JOIN TRACK_GED.SADE_REPARTICION REP_CARATULA ON EE.CODIGO_REPARTICION_USUARIO = REP_CARATULA.CODIGO_REPARTICION
    LEFT JOIN TRACK_GED.SADE_REPARTICION MIN_CARATULA ON REP_CARATULA.MINISTERIO = MIN_CARATULA.ID_REPARTICION

WHERE
    EE.SISTEMA_CREADOR = 'SCBA' AND 
    EE.FECHA_CREACION > TO_DATE('01/01/2023','DD/MM/YYYY')

ORDER BY EE.FECHA_CREACION DESC
;