WITH RESULTADO AS (
SELECT
--origen--
R1O.CODIGO_REPARTICION AS ORIGEN_DESTINO,
--destino--
COALESCE(R1DR.CODIGO_REPARTICION,R1DU.CODIGO_REPARTICION) AS COD_MINISTERIO_DESTINO

FROM EE_GED.HISTORIALOPERACION HIST
--origen--
LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SO ON SO.NOMBRE_USUARIO = HIST.USUARIO
LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SIO ON SIO.ID_SECTOR_INTERNO = SO.ID_SECTOR_INTERNO
LEFT JOIN TRACK_GED.SADE_REPARTICION RO ON RO.ID_REPARTICION = SIO.CODIGO_REPARTICION
LEFT JOIN  TRACK_GED.SADE_REPARTICION R1O ON R1O.ID_REPARTICION = RO.MINISTERIO
--destino es usuario--
LEFT JOIN TRACK_GED.SADE_SECTOR_USUARIO SDU ON SDU.NOMBRE_USUARIO = HIST.DESTINATARIO
LEFT JOIN TRACK_GED.SADE_SECTOR_INTERNO SIDU ON SIDU.ID_SECTOR_INTERNO = SDU.ID_SECTOR_INTERNO
LEFT JOIN TRACK_GED.SADE_REPARTICION RDU ON RDU.ID_REPARTICION = SIDU.CODIGO_REPARTICION
LEFT JOIN  TRACK_GED.SADE_REPARTICION R1DU ON R1DU.ID_REPARTICION = RDU.MINISTERIO
--destino es reparticion--
LEFT JOIN TRACK_GED.SADE_REPARTICION RDR ON RDR.CODIGO_REPARTICION = (REGEXP_SUBSTR(HIST.DESTINATARIO, '[A-z]*'))
LEFT JOIN  TRACK_GED.SADE_REPARTICION R1DR ON R1DR.ID_REPARTICION = RDR.MINISTERIO

WHERE
HIST.TIPO_OPERACION = 'Pase' AND TO_CHAR(HIST.FECHA_OPERACION,'DD/MM/YYYY') = TO_CHAR(SYSDATE,'DD/MM/YYYY')
)
SELECT * FROM RESULTADO
PIVOT (
    COUNT(*) FOR COD_MINISTERIO_DESTINO IN (
'ADA'ADA,'AGG'AGG,'ARBA'ARBA,'CGP'CGP,'CGUG'CGUG,'CICMCTI'CICMCTI,'CORFOMAGP'CORFOMAGP,
'CRJYPP'CRJYPP,'CUCAIBA'CUCAIBA,'DGCYE'DGCYE,'DVMIYSPGP'DVMIYSPGP,'EAARS'EAARS,'FDE'FDE,
'HTC'HTC,'IOMA'IOMA,'IPLYCMJGM'IPLYCMJGM,'IPS'IPS,'IVMIYSPGP'IVMIYSPGP,'MCPGP'MCPGP,'MDAGP'MDAGP,
'MDCGP'MDCGP,'MGGP'MGGP,'MHYFGP'MHYFGP,'MIYSPGP'MIYSPGP,'MJGM'MJGM,'MJYDHGP'MJYDHGP,'MMPGYDSGP'MMPGYDSGP,
'MPCEITGP'MPCEITGP,'MSALGP'MSALGP,'MSGP'MSGP,'MTGP'MTGP,'OCEBA'OCEBA,'OPDS'OPDS,'OPISU'OPISU,
'OPNYAMDCGP'OPNYAMDCGP,'PALB'PALB,'SGG'SGG,'SPBMJGP'SPBMJGP,'SPBMJYDHGP'SPBMJYDHGP,'TESTGDEBA'TESTGDEBA,
'TGP'TGP,'UNVPE'UNVPE,'UNVPSO'UNVPSO)
)
ORDER BY ORIGEN_DESTINO;



  