-- ##### SCHEMA GEDO_GED #####

-- TRUNCATE TABLE  GEDO_GED.CCOO_AVISO;
-- TRUNCATE TABLE  GEDO_GED.DOCUMENTO_DATOS_VARIABLES;
-- TRUNCATE TABLE  GEDO_GED.GEDO_ARCHIVO_DE_TRABAJO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_ARCHIVO_EMBEBIDO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUD_ERROR_EDR;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUTOGUARDADO_DOC_LIBRE;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUTOGUARDADO_DOC_REF;
-- TRUNCATE TABLE  GEDO_GED.GEDO_BIBLIOTECA_DOCS;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DOCUMENTO_ADJUNTO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DOCUMENTO_SOLICITUD;
-- TRUNCATE TABLE  GEDO_GED.GEDO_ERROR_REINTENTO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_FAVORITOS;
-- TRUNCATE TABLE  GEDO_GED.GEDO_FIRMANTES;
-- TRUNCATE TABLE  GEDO_GED.GEDO_HISTORIAL;
-- TRUNCATE TABLE  GEDO_GED.GEDO_HISTORIAL_PROCESOS;
-- TRUNCATE TABLE  GEDO_GED.GEDO_HIST_VISUALIZACION;
-- TRUNCATE TABLE  GEDO_GED.GEDO_NUMERACIONESPECIAL;
-- TRUNCATE TABLE  GEDO_GED.GEDO_NUMERACIONESPECIAL_AUD;
-- TRUNCATE TABLE  GEDO_GED.GEDO_NUMERACIONESPECIAL_BCK;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_FAMILIA_AUD;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOC_PERFIL;
-- TRUNCATE TABLE  GEDO_GED.GEDO_USR_PROCESO_SELLO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_USUARIO_SELLO_PUBLICABLE;
-- TRUNCATE TABLE  GEDO_GED.MESSAGEREQUEST; 
-- TRUNCATE TABLE  GEDO_GED.PF_TAREAS_FINALIZADAS;
-- TRUNCATE TABLE  GEDO_GED.TEMPLATE_TIPO_DOC;
-- TRUNCATE TABLE  GEDO_GED.DF_FORM_COMP_VALUE;
-- TRUNCATE TABLE  GEDO_GED.DF_TRANSACTION;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUD_ERROR_CAMBIO_SIGLA;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUD_ERROR_CAMBIO_SIGLA;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AUD_TAREA_CAMBIO_SIGLA;
-- TRUNCATE TABLE  GEDO_GED.DATOS_VARIABLES_TIPO_DOC_AUD;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_REP_AUD;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_AUD;
-- TRUNCATE TABLE  GEDO_GED.CCOO_COMUNICACION_DESTINO;
-- TRUNCATE TABLE  GEDO_GED.CCOO_COMUNICACION;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DOCUMENTO_USUARIOSRESERVA;
-- TRUNCATE TABLE  GEDO_GED.GEDO_AVISO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DOCUMENTO;
-- TRUNCATE TABLE  GEDO_GED.DATOS_VARIABLES_TIPO_DOCUMENTO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_REPARTICION;
-- TRUNCATE TABLE  GEDO_GED.GEDO_NUMEROSUSADOS;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_EMBEBIDO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DOCUMENTO_TEMPLATE;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_TEMPLATE;
-- TRUNCATE TABLE  GEDO_GED.TIPO_DOC_IOP;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_TIPODOCUMENTO_FAMILIA;
-- TRUNCATE TABLE  GEDO_GED.GEDO_DISTRIBUCION_USUARIO;
-- TRUNCATE TABLE  GEDO_GED.GEDO_LIST_DISTRIB_TAREAS;
-- TRUNCATE TABLE  GEDO_GED.GEDO_LISTA_DISTRIBUCION;
-- TRUNCATE TABLE  GEDO_GED.GEDO_USUARIO_PLANTILLA;
-- TRUNCATE TABLE  GEDO_GED.GEDO_PLANTILLA;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_JOB;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_VARIABLE;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_LOB;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_DEPLOYPROP;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_DEPLOYMENT;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_PARTICIPATION;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_TASK;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_SWIMLANE;
-- TRUNCATE TABLE  GEDO_GED.JBPM4_EXECUTION;


-- ##### SCHEMA EE_GED #####

-- TRUNCATE TABLE  EE_GED.CONTROL_TC;
-- TRUNCATE TABLE EE_GED.DATOS_VARIABLES_COMBOS;
-- TRUNCATE TABLE  EE_GED.DATOS_VARIABLES_COMBO_GRUPOS;
-- TRUNCATE TABLE  EE_GED.EE_ARCH_TRABAJO_VISUALIZACION;
-- TRUNCATE TABLE  EE_GED.EE_AUDITORIA_DE_CONSULTA;
-- TRUNCATE TABLE  EE_GED.EE_AUDITORIA_NOTIFICACION;
-- TRUNCATE TABLE  EE_GED.EE_DOCUMENTO_OBLIGATORIO;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_DOCUMENTOS_0811;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_DOCUMENTOS_3010;
-- TRUNCATE TABLE  EE_GED.EE_INFORMAR_RESUELTO;
-- TRUNCATE TABLE  EE_GED.EE_NOTIFICACION_RECIBIDA;
-- TRUNCATE TABLE  EE_GED.EE_TAREA_PARALELO;
-- TRUNCATE TABLE  EE_GED.GENERAR_COPIA;
-- TRUNCATE TABLE  EE_GED.TRATAS_DIFERENCIALES;
-- TRUNCATE TABLE  EE_GED.TRATA_AUDITORIA;
-- TRUNCATE TABLE  EE_GED.TRATA_REPARTICION_AUDITORIA;
-- TRUNCATE TABLE  EE_GED.TRATA_TIPO_DOCUMENTO_AUDITORIA;
-- TRUNCATE TABLE  EE_GED.USUARIOS_FRECUENTES;
-- TRUNCATE TABLE  EE_GED.ACTIVIDAD;
-- TRUNCATE TABLE  EE_GED.TIPO_ACTIVIDAD;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_DOCUMENTOS;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_DOCUMENTOS_2510;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_DOCUMENTOS_2410;
-- TRUNCATE TABLE  EE_GED.DOCUMENTO;
-- TRUNCATE TABLE  EE_GED.EE_REPARTICION_PARTICIPANTE;
-- TRUNCATE TABLE  EE_GED.EE_ARCH_TRAB_REPA_PART;
-- TRUNCATE TABLE  EE_GED.EE_ARCHIVO_DE_TRABAJO;
-- TRUNCATE TABLE  EE_GED.HISTORIALOPERACIONDETALLES;
-- TRUNCATE TABLE  EE_GED.HISTORIALOPERACION;
-- TRUNCATE TABLE  EE_GED.EE_TRAMITACION_CONJUNTA;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_ASOCIADO;
-- TRUNCATE TABLE  EE_GED.EXPEDIENTEASOCIADO;
-- TRUNCATE TABLE  EE_GED.EE_AUD_TAREA_MIGRACION_ERROR;
-- TRUNCATE TABLE  EE_GED.EE_AUD_TAREA_MIGRACION;
-- TRUNCATE TABLE  EE_GED.EE_ARCHIVO_REMISION;
-- TRUNCATE TABLE  EE_GED.EE_CON_SUSPENSION;
-- TRUNCATE TABLE  EE_GED.METADATOS_TRATA;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_ARCHIVOSTRABAJO;
-- TRUNCATE TABLE  EE_GED.EE_EXPEDIENTE_ELECTRONICO;
-- TRUNCATE TABLE  EE_GED.SOLICITUD_EXPEDIENTE;
-- TRUNCATE TABLE  EE_GED.SOLICITANTE;
-- TRUNCATE TABLE  EE_GED.DOCUMENTO_DE_IDENTIDAD;
-- TRUNCATE TABLE  EE_GED.TRATA_REPARTICION;
-- TRUNCATE TABLE  EE_GED.TRATA_TIPO_DOCUMENTO;
-- TRUNCATE TABLE  EE_GED.DATO_VARIABLE;
-- TRUNCATE TABLE  EE_GED.TRATA;
-- TRUNCATE TABLE  EE_GED.EE_DATOS_SISTEMA_EXTERNO;
-- TRUNCATE TABLE  EE_GED.EE_CONFIG_SIST_EXTERNO;
-- TRUNCATE TABLE  EE_GED.EE_ORGANISMO_EXTERNO;
-- TRUNCATE TABLE  EE_GED.TRATA_INTEGRACION_REPARTICION;
-- TRUNCATE TABLE  EE_GED.EE_SISTEMA_EXTERNO;
-- TRUNCATE TABLE  EE_GED.JBPM4_DEPLOYPROP;
-- TRUNCATE TABLE  EE_GED.JBPM4_VARIABLE;
-- TRUNCATE TABLE  EE_GED.JBPM4_PARTICIPATION;
-- TRUNCATE TABLE  EE_GED.JBPM4_TASK;
-- TRUNCATE TABLE  EE_GED.JBPM4_SWIMLANE;
-- TRUNCATE TABLE  EE_GED.JBPM4_EXECUTION;
-- TRUNCATE TABLE  EE_GED.JBPM4_JOB;
-- TRUNCATE TABLE  EE_GED.JBPM4_LOB;
-- TRUNCATE TABLE  EE_GED.JBPM4_DEPLOYMENT;


-- ##### SCHEMA EU_GED #####

-- TRUNCATE TABLE  EU_GED.EU_ALERTA_AVISO;		
-- TRUNCATE TABLE  EU_GED.EU_ALERTA_AVISO_EE;
-- TRUNCATE TABLE  EU_GED.EU_ALERTA_AVISO_GEDO;
-- TRUNCATE TABLE  EU_GED.EU_BUZON_DE_OTRO;
-- TRUNCATE TABLE  EU_GED.EU_FERIADOS_AUDI;
-- TRUNCATE TABLE  EU_GED.EU_LOCALIDAD;
-- TRUNCATE TABLE  EU_GED.EU_NOVEDAD_APLICACION;
-- TRUNCATE TABLE  EU_GED.EU_NOVEDAD_HIST;
-- TRUNCATE TABLE  EU_GED.EU_USUARIO_BUZONGRUPAL;
-- TRUNCATE TABLE  EU_GED.EU_USUARIO_BUZONOTROS;

-- DELETE FROM EU_GED.EU_USUARIO_FRECUENCIAS WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;
-- DELETE FROM  EU_GED.EU_USUARIO_MISSISTEMAS WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;
-- TRUNCATE TABLE  EU_GED.EU_USUARIO_MISSUPERVISADOS;
-- DELETE FROM  EU_GED.EU_USUARIO_MISTAREAS WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;
-- DELETE FROM  EU_GED.EU_VENCIMIENTO_PASS WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;
-- TRUNCATE TABLE  EU_GED.MENSAJES_LOGIN ;
-- DELETE FROM  EU_GED.MIG_DATO_CONSULTA WHERE (codigo_usuario != 'PUESTAINICIAL' OR codigo_reparticion != 'TESTGDEBA');
-- COMMIT;
-- TRUNCATE TABLE  EU_GED.MIG_TAREA;
-- TRUNCATE TABLE  EU_GED.MIG_TAREA_HIST;
-- TRUNCATE TABLE  EU_GED.REVINFO ;

-- TRUNCATE TABLE  EU_GED.SADE_APP_ALIVE_LOGGER;
-- TRUNCATE TABLE  EE_GED.USUARIOS_LOGUEADOS;

TRUNCATE TABLE  EU_GED.EU_NOVEDAD;
TRUNCATE TABLE  EU_GED.EU_CATEGORIA;

TRUNCATE TABLE  EU_GED.MIG_LOGUEO_ERROR;					
TRUNCATE TABLE  EU_GED.MIG_TIPO_ERROR;

TRUNCATE TABLE  EU_GED.EU_ALERTAS_AVISOS;


-- ##### SCHEMA CO_GED #####

-- DELETE FROM  CO_GED.CARGOS_HIST WHERE (id != 30);
-- COMMIT;							
-- TRUNCATE TABLE  CO_GED.DATOS_USUARIO_SYNCH;
-- TRUNCATE TABLE  CO_GED.ST_AVISO;
-- TRUNCATE TABLE  CO_GED.PERIODO_LICENCIA;
-- DELETE FROM  CO_GED.DATOS_USUARIO_HIST WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;

DELETE FROM  CO_GED.REVINFO WHERE (rev NOT IN 
	(SELECT REVISION FROM CO_GED.DATOS_USUARIO_HIST WHERE USUARIO = 'PUESTAINICIAL'));
COMMIT;

-- DELETE FROM  CO_GED.DATOS_USUARIO WHERE (usuario != 'PUESTAINICIAL');
-- COMMIT;
-- DELETE FROM  CO_GED.CARGOS WHERE (id != 30);
-- COMMIT;


-- ##### SCHEMA TRACK_GED #####

-- TRUNCATE TABLE  TRACK_GED.CRUCE;
-- TRUNCATE TABLE  TRACK_GED.GDE_ALTA_USUARIOS_WORK;
-- DELETE FROM  TRACK_GED.SADE_AUDITORIA WHERE (user_id != 'PUESTAINICIAL');
-- COMMIT;

TRUNCATE TABLE  TRACK_GED.SADE_EXPEDIENTE_AUDI;
TRUNCATE TABLE  TRACK_GED.SADE_EXPEDIENTE;
TRUNCATE TABLE  TRACK_GED.SADE_EXPEDIENTE_AUDI_MIG;
TRUNCATE TABLE  TRACK_GED.SADE_EXTRACTO;

-- TRUNCATE TABLE  TRACK_GED.SADE_JURISDICCION;
-- TRUNCATE TABLE  TRACK_GED.SADE_MIG_BITACORA_TRACK;
-- TRUNCATE TABLE  TRACK_GED.SADE_PARAM_AUDIT;

TRUNCATE TABLE  TRACK_GED.SADE_PASE_COPIA;
TRUNCATE TABLE  TRACK_GED.SADE_PASE;
TRUNCATE TABLE  TRACK_GED.SADE_PASE_AUDI_MIG;
TRUNCATE TABLE  TRACK_GED.SADE_PERMANENCIA;

-- TRUNCATE TABLE  TRACK_GED.SADE_REMITO_SECUENCIA;
-- DELETE FROM  TRACK_GED.SADE_USR_REPA_HABILITADA WHERE (nombre_usuario != 'PUESTAINICIAL');
-- COMMIT;

-- TRUNCATE TABLE  TRACK_GED.SADE_WORK_ANOMALIAS;
-- TRUNCATE TABLE  TRACK_GED.SADE_WORK_ANOMALIAS_PASE;
-- TRUNCATE TABLE  TRACK_GED.SADE_WORK_EX_DUP_ANT_2011;
-- TRUNCATE TABLE  TRACK_GED.SADE_WORK_EX_DUP_RES_ANT_2011;
-- DELETE FROM  TRACK_GED.SADE_USR_REPA_HABILITADA_HIST WHERE (nombre_usuario != 'PUESTAINICIAL');
-- COMMIT;
-- TRUNCATE TABLE  TRACK_GED.SADE_ADMIN_REPARTICION_HIST;
-- DELETE FROM  TRACK_GED.SADE_SECTOR_USUARIO_HIST WHERE (nombre_usuario = 'PUESTAINICIAL');
-- COMMIT;
-- TRUNCATE TABLE  TRACK_GED.SADE_AGRUPACION_SECTOR_MESA;
-- DELETE FROM  TRACK_GED.SADE_SECTOR_USUARIO_AUDI WHERE (nombre_usuario != 'PUESTAINICIAL');
-- COMMIT;
-- DELETE FROM  TRACK_GED.SADE_SECTOR_USUARIO WHERE (nombre_usuario != 'PUESTAINICIAL');
-- COMMIT;
-- DELETE FROM  TRACK_GED.SADE_SECTOR_INTERNO_AUDI WHERE (nombre_sector_interno != 'TESTGDEBA');
-- COMMIT;
-- TRUNCATE TABLE  TRACK_GED.SADE_REPARTICION_SELECCIONADA;

TRUNCATE TABLE  TRACK_GED.SADE_EXPEDIENTE;
TRUNCATE TABLE  TRACK_GED.SADE_PASE_DETALLE_AUDI;
TRUNCATE TABLE  TRACK_GED.SADE_PASE;
TRUNCATE TABLE  TRACK_GED.SADE_REMITO;
TRUNCATE TABLE  TRACK_GED.SADE_ACTUACION_AUDI;
TRUNCATE TABLE  TRACK_GED.SADE_ACTUACIONES_DESHABILITADA;
TRUNCATE TABLE  TRACK_GED.SADE_SECTOR_REPARTICION;
DELETE FROM  TRACK_GED.SADE_SECTOR_INTERNO WHERE (codigo_sector_interno != 'TESTGDEBA');
COMMIT;

-- DELETE FROM  TRACK_GED.SADE_REPARTICION_AUDI WHERE (codigo_reparticion != 'TESTGDEBA');
-- COMMIT;
-- TRUNCATE TABLE  TRACK_GED.SADE_ADMIN_REPARTICION;

DELETE FROM  TRACK_GED.SADE_CALLE WHERE (id_calle not in (
	SELECT CALLE FROM TRACK_GED.SADE_SECTOR_INTERNO_AUDI WHERE (nombre_sector_interno = 'TESTGDEBA')))

TRUNCATE TABLE  TRACK_GED.SADE_REPARTICION_UAI;
TRUNCATE TABLE  TRACK_GED.SADE_UAI;

DELETE FROM  TRACK_GED.SADE_REPARTICION WHERE (codigo_reparticion != 'TESTGDEBA');
COMMIT;



			


