SELECT
	RR.ID_REGISTRO,
    TO_CHAR (RR.FECHA_INUTILIZACION, 'YYYY-MM-DD') AS FECHA_INUTILIZACION,
    C.ID_CIRCUNSCRIPCION AS ID_DELEGACION,
    C.NOMBRE AS DELEGACION_INSCRIPCION,
    L.ID AS ID_LOCALIDAD_INSCRIPCION,
  	L.NOMBRE AS LOCALIDAD_INSCRIPCION,
    DL.ID AS ID_PARTIDO_INSCRIPCION,
  	DL.NOMBRE AS PARTIDO_INSCRIPCION,
    COALESCE(RAR.ANIO,DT.ANIO) AS ANIO,
    COALESCE(RAR.TOMO||RAR.LETRA_TOMO, DT.TOMO) AS TOMO,
    NVL(RAR.FOLIO,0) AS FOLIO,
    COALESCE(RAR.NUMERO_ACTA,DT.ACTA) AS NUMERO_ACTA,
    COALESCE((TO_CHAR(RAR.FECHA_CREACION,'YYYY-MM-DD')),(TO_CHAR(RPM1.FECHA_CREACION,'YYYY-MM-DD'))) AS FECHA_CREACION,
    SSR.ID_SUBTIPO_REGISTRO AS ID_SUBTIPO,
  	SSR.DESCRIPCION AS SUBTIPO,
    NVL(F.ACTIVITY_NAME_, 'Cerrado') ESTADO,
    TO_CHAR(RR.FECHA_ULTIMA_MODIFICACION,'YYYY-MM-DD') AS ESTADO_ULTIMA_MODIF,
  	NVL(RAR.ID_ACTA_REGISTRO,0) AS ID_ACTA_UNION,
    TO_CHAR (MAT.FECHA_INICIO_CONVIVENCIA, 'YYYY-MM-DD') AS FECHA_INICIO_CONVIVENCIA,
  	RP1.ID_PERSONA AS "ID_CONVIVIENTE1",
  	STD2.DESCRIPCION AS "TIPO_DOC_CONVIVIENTE1",
  	RP1.NUMERO_DOCUMENTO AS "NRO_DOC_CONVIVIENTE1",
  	CONCAT ( RP1.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP1.SEGUNDO_NOMBRE), CONCAT (' ', RP1.TERCER_NOMBRE))) AS "NOMBRES_CONVIVIENTE1",
  	CONCAT ( RP1.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP1.SEGUNDO_APELLIDO), CONCAT (' ', RP1.TERCER_APELLIDO))) AS "APELLIDOS_CONVIVIENTE1",
  	NACPM1.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_CONVIVIENTE1",
  	SEXPM1.DESCRIPCION AS "SEXO_CONVIVIENTE1",
  	TO_CHAR (RP1.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_CONVIVIENTE1",
  	RP1.ESTADO_CIVIL AS "ESTADO_CIVIL_CONVIVIENTE1",
  	RP1.PROFESION AS "PROFESION_CONVIVIENTE1",
  	
	CASE DOMPM1.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (', ', DOMPM1.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM1.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM1.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM1.MANZANA, CONCAT (', Casa: ', DOMPM1.CASA)))))
      WHEN 5
        THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (' - ', DOMPM1.CALLE_ALTURA))))
  	END AS "DOMICILIO_CONVIVIENTE1",
    
	CASE DOMREAL1.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMREAL1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMREAL1.LOCALIDAD, CONCAT (', ', DOMREAL1.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMREAL1.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMREAL1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asepREAL.nombre, CONCAT ( ', Manzana: ', CONCAT (DOMREAL1.manzana, CONCAT (', Casa: ', DOMREAL1.casa)))))
      WHEN 5
        THEN CONCAT (DOMREAL1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMREAL1.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMREAL1.LOCALIDAD, CONCAT (' - ', DOMREAL1.CALLE_ALTURA))))
    END AS "DOMICILIO_NACIMIENTO_CONV1",

    RP4.ID_PERSONA AS "ID_MADRE_PADRE1_CONV1",
    STD4.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1_CONV1",
    RP4.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1_CONV1",
    RP4.CUIL AS "CUIL_MADRE_PADRE1_CONV1",
    CONCAT ( RP4.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP4.SEGUNDO_NOMBRE), CONCAT (' ', RP4.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1_CONV1",
    CONCAT ( RP4.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP4.SEGUNDO_APELLIDO), CONCAT (' ', RP4.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1_CONV1",
    SEXPM4.DESCRIPCION AS "SEXO_MADRE_PADRE1_CONV1",
    NACPM4.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE1_CONV1",
    TO_CHAR (RP4.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NAC_MADRE_PADRE1_CONV1",
    RP4.TELEFONO AS "TEL_MADRE_PADRE1_CONV1",
    RP4.EMAIL AS "MAIL_MADRE_PADRE1_CONV1",
    RP4.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE1_CONV1",
    RP4.PROFESION AS "PROFESION_MADRE_PADRE1_CONV1",

    RP5.ID_PERSONA AS "ID_MADRE_PADRE2_CONV1",
    STD5.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2_CONV1",
    RP5.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2_CONV1",
    RP5.CUIL AS "CUIL_MADRE_PADRE2_CONV1",
    CONCAT ( RP5.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP5.SEGUNDO_NOMBRE), CONCAT (' ', RP5.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2_CONV1",
    CONCAT ( RP5.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP5.SEGUNDO_APELLIDO), CONCAT (' ', RP5.TERCER_APELLIDO))) AS "APELL_MADRE_PADRE2_CONV1",
    SEXPM5.DESCRIPCION AS "SEXO_MADRE_PADRE2_CONV1",
    NACPM5.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE2_CONV1",
    TO_CHAR (RP5.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE2_CONV1",
    RP5.TELEFONO AS "TEL_MADRE_PADRE2_CONV1",
    RP5.EMAIL AS "MAIL_MADRE_PADRE2_CONV1",
    RP5.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE2_CONV1",
    RP5.PROFESION AS "PROFESION_MADRE_PADRE2_CONV1",
  
    CASE DOMPM5.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM5.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM5.LOCALIDAD, CONCAT (', ', DOMPM5.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM5.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM5.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP5.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM5.MANZANA, CONCAT (', Casa: ', DOMPM5.CASA)))))
      WHEN 5
        THEN CONCAT (DOMPM5.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM5.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM5.LOCALIDAD, CONCAT (' - ', DOMPM5.CALLE_ALTURA))))
    END AS "DOMICILIO MADRE_PADRE2_CONV1",

    RP2.ID_PERSONA AS "ID_CONVIVIENTE2",
    STD3.DESCRIPCION AS "TIPO_DOC_CONVIVIENTE2",
    RP2.NUMERO_DOCUMENTO AS "NRO_DOC_CONVIVIENTE2",
    CONCAT (RP2.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP2.SEGUNDO_NOMBRE), CONCAT (' ', RP2.TERCER_NOMBRE))) AS "NOMBRES_CONVIVIENTE2",
    CONCAT (RP2.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP2.SEGUNDO_APELLIDO), CONCAT (' ', RP2.TERCER_APELLIDO))) AS "APELLIDOS_CONVIVIENTE2",
    NACPM2.DESCRIPCION_NACIONALIDAD AS "NAC_CONVIVIENTE2",
    SEXPM2.DESCRIPCION AS "SEXO_CONVIVIENTE2",
    TO_CHAR (RP2.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_CONVIVIENTE2",
    RP2.ESTADO_CIVIL AS "EST_CIVIL_CONVIVIENTE2",
    RP2.PROFESION AS "PROFESION_CONVIVIENTE2",
    
    CASE DOMPM2.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (', ', DOMPM2.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM2.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asep2.nombre, CONCAT ( ', Manzana: ', CONCAT (DOMPM2.MANZANA, CONCAT (', Casa: ', DOMPM2.CASA)))))
      WHEN 5
        THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (' - ', DOMPM2.CALLE_ALTURA))))
    END AS "DOMICILIO_CONVIVIENTE2",
    
    CASE DOMPM4.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM4.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM4.LOCALIDAD, CONCAT (', ', DOMPM4.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM4.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM4.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM4.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM4.MANZANA, CONCAT (', Casa: ', DOMPM4.CASA)))))
      WHEN 5
        THEN CONCAT (DOMPM4.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM4.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM4.LOCALIDAD, CONCAT (' - ', DOMPM4.CALLE_ALTURA))))
    END AS "DOM_MADRE_PADRE1_CONV1",
  
    CASE DOMREAL2.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMREAL2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMREAL2.LOCALIDAD, CONCAT (', ', DOMREAL2.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMREAL2.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMREAL2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 4
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asepREAL2.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMREAL2.MANZANA, CONCAT (', Casa: ', DOMREAL2.CASA)))))
      WHEN 5
        THEN CONCAT (DOMREAL2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMREAL2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMREAL2.LOCALIDAD, CONCAT (' - ', DOMREAL2.CALLE_ALTURA))))
    END AS "DOMICILIO_NACIMIENTO_CONV2",
  
    RP6.ID_PERSONA AS "ID_MADRE_PADRE1_CONV2",
    STD6.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1_CONV2",
    RP6.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1_CONV2",
    RP6.CUIL AS "CUIL_MADRE_PADRE1_CONV2",
    CONCAT ( RP6.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP6.SEGUNDO_NOMBRE), CONCAT (' ', RP6.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1_CONV2",
    CONCAT ( RP6.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP6.SEGUNDO_APELLIDO), CONCAT (' ', RP6.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1_CONV2",
    SEXPM6.DESCRIPCION AS "SEXO_MADRE_PADRE1_CONV2",
    NACPM6.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE1_CONV2",
    TO_CHAR (RP6.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE1_CONV2",
    RP6.EMAIL AS "MAIL_MADRE_PADRE1_CONV2",
    RP6.TELEFONO AS "TEL_MADRE_PADRE1_CONV2",
    RP6.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE1_CONV2",
    RP6.PROFESION AS "PROF_MADRE_PADRE1_CONV2",
  
    CASE DOMPM6.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM6.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM6.LOCALIDAD, CONCAT (', ', DOMPM6.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM6.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM6.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 6
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM6.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM6.MANZANA, CONCAT (', Casa: ', DOMPM6.CASA)))))
      WHEN 7
        THEN CONCAT (DOMPM6.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM6.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM6.LOCALIDAD, CONCAT (' - ', DOMPM6.CALLE_ALTURA))))
    END AS "DOM_MADRE_PADRE1_CONV2",
    
    RP7.ID_PERSONA AS "ID_MADRE_PADRE2_CONV2",
    STD7.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2_CONV2",
    RP7.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2_CONV2",
    RP7.CUIL AS "CUIL_MADRE_PADRE2_CONV2",
    CONCAT ( RP7.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP7.SEGUNDO_NOMBRE), CONCAT (' ', RP7.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2_CONV2",
    CONCAT ( RP7.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP7.SEGUNDO_APELLIDO), CONCAT (' ', RP7.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE2_CONV2",
    NACPM7.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE2_CONV2",
    TO_CHAR (RP7.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE2_CONV2",
    SEXPM7.DESCRIPCION AS "SEXO_MADRE_PADRE2_CONV2",
    RP7.EMAIL AS "MAIL_MADRE_PADRE2_CONV2",
    RP7.TELEFONO AS "TEL_MADRE_PADRE2_CONV2",
    RP7.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE2_CONV2",
    RP7.PROFESION AS "PROFESION_MADRE_PADRE2_CONV2",
  
    CASE DOMPM7.FK_TIPO_DOMICILIO
      WHEN 1
        THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM7.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM7.LOCALIDAD, CONCAT (', ', DOMPM7.CALLE_ALTURA)))))
      WHEN 2
        THEN TO_CHAR (DOMPM7.OBSERVACIONES)
      WHEN 3
        THEN CONCAT (DOMPM7.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 6
        THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP7.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM7.MANZANA, CONCAT (', Casa: ', DOMPM7.CASA)))))
      WHEN 7
        THEN CONCAT (DOMPM7.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
      WHEN 7
        THEN CONCAT ( DOMPM7.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM7.LOCALIDAD, CONCAT (' - ', DOMPM7.CALLE_ALTURA))))
    END AS "DOMICILIO_MADRE_PADRE2_CONV2",
    MAT.TRANSCRIPCION_LIBRE AS "TRANSCRIPCION"
    
---------------------------------------------------------------------------------------------------

FROM RCE_GED.RCE_REGISTRO RR
LEFT OUTER JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SSR ON (RR.FK_SUBTIPO_REGISTRO = SSR.ID_SUBTIPO_REGISTRO)
LEFT OUTER JOIN RCE_GED.RCE_MATRIMONIO MAT ON MAT.ID_REGISTRO = RR.ID_REGISTRO
LEFT OUTER JOIN RCE_GED.RCE_CONVENCION_MATRIMONIAL CONV ON CONV.ID_CONVENCION_MATRIMONIAL =  MAT.FK_CONVENCION_MATRIMONIAL
LEFT OUTER JOIN RCE_GED.RCE_ACTA_REGISTRO RAR ON (RR.ID_REGISTRO = RAR.FK_REGISTRO)
LEFT OUTER JOIN RCE_GED.RCE_DIGITAL D ON (RR.ID_REGISTRO = D.ID_REGISTRO)
LEFT OUTER JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT ON (D.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO)
LEFT JOIN RCE_GED.JBPM4_TASK F ON RR.ID_FLUJO_JBPM = F.EXECUTION_ID_

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM1 ON RPM1.FK_REGISTRO = RR.ID_REGISTRO AND RPM1.EVENTO     = 'onContrayente1'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP1 ON (RPM1.FK_PERSONA = RP1.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD2 ON (RP1.FK_TIPO_DOCUMENTO = STD2.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM1 ON NACPM1.ID_NACIONALIDAD = RP1.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM1 ON SEXPM1.ID_SEXO = RP1.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM1 ON DOMPM1.ID_DOMICILIO = RP1.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM1 ON ASEPM1.ID_ASENTAMIENTO = DOMPM1.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMREAL1 ON DOMREAL1.ID_DOMICILIO = RP1.FK_DOMICILIO_NACIMIENTO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPREAL ON ASEPREAL.ID_ASENTAMIENTO = DOMREAL1.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM2 ON RPM2.FK_REGISTRO = RR.ID_REGISTRO AND RPM2.EVENTO     = 'onContrayente2'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP2 ON (RPM2.FK_PERSONA = RP2.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD3 ON (RP2.FK_TIPO_DOCUMENTO = STD3.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM2 ON NACPM2.ID_NACIONALIDAD = RP2.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM2 ON SEXPM2.ID_SEXO = RP2.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM2 ON DOMPM2.ID_DOMICILIO = RP2.FK_DOMICILIO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMREAL2 ON DOMREAL2.ID_DOMICILIO = RP2.FK_DOMICILIO_NACIMIENTO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPREAL2 ON ASEPREAL2.ID_ASENTAMIENTO = DOMREAL2.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP2 ON ASEP2.ID_ASENTAMIENTO = DOMPM2.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM4 ON RPM4.FK_REGISTRO = RR.ID_REGISTRO AND RPM4.EVENTO     = 'onPadre1'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP4 ON (RPM4.FK_PERSONA = RP4.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD4 ON (RP4.FK_TIPO_DOCUMENTO = STD4.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM4 ON NACPM4.ID_NACIONALIDAD = RP4.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM4 ON SEXPM4.ID_SEXO = RP4.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM4 ON DOMPM4.ID_DOMICILIO = RP4.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM4 ON ASEPM4.ID_ASENTAMIENTO = DOMPM4.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM5 ON RPM5.FK_REGISTRO = RR.ID_REGISTRO AND RPM5.EVENTO     = 'onPadre2'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP5 ON (RPM5.FK_PERSONA = RP5.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD5 ON (RP5.FK_TIPO_DOCUMENTO = STD5.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM5 ON NACPM5.ID_NACIONALIDAD = RP5.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM5 ON SEXPM5.ID_SEXO = RP5.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM5 ON DOMPM5.ID_DOMICILIO = RP5.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP5 ON ASEP5.ID_ASENTAMIENTO = DOMPM5.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM6 ON RPM6.FK_REGISTRO = RR.ID_REGISTRO AND RPM6.EVENTO     = 'onPadre3'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP6 ON (RPM6.FK_PERSONA = RP6.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD6 ON (RP6.FK_TIPO_DOCUMENTO = STD6.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM6 ON NACPM6.ID_NACIONALIDAD = RP6.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM6 ON SEXPM6.ID_SEXO = RP6.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM6 ON DOMPM6.ID_DOMICILIO = RP6.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM6 ON ASEPM6.ID_ASENTAMIENTO = DOMPM6.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM7 ON RPM7.FK_REGISTRO = RR.ID_REGISTRO AND RPM7.EVENTO     = 'onPadre4'
LEFT OUTER JOIN RCE_GED.RCE_PERSONA RP7 ON (RPM7.FK_PERSONA = RP7.ID_PERSONA)
LEFT OUTER JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD7 ON (RP7.FK_TIPO_DOCUMENTO = STD7.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM7 ON NACPM7.ID_NACIONALIDAD = RP7.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM7 ON SEXPM7.ID_SEXO = RP7.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM7 ON DOMPM7.ID_DOMICILIO = RP7.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP7 ON ASEP7.ID_ASENTAMIENTO = DOMPM5.FK_ASENTAMIENTO
  
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON RR.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
INNER JOIN RCE_GED.EU_LOCALIDAD L ON C.FK_LOCALIDAD = L.ID
INNER JOIN RCE_GED.EU_DEPARTAMENTO DL ON L.ID_DEPARTAMENTO = DL.ID   

---------------------------------------------------------------------------------------------------
  
WHERE 
  REPARTICION_USUARIO  != 'TESTGDEBA'
  AND RR.USUARIO_INUTILIZACION IS NULL
  AND RR.USUARIO_INMOVILIZACION IS NULL
  AND RR.FK_SUBTIPO_REGISTRO IN (83,84,86,102);
