SELECT 
  RR.ID_REGISTRO,
  TO_CHAR (RR.FECHA_INUTILIZACION, 'YYYY-MM-DD') AS FECHA_INUTILIZACION,
  COALESCE(DTC.ID_CIRCUNSCRIPCION, C.ID_CIRCUNSCRIPCION) AS ID_DELEGACION,
  COALESCE(DTC.NOMBRE,C.NOMBRE) AS DELEGACION_INSCRIPCION,
  COALESCE(DTL.ID,L.ID) AS ID_LOCALIDAD_INSCRIPCION,
  COALESCE(DTL.NOMBRE,L.NOMBRE) AS LOCALIDAD_INSCRIPCION,
  COALESCE(DTDL.ID,DL.ID) AS ID_PARTIDO_INSCRIPCION,
  COALESCE(DTDL.NOMBRE,DL.NOMBRE) AS PARTIDO_INSCRIPCION,
  COALESCE(DT.ANIO,RAR.ANIO) AS ANIO,
  COALESCE(DT.TOMO,RAR.TOMO||RAR.LETRA_TOMO) AS TOMO,
  NVL(RAR.FOLIO,0) AS FOLIO,
  COALESCE(DT.ACTA,RAR.NUMERO_ACTA) AS NUMERO_ACTA,
  TO_CHAR(COALESCE(RAR.FECHA_CREACION,RPM1.FECHA_CREACION),'YYYY-MM-DD') AS FECHA_CREACION,
  SSR.ID_SUBTIPO_REGISTRO AS ID_SUBTIPO,
  SSR.DESCRIPCION AS SUBTIPO,
  NVL(F.ACTIVITY_NAME_, 'Cerrado') ESTADO,
  TO_CHAR(RR.FECHA_ULTIMA_MODIFICACION,'YYYY-MM-DD') AS ESTADO_ULTIMA_MODIF,
  DECODE(RV.ID_REGISTRO_ANTECESOR, NULL, 'NO TIENE', 'SI') AS "CON VINC. REGISTRO ANTECESOR",
  RV.ID_REGISTRO_ANTECESOR,
  MAT.FECHA_MATRIMONIO,
  NVL(RAR.ID_ACTA_REGISTRO,0) AS ID_ACTA_MATRIMONIO,
  RP1.ID_PERSONA AS "ID_CONTRAYENTE1",
  STD2.DESCRIPCION AS "TIPO_DOC_CONTRAYENTE1",
  RP1.NUMERO_DOCUMENTO AS "NRO_DOC_CONTRAYENTE1",
  CONCAT ( RP1.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP1.SEGUNDO_NOMBRE), CONCAT (' ', RP1.TERCER_NOMBRE))) AS "NOMBRES_CONTRAYENTE1",
  CONCAT ( RP1.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP1.SEGUNDO_APELLIDO), CONCAT (' ', RP1.TERCER_APELLIDO))) AS "APELLIDOS_CONTRAYENTE1",
  NACPM1.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_CONTRAYENTE1",
  SEXPM1.DESCRIPCION AS "SEXO_CONTRAYENTE1",
  TO_CHAR (RP1.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_CONTRAYENTE1",
  RP1.ESTADO_CIVIL AS "ESTADO_CIVIL_CONTRAYENTE1",
  RP1.PROFESION AS "PROFESION_CONTRAYENTE1",
  
  CASE DOMPM1.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (', ', DOMPM1.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM1.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM1.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM1.MANZANA, CONCAT (', Casa: ', DOMPM1.CASA)))))
    WHEN 5
    THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (' - ', DOMPM1.CALLE_ALTURA))))
  END AS "DOMICILIO_CONTRAYENTE1",
  
  RP4.ID_PERSONA AS "ID_MADRE_PADRE1_CONT1",
  STD4.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1_CONT1",
  RP4.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1_CONT1",
  RP4.CUIL AS "CUIL_MADRE_PADRE1_CONT1",
  CONCAT ( RP4.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP4.SEGUNDO_NOMBRE), CONCAT (' ', RP4.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1_CONT1",
  CONCAT ( RP4.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP4.SEGUNDO_APELLIDO), CONCAT (' ', RP4.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1_CONT1",
  SEXPM4.DESCRIPCION AS "SEXO_MADRE_PADRE1_CONT1",
  NACPM4.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE1_CONT1",
  TO_CHAR (RP4.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NAC_MADRE_PADRE1_CONT1",
  RP4.TELEFONO AS "TEL_MADRE_PADRE1_CONT1",
  RP4.EMAIL AS "MAIL_MADRE_PADRE1_CONT1",
  RP4.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE1_CONT1",
  RP4.PROFESION AS "PROFESION_MADRE_PADRE1_CONT1",
  
  CASE DOMPM4.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM4.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM4.LOCALIDAD, CONCAT (', ', DOMPM4.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM4.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM4.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM4.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM4.MANZANA, CONCAT (', Casa: ', DOMPM4.CASA)))))
    WHEN 5
    THEN CONCAT (DOMPM4.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM4.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM4.LOCALIDAD, CONCAT (' - ', DOMPM4.CALLE_ALTURA))))
  END AS "DOM_MADRE_PADRE1_CONT1",
  
  RP5.ID_PERSONA AS "ID_MADRE_PADRE2_CONT1",
  STD5.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2_CONT1",
  RP5.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2_CONT1",
  RP5.CUIL AS "CUIL_MADRE_PADRE2_CONT1",
  CONCAT ( RP5.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP5.SEGUNDO_NOMBRE), CONCAT (' ', RP5.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2_CONT1",
  CONCAT ( RP5.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP5.SEGUNDO_APELLIDO), CONCAT (' ', RP5.TERCER_APELLIDO))) AS "APELL_MADRE_PADRE2_CONT1",
  SEXPM5.DESCRIPCION  AS "SEXO_MADRE_PADRE2",
  NACPM5.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE2_CONT1",
  TO_CHAR (RP5.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE2_CONT1",
  RP5.TELEFONO AS "TEL_MADRE_PADRE2_CONT1",
  RP5.EMAIL AS "MAIL_MADRE_PADRE2_CONT1",
  RP5.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE2_CONT1",
  RP5.PROFESION AS "PROFESION_MADRE_PADRE2_CONT1",
  
  CASE DOMPM5.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM5.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM5.LOCALIDAD, CONCAT (', ', DOMPM5.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM5.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM5.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asep5.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM5.MANZANA, CONCAT (', Casa: ', DOMPM5.CASA)))))
    WHEN 5
    THEN CONCAT (DOMPM5.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM5.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM5.LOCALIDAD, CONCAT (' - ', DOMPM5.CALLE_ALTURA))))
  END AS "DOMICILIO MADRE_PADRE2_CONT1",
  
  RP2.ID_PERSONA AS "ID_CONTRAYENTE2",
  STD3.DESCRIPCION AS "TIPO_DOC_CONTRAYENTE2",
  RP2.NUMERO_DOCUMENTO AS "NRO_DOC_CONTRAYENTE2",
  CONCAT ( RP2.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP2.SEGUNDO_NOMBRE), CONCAT (' ', RP2.TERCER_NOMBRE))) AS "NOMBRES_CONTRAYENTE2",
  CONCAT ( RP2.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP2.SEGUNDO_APELLIDO), CONCAT (' ', RP2.TERCER_APELLIDO))) AS "APELLIDOS_CONTRAYENTE2",
  NACPM2.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_CONTRAYENTE2",
  SEXPM2.DESCRIPCION AS "SEXO_CONTRAYENTE2",
  TO_CHAR (RP2.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_CONTRAYENTE2",
  RP2.ESTADO_CIVIL AS "EST_CIVIL_CONTRAYENTE2",
  RP2.PROFESION AS "PROFESION_CONTRAYENTE2",
  
  CASE DOMPM2.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (', ', DOMPM2.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM2.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 4
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asep2.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM2.MANZANA, CONCAT (', Casa: ', DOMPM2.CASA)))))
    WHEN 5
    THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (' - ', DOMPM2.CALLE_ALTURA))))
  END AS "DOMICILIO CONTRAYENTE2",

  RP6.ID_PERSONA AS "ID_MADRE_PADRE1_CONT2",
  STD6.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1_CONT2",
  RP6.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1_CONT2",
  RP6.CUIL AS "CUIL_MADRE_PADRE1_CONT2",
  CONCAT ( RP6.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP6.SEGUNDO_NOMBRE), CONCAT (' ', RP6.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1_CONT2",
  CONCAT ( RP6.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP6.SEGUNDO_APELLIDO), CONCAT (' ', RP6.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1_CONT2",
  SEXPM6.DESCRIPCION AS "SEXO_MADRE_PADRE1_CONT2",
  NACPM6.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE1_CONT2",
  TO_CHAR (RP6.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE1_CONT2",
  RP6.EMAIL AS "MAIL_MADRE_PADRE1_CONT2",
  RP6.TELEFONO AS "TEL_MADRE_PADRE1_CONT2",
  RP6.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE1_CONT2",
  RP6.PROFESION AS "PROF_MADRE_PADRE1_CONT2",

  CASE DOMPM6.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM6.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM6.LOCALIDAD, CONCAT (', ', DOMPM6.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM6.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM6.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 6
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM6.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM6.MANZANA, CONCAT (', Casa: ', DOMPM6.CASA)))))
    WHEN 7
    THEN CONCAT (DOMPM6.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM6.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM6.LOCALIDAD, CONCAT (' - ', DOMPM6.CALLE_ALTURA))))
  END AS "DOM_MADRE_PADRE1_CONT2",

  RP7.ID_PERSONA AS "ID_MADRE_PADRE2_CONT2",
  STD7.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2_CONT2",
  RP7.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2_CONT2",
  RP7.CUIL AS "CUIL_MADRE_PADRE2_CONT2",
  CONCAT ( RP7.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP7.SEGUNDO_NOMBRE), CONCAT (' ', RP7.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2_CONT2",
  CONCAT ( RP7.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP7.SEGUNDO_APELLIDO), CONCAT (' ', RP7.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE2_CONT2",
  NACPM7.DESCRIPCION_NACIONALIDAD AS "NAC_MADRE_PADRE2_CONT2",
  TO_CHAR (RP7.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FEC_NAC_MADRE_PADRE2_CONT2",
  SEXPM7.DESCRIPCION AS "SEXO_MADRE_PADRE2_CONT2",
  RP7.EMAIL AS "MAIL_MADRE_PADRE2_CONT2",
  RP7.TELEFONO AS "TEL_MADRE_PADRE2_CONT2",
  RP7.ESTADO_CIVIL AS "EST_CIVIL_MADRE_PADRE2_CONT2",
  RP7.PROFESION AS "PROFESION_MADRE_PADRE2_CONT2",

  CASE DOMPM7.FK_TIPO_DOMICILIO
    WHEN 1
    THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM7.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM7.LOCALIDAD, CONCAT (', ', DOMPM7.CALLE_ALTURA)))))
    WHEN 2
    THEN TO_CHAR (DOMPM7.OBSERVACIONES)
    WHEN 3
    THEN CONCAT (DOMPM7.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 6
    THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( asep7.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM7.MANZANA, CONCAT (', Casa: ', DOMPM7.CASA)))))
    WHEN 7
    THEN CONCAT (DOMPM7.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
    WHEN 7
    THEN CONCAT ( DOMPM7.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM7.LOCALIDAD, CONCAT (' - ', DOMPM7.CALLE_ALTURA))))
  END AS "DOMICILIO MADRE_PADRE2_CONT2",
  
  CASE WHEN CONV.CONVENCION  = 0 
    THEN 'NO'
    ELSE 'SI'
  END TIENE_CONVENCION,
  
  CONV.FECHA_CONVENCION,
  CONV.ESCRITURA,
  CONV.REGISTRO_NOTARIAL

---------------------------------------------------------------------------------------------------  

FROM RCE_GED.RCE_REGISTRO RR
LEFT JOIN RCE_GED.RCE_VINCULACION RV ON RR.ID_REGISTRO = RV.ID_REGISTRO_SUCESOR
LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SSR ON (RR.FK_SUBTIPO_REGISTRO = SSR.ID_SUBTIPO_REGISTRO)
LEFT JOIN RCE_GED.RCE_MATRIMONIO MAT ON MAT.ID_REGISTRO = RR.ID_REGISTRO
LEFT JOIN RCE_GED.RCE_CONVENCION_MATRIMONIAL CONV ON CONV.ID_CONVENCION_MATRIMONIAL =  MAT.FK_CONVENCION_MATRIMONIAL
LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO RAR ON (RR.ID_REGISTRO = RAR.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_DIGITAL D ON (RR.ID_REGISTRO = D.ID_REGISTRO)
LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT ON (D.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO)
LEFT JOIN RCE_GED.JBPM4_TASK F ON RR.ID_FLUJO_JBPM = F.EXECUTION_ID_

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM1 ON RPM1.FK_REGISTRO = RR.ID_REGISTRO AND RPM1.EVENTO     = 'onContrayente1'
LEFT JOIN RCE_GED.RCE_PERSONA RP1 ON (RPM1.FK_PERSONA = RP1.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD2 ON (RP1.FK_TIPO_DOCUMENTO = STD2.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM1 ON NACPM1.ID_NACIONALIDAD = RP1.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM1 ON SEXPM1.ID_SEXO = RP1.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM1 ON DOMPM1.ID_DOMICILIO = RP1.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM1 ON ASEPM1.ID_ASENTAMIENTO = DOMPM1.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM2 ON RPM2.FK_REGISTRO = RR.ID_REGISTRO AND RPM2.EVENTO     = 'onContrayente2'
LEFT JOIN RCE_GED.RCE_PERSONA RP2 ON (RPM2.FK_PERSONA = RP2.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD3 ON (RP2.FK_TIPO_DOCUMENTO = STD3.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM2 ON NACPM2.ID_NACIONALIDAD = RP2.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM2 ON SEXPM2.ID_SEXO = RP2.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM2 ON DOMPM2.ID_DOMICILIO = RP2.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP2 ON ASEP2.ID_ASENTAMIENTO = DOMPM2.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM4 ON RPM4.FK_REGISTRO = RR.ID_REGISTRO AND RPM4.EVENTO     = 'onPadre1'
LEFT JOIN RCE_GED.RCE_PERSONA RP4 ON (RPM4.FK_PERSONA = RP4.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD4 ON (RP4.FK_TIPO_DOCUMENTO = STD4.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM6 ON NACPM6.ID_NACIONALIDAD = RP4.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM4 ON SEXPM4.ID_SEXO = RP4.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM4 ON DOMPM4.ID_DOMICILIO = RP4.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM4 ON ASEPM4.ID_ASENTAMIENTO = DOMPM4.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM5 ON RPM5.FK_REGISTRO = RR.ID_REGISTRO AND RPM5.EVENTO     = 'onPadre2'
LEFT JOIN RCE_GED.RCE_PERSONA RP5 ON (RPM5.FK_PERSONA = RP5.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD5 ON (RP5.FK_TIPO_DOCUMENTO = STD5.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM5 ON NACPM5.ID_NACIONALIDAD = RP5.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM5 ON SEXPM5.ID_SEXO = RP5.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM5 ON DOMPM5.ID_DOMICILIO = RP5.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP5 ON ASEP5.ID_ASENTAMIENTO = DOMPM5.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM6 ON RPM6.FK_REGISTRO = RR.ID_REGISTRO AND RPM6.EVENTO     = 'onPadre3'
LEFT JOIN RCE_GED.RCE_PERSONA RP6 ON (RPM6.FK_PERSONA = RP6.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD6 ON (RP6.FK_TIPO_DOCUMENTO = STD6.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM4 ON NACPM4.ID_NACIONALIDAD = RP6.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM6 ON SEXPM6.ID_SEXO = RP6.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM6 ON DOMPM6.ID_DOMICILIO = RP6.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM6 ON ASEPM6.ID_ASENTAMIENTO = DOMPM6.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM7 ON RPM7.FK_REGISTRO = RR.ID_REGISTRO AND RPM7.EVENTO     = 'onPadre4' 
LEFT JOIN RCE_GED.RCE_PERSONA RP7 ON (RPM7.FK_PERSONA = RP7.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD7 ON (RP7.FK_TIPO_DOCUMENTO = STD7.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM7 ON NACPM7.ID_NACIONALIDAD = RP7.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM7 ON SEXPM7.ID_SEXO = RP7.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM7 ON DOMPM7.ID_DOMICILIO = RP7.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP7 ON ASEP7.ID_ASENTAMIENTO = DOMPM5.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON RR.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.EU_LOCALIDAD L ON C.FK_LOCALIDAD = L.ID
LEFT JOIN RCE_GED.EU_DEPARTAMENTO DL ON L.ID_DEPARTAMENTO = DL.ID

LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION DTC ON DT.FK_CIRCUNSCRIPCION = DTC.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.EU_LOCALIDAD DTL ON DTC.FK_LOCALIDAD = DTL.ID
LEFT JOIN RCE_GED.EU_DEPARTAMENTO DTDL ON DTL.ID_DEPARTAMENTO = DTDL.ID

---------------------------------------------------------------------------------------------------

WHERE
  REPARTICION_USUARIO  != 'TESTGDEBA'
  AND SSR.FK_TIPO_REGISTRO IN (4,5)
  AND RR.FK_SUBTIPO_REGISTRO NOT IN (83,86,102)
  ;