SELECT
	RR.ID_REGISTRO,
    TO_CHAR (RR.FECHA_INUTILIZACION, 'YYYY-MM-DD') AS FECHA_INUTILIZACION,
    RR.USUARIO_INMOVILIZACION,
    TO_CHAR(RR.FECHA_INMOVILIZACION,'YYYY-MM-DD') AS FECHA_INMOVILIZACION,
    SC.ID_CIRCUNSCRIPCION AS ID_DELEGACION,
    SC.NOMBRE AS DELEGACION_INSCRIPCION,
    EL.ID AS ID_LOCALIDAD_INSCRIPCION,
    EL.NOMBRE AS LOCALIDAD_INSCRIPCION,
    ED.ID AS ID_PARTIDO_INSCRIPCION,
    ED.NOMBRE AS PARTIDO_INSCRIPCION,
    COALESCE(RAR.ANIO,DT.ANIO) AS ANIO,
    COALESCE(RAR.TOMO||RAR.LETRA_TOMO, DT.TOMO) AS TOMO,
    COALESCE(RAR.NUMERO_ACTA,DT.ACTA) AS NUMERO_ACTA,
    RR.REPARTICION_USUARIO,
    TO_CHAR(COALESCE(RAR.FECHA_CREACION,RRP.FECHA_CREACION), 'YYYY-MM-DD') AS FECHA_CREACION,
	SSR.ID_SUBTIPO_REGISTRO AS ID_SUBTIPO,
    SSR.DESCRIPCION AS SUBTIPO,
    NVL(F.ACTIVITY_NAME_, 'Cerrado') ESTADO,
    TO_CHAR(RR.FECHA_ULTIMA_MODIFICACION,'YYYY-MM-DD') AS ESTADO_ULTIMA_MODIF,
	RRP.ID_REGISTRO_PERSONA AS ID_PERSONA_DIFUNTO,
    DECODE(RV.ID_REGISTRO_ANTECESOR, NULL, 'NO TIENE', 'SI') AS "CON VINC. REGISTRO ANTECESOR",
    RV.ID_REGISTRO_ANTECESOR,
    DECODE(CR1.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "TOMA IMPRES DACTILOSCOPICAS",
    DECODE(CR2.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "0-48 HS",
    DECODE(CR3.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "3-60 DIAS",
    DECODE(CR4.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "EXENTO",
    DECODE(CR5.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "TRAUMATICA",
    DECODE(CR6.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "PRESENTA DOCUMENTO",
    DECODE(CR7.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE') AS "TOMA DE HUELLAS",
    RP.PRIMER_NOMBRE AS NOMBRE_DIFUNTO,
    RP.PRIMER_APELLIDO AS APELLIDO_DIFUNTO,
    TO_CHAR (RP.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS FECHA_NAC_DIFUNTO,
    TO_CHAR (RD.FECHA_DEFUNCION, 'YYYY-MM-DD') AS FECHA_DEFUNCION,
    RP.SEGUNDO_NOMBRE AS SEGUNDO_NOMBRE_DIFUNTO,
    RP.TERCER_NOMBRE AS TERCER_NOMBRE_DIFUNTO,
    RP.SEGUNDO_APELLIDO AS SEG_APELLIDO_DIFUNTO,
    RP.TERCER_APELLIDO AS TERCER_APELLIDO_DIFUNTO,
    RP.ESTADO_CIVIL AS ESTADO_CIVIL_DIFUNTO,
    RP.TELEFONO AS TEL_DIFUNTO,
    RP.EMAIL AS MAIL_DIFUNTO,
    RP.PROFESION AS PROFESION_DIFUNTO,
    STD.DESCRIPCION  AS TIPO_DOC_DIFUNTO,
    RP.NUMERO_DOCUMENTO AS NRO_DOC_DIFUNTO ,
    SEXPM.DESCRIPCION AS SEXO_DIFUNTO,
    NACPM.DESCRIPCION_NACIONALIDAD AS NACIONALIDAD_DIFUNTO,
    
    'Argentina' AS DOM_DIFUNTO_PAIS, 
    'Buenos Aires' AS DOM_DIFUNTO_PROVINCIA, 
    DOMPM.MUNICIPIO AS DOM_DIFUNTO_MUNICIPIO, 
    DOMPM.LOCALIDAD AS DOM_DIFUNTO_LOCALIDAD, 
    DOMPM.CALLE_ALTURA AS DOM_DIFUNTO_CALLE_ALTURA, 
    ASEPM.NOMBRE AS DOM_DIFUNTO_VILLA_ASENTAMIENTO, 
    DOMPM.MANZANA AS DOM_DIFUNTO_MANZANA, 
    DOMPM.CASA AS DOM_DIFUNTO_CASA, 
    DOMPM.OBSERVACIONES AS DOM_DIFUNTO_OBSERVACIONES,

    ENF1.CODIGO AS COD_CAUSA_ORIGINARIA_DEF,
    ENF1.DESCRIPCION AS DESC_CAUSA_ORIGINARIA_DEF,
    ENF3.CODIGO AS COD_CAUSA_MEDIATA_DEF,
    ENF3.DESCRIPCION AS DESC_CAUSA_MEDIATA_DEF,
    ENF2.CODIGO AS COD_CAUSA_INMEDIATA_DEF,
    ENF2.DESCRIPCION AS DESC_CAUSA_INMEDIATA_DEF,
    OBS.DESCRIPCION AS OBSERVACIONES,
    
    STD1.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1",
    RP1.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1",
    CONCAT ( RP1.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP1.SEGUNDO_NOMBRE), CONCAT (' ', RP1.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1",
    CONCAT ( RP1.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP1.SEGUNDO_APELLIDO), CONCAT (' ', RP1.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1",
    NACPM1.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_MADRE_PADRE1",
    SEXPM1.DESCRIPCION AS "SEXO_MADRE_PADRE1",
    RP1.EMAIL AS "MAIL_MADRE_PADRE1",
    RP1.TELEFONO AS "TELEFONO_MADRE_PADRE1",
    TO_CHAR (RP1.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_MADRE_PADRE1",
    RP1.CUIL AS "CUIL_MADRE_PADRE1",
    RP1.ESTADO_CIVIL AS "ESTADO_CIVIL_MADRE_PADRE1",
    RP1.PROFESION AS "PROFESION_MADRE_PADRE1",
    
    CASE DOMPM1.FK_TIPO_DOMICILIO
        WHEN 1 THEN 
            CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (', ', DOMPM1.CALLE_ALTURA)))))
        WHEN 2 THEN 
            TO_CHAR (DOMPM1.OBSERVACIONES)
        WHEN 3 THEN 
            CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 4 THEN 
            CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM1.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM1.MANZANA, CONCAT (', Casa: ', DOMPM1.CASA)))))
        WHEN 5 THEN 
            CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 7 THEN 
            CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (' - ', DOMPM1.CALLE_ALTURA))))
    END AS "DOMICILIO_MADRE_PADRE1",  

    STD2.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2",
    RP2.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2",
    CONCAT ( RP2.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP2.SEGUNDO_NOMBRE), CONCAT (' ', RP2.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2",
    CONCAT ( RP2.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP2.SEGUNDO_APELLIDO), CONCAT (' ', RP2.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE2",
    NACPM2.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_MADRE_PADRE2",
    SEXPM2.DESCRIPCION AS "SEXO_MADRE_PARE2",
    RP2.EMAIL AS "MAIL_MADRE_PADRE2",
    RP2.TELEFONO AS "TELEFONO_MADRE_PADRE2",
    TO_CHAR (RP2.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_MADRE_PADRE2",
    RP2.CUIL AS "CUIL_MADRE_PADRE2",
    RP2.ESTADO_CIVIL AS "ESTADO_CIVIL_MADRE_PADRE2",
    RP2.PROFESION AS "PROFESION_MADRE_PADRE2",

    CASE DOMPM2.FK_TIPO_DOMICILIO
        WHEN 1 THEN 
            CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (', ', DOMPM2.CALLE_ALTURA)))))
        WHEN 2 THEN 
            TO_CHAR (DOMPM2.OBSERVACIONES)
        WHEN 3 THEN 
            CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 4 THEN 
            CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP2.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM2.MANZANA, CONCAT (', Casa: ', DOMPM2.CASA)))))
        WHEN 5 THEN 
            CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 7 THEN 
            CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (' - ', DOMPM2.CALLE_ALTURA))))
    END AS "DOMICILIO MADRE_PADRE2",
  
    STD3.DESCRIPCION AS "TIPO_DOC_DECLARANTE",
    RP3.NUMERO_DOCUMENTO AS "NRO_DOC_DECLARANTE",
    CONCAT ( RP3.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP3.SEGUNDO_NOMBRE), CONCAT (' ', RP3.TERCER_NOMBRE))) AS "NOMBRES_DECLARANTE",
    CONCAT ( RP3.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP3.SEGUNDO_APELLIDO), CONCAT (' ', RP3.TERCER_APELLIDO))) AS "APELLIDOS_DECLARANTE",
    NACPM3.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_DECLARANTE",
    SEXPM3.DESCRIPCION AS "SEXO_DECLARANTE",
    RP3.EMAIL AS "MAIL_DECLARANTE",
    RP3.TELEFONO AS "TELEFONO_DECLARANTE",
    TO_CHAR (RP3.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_DECLARANTE",
    RP3.CUIL AS "CUIL_DECLARANTE",
    RP3.ESTADO_CIVIL AS "ESTADO_CIVIL_DECLARANTE",
    RP3.PROFESION AS "PROFESION_DECLARANTE",

    CASE DOMPM3.FK_TIPO_DOMICILIO
        WHEN 1 THEN 
            CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM3.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM3.LOCALIDAD, CONCAT (', ', DOMPM3.CALLE_ALTURA)))))
        WHEN 2 THEN 
            TO_CHAR (DOMPM3.OBSERVACIONES)
        WHEN 3 THEN 
            CONCAT (DOMPM3.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 4 THEN 
            CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP3.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM3.MANZANA, CONCAT (', Casa: ', DOMPM3.CASA)))))
        WHEN 5 THEN 
            CONCAT (DOMPM3.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
        WHEN 7 THEN 
            CONCAT ( DOMPM3.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM3.LOCALIDAD, CONCAT (' - ', DOMPM3.CALLE_ALTURA))))
    END AS "DOMICILIO_DECLARANTE",

    OBS3.DESCRIPCION AS ACLARACIONES_DECLARANTE,
    SAL.ID_ESTABLECIMIENTO_SALUD,
    SAL.DESCRIPCION AS ESTABLECIMIENTO_LUGAR,
	DOMICILIO_EST.CALLE_ALTURA AS ESTABLECIMIENTO_CALLE,
	DOMICILIO_EST.LOCALIDAD AS ESTABLECIMIENTO_LOCALIDAD,
	DOMICILIO_EST.MUNICIPIO AS ESTABLECIMIENTO_MUNICIPIO,
	PROV_ESTABLECIMIENTO.NOMBRE AS ESTABLECIMIENTO_PROVINCIA,
    EST_PAIS.DESCRIPCION AS ESTABLECIMIENTO_PAIS,
    DOMICILIO_DEFUNCION.CALLE_ALTURA AS DEFUNCION_CALLE,
	DOMICILIO_DEFUNCION.LOCALIDAD AS DEFUNCION_LOCALIDAD,
	DOMICILIO_DEFUNCION.MUNICIPIO AS DEFUNCION_MUNICIPIO,
	PROV_DOM_DEFU.NOMBRE AS DEFUNCION_PROVINCIA,
    PAIS_DOM_DEFU.DESCRIPCION AS DEFUNCION_PAIS,
    DOMICILIO_DEFUNCION.OBSERVACIONES AS OBS_DOMICILIO_DEFUNCION,
    OBS1.DESCRIPCION AS OBS_LUGAR_DEFUNCION,
    PROF.PROFESION AS PROFESION_MEDICO,
    MED.TIPO_MATRICULA AS TIPO_MAT_MED,
    MED.MATRICULA AS MAT_MEDICO,
    MED.NOMBRE AS NOMBRE_MEDICO,
    MED.APELLIDO AS APELLIDO_MEDICO,
    RD.NUMERO_CERT_MEDICO

----------------------------------------------------------------------------------------------------------------

--INFORMACION REFERIDA AL REGISTRO Y ACTA DE REGISTRO--
FROM RCE_GED.RCE_REGISTRO RR
LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO RAR ON (RR.ID_REGISTRO = RAR.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_DIGITAL D ON (RR.ID_REGISTRO = D.ID_REGISTRO)
LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DT ON (D.FK_DATO_TOPOGRAFICO = DT.ID_DATO_TOPOGRAFICO)
LEFT JOIN RCE_GED.RCE_VINCULACION RV ON RR.ID_REGISTRO = RV.ID_REGISTRO_SUCESOR

--INFORMACION REFERIDA AL SUBTIPO DE REGISTRO Y CONDICION--
LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SSR ON (RR.FK_SUBTIPO_REGISTRO = SSR.ID_SUBTIPO_REGISTRO)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR1 ON CR1.FK_REGISTRO = RR.ID_REGISTRO AND CR1.FK_TIPO_CONDICION = 420
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR2 ON CR2.FK_REGISTRO = RR.ID_REGISTRO AND CR2.FK_TIPO_CONDICION IN (428,430,432)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR3 ON CR3.FK_REGISTRO = RR.ID_REGISTRO AND CR3.FK_TIPO_CONDICION IN (429 , 431, 433)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR4 ON CR4.FK_REGISTRO = RR.ID_REGISTRO AND CR4.FK_TIPO_CONDICION IN (434, 435)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR5 ON CR5.FK_REGISTRO = RR.ID_REGISTRO AND CR5.FK_TIPO_CONDICION IN (436, 437, 440)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR6 ON CR6.FK_REGISTRO = RR.ID_REGISTRO AND CR6.FK_TIPO_CONDICION = 438
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR7 ON CR7.FK_REGISTRO = RR.ID_REGISTRO AND CR7.FK_TIPO_CONDICION = 439
LEFT JOIN RCE_GED.JBPM4_TASK F ON RR.ID_FLUJO_JBPM = F.EXECUTION_ID_

--INFORMACION REFERIDA A LA CIRCUNSCRIPCION--
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SC ON RR.FK_ID_CIRCUNSCRIPCION = SC.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION SC ON DT.FK_CIRCUNSCRIPCION = SC.ID_CIRCUNSCRIPCION
LEFT JOIN EU_GED.EU_LOCALIDAD EL ON SC.FK_LOCALIDAD = EL.ID
LEFT JOIN EU_GED.EU_DEPARTAMENTO ED ON EL.ID_DEPARTAMENTO = ED.ID

--INFORMACION REFERIDA AL DIFUNTO--
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RRP ON (RR.ID_REGISTRO = RRP.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_PERSONA RP ON (RRP.FK_PERSONA = RP.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD ON (RP.FK_TIPO_DOCUMENTO = STD.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM ON NACPM.ID_NACIONALIDAD = RP.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM ON SEXPM.ID_SEXO = RP.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM ON DOMPM.ID_DOMICILIO = RP.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM ON ASEPM.ID_ASENTAMIENTO = DOMPM.FK_ASENTAMIENTO

--INFORMACION REFERIDA A CAUSA DE DEFUNCION--
LEFT JOIN RCE_GED.RCE_DEFUNCION RD ON (RR.ID_REGISTRO = RD.ID_REGISTRO)
LEFT JOIN RCE_GED.SYS_CLASIFICACION_ENFERMEDADES ENF1 ON (ENF1.ID_CLASIFICACION_ENFERMEDADES = RD.FK_CAUSA_ORIGINARIA)
LEFT JOIN RCE_GED.SYS_CLASIFICACION_ENFERMEDADES ENF2 ON (ENF2.ID_CLASIFICACION_ENFERMEDADES = RD.FK_CAUSA_INMEDIATA)
LEFT JOIN RCE_GED.SYS_CLASIFICACION_ENFERMEDADES ENF3 ON (ENF3.ID_CLASIFICACION_ENFERMEDADES = RD.FK_CAUSA_MEDIATA)
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS ON RD.FK_OTRA_CAUSA_INMEDIATA = OBS.ID_OBSERVACIONES
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS1 ON OBS1.ID_OBSERVACIONES = RD.FK_OBSERVACION_LUGAR_DEFUNCION

--INFORMACION REFERIDA AL LUGAR DE DEFUNCION--

LEFT JOIN RCE_GED.RCE_DOMICILIO DOMICILIO_DEFUNCION ON RD.FK_DOMICILIO = DOMICILIO_DEFUNCION.ID_DOMICILIO
LEFT JOIN EU_GED.EU_PROVINCIA PROV_DOM_DEFU ON PROV_DOM_DEFU.ID = DOMICILIO_DEFUNCION.FK_PROVINCIA
LEFT JOIN RCE_GED.SYS_NACIONALIDAD PAIS_DOM_DEFU ON PAIS_DOM_DEFU.ID_NACIONALIDAD = DOMICILIO_DEFUNCION.FK_PAIS

--INFORMACION REFERIDA A MADRE/PADRE 1--
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM1 ON RPM1.FK_REGISTRO = RR.ID_REGISTRO AND RPM1.EVENTO = 'onPadre1'
LEFT JOIN RCE_GED.RCE_PERSONA RP1 ON (RPM1.FK_PERSONA = RP1.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD1 ON (RP1.FK_TIPO_DOCUMENTO = STD1.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM1 ON NACPM1.ID_NACIONALIDAD = RP1.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM1 ON SEXPM1.ID_SEXO = RP1.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM1 ON DOMPM1.ID_DOMICILIO = RP1.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM1 ON ASEPM1.ID_ASENTAMIENTO = DOMPM1.FK_ASENTAMIENTO

--INFORMACION REFERIDA A MADRE/PADRE 2--
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM2 ON RPM2.FK_REGISTRO = RR.ID_REGISTRO AND RPM2.EVENTO = 'onPadre2'
LEFT JOIN RCE_GED.RCE_PERSONA RP2 ON (RPM2.FK_PERSONA = RP2.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD2 ON (RP2.FK_TIPO_DOCUMENTO = STD2.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM2 ON NACPM2.ID_NACIONALIDAD = RP2.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM2 ON SEXPM2.ID_SEXO = RP2.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM2 ON DOMPM2.ID_DOMICILIO = RP2.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP2 ON ASEP2.ID_ASENTAMIENTO = DOMPM2.FK_ASENTAMIENTO

--INFORMACION REFERIDA AL INTERVINIENTE--
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM3 ON RPM3.FK_REGISTRO = RR.ID_REGISTRO AND RPM3.EVENTO = 'onIntervinienteDefuncion'
LEFT JOIN RCE_GED.RCE_PERSONA RP3 ON (RPM3.FK_PERSONA = RP3.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD3 ON (RP3.FK_TIPO_DOCUMENTO = STD3.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM3 ON NACPM3.ID_NACIONALIDAD = RP3.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM3 ON SEXPM3.ID_SEXO = RP3.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM3 ON DOMPM3.ID_DOMICILIO = RP3.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP3 ON ASEP3.ID_ASENTAMIENTO = DOMPM3.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS3 ON RPM3.FK_OBSERVACIONES = OBS3.ID_OBSERVACIONES

--INFORMACION REFERIDA AL ESTABLECIMIENTO DE SALUD--
LEFT JOIN RCE_GED.SYS_ESTABLECIMIENTO_SALUD SAL ON RD.FK_ESTABLECIMIENTO_SALUD = SAL.ID_ESTABLECIMIENTO_SALUD
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMICILIO_EST ON SAL.FK_DOMICILIO = DOMICILIO_EST.ID_DOMICILIO
LEFT JOIN EU_GED.EU_PROVINCIA PROV_ESTABLECIMIENTO ON PROV_ESTABLECIMIENTO.ID = DOMICILIO_EST.FK_PROVINCIA
LEFT JOIN RCE_GED.SYS_NACIONALIDAD EST_PAIS ON EST_PAIS.ID_NACIONALIDAD = DOMICILIO_EST.FK_PAIS

--INFORMACION REFERIDA AL PERSONAL DE SALUD--
LEFT JOIN RCE_GED.RCE_MEDICO MED ON MED.ID_MEDICO = RD.FK_MEDICO
LEFT JOIN RCE_GED.SYS_PROFESIONAL_MEDICINA PROF ON PROF.ID_PROFESION = MED.FK_PROFESIONAL_MEDICINA


----------------------------------------------------------------------------------------------------------------

WHERE REPARTICION_USUARIO != 'TESTGDEBA' AND RRP.ROL = 'Difunto';