SELECT
RR.ID_REGISTRO,
TO_CHAR (RR.FECHA_INUTILIZACION, 'YYYY-MM-DD') AS FECHA_INUTILIZACION,
RR.USUARIO_INMOVILIZACION,
TO_CHAR(RR.FECHA_INMOVILIZACION,'YYYY-MM-DD') AS FECHA_INMOVILIZACION,
C.NOMBRE AS DELEGACION_INSCRIPCION,
L.ID AS ID_LOCALIDAD_INSCRIPCION,
L.NOMBRE AS LOCALIDAD_INSCRIPCION,
DL.ID AS ID_PARTIDO_INSCRIPCION,
DL.NOMBRE AS PARTIDO_INSCRIPCION,
COALESCE(RAR.ANIO,DATOP.ANIO) AS ANIO,
COALESCE(RAR.TOMO||RAR.LETRA_TOMO, DATOP.TOMO) AS TOMO,
NVL(RAR.FOLIO,0) AS FOLIO,
COALESCE(RAR.NUMERO_ACTA,DATOP.ACTA) AS NUMERO_ACTA,
NVL(RAR.ID_ACTA_REGISTRO,0) AS ID_ACTA_NACIDO,
TO_CHAR(RP.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS FECHA_NACIMIENTO,
NAC.PESO_NACIMIENTO AS PESO_NACIMIENTO,
NAC.EDAD_GESTACIONAL AS EDAD_GESTACIONAL,
NAC.VACUNADO AS VACUNADO,
TO_CHAR(COALESCE(RAR.FECHA_CREACION,RRP.FECHA_CREACION), 'YYYY-MM-DD') AS FECHA_REGISTRO,
SSR.ID_SUBTIPO_REGISTRO AS ID_SUBTIPO,
SSR.DESCRIPCION AS SUBTIPO,
NVL(F.ACTIVITY_NAME_, 'Cerrado') AS ESTADO,
TO_CHAR(RR.FECHA_ULTIMA_MODIFICACION,'YYYY-MM-DD') AS ESTADO_ULTIMA_MODIF,
RRP.ID_REGISTRO_PERSONA AS ID_PERSONA_NACIDO,
RP.PRIMER_NOMBRE AS NOMBRE_NACIDO,
RP.SEGUNDO_NOMBRE AS SEGUNDO_NOMBRE_NACIDO,
RP.TERCER_NOMBRE AS TERCER_NOMBRE_NACIDO,
RP.PRIMER_APELLIDO AS APELLIDO_NACIDO,
RP.SEGUNDO_APELLIDO AS SEG_APELLIDO_NACIDO,
RP.TERCER_APELLIDO AS TERCER_APELLIDO_NACIDO,
STD.DESCRIPCION AS TIPO_DOC_NACIDO,
RP.NUMERO_DOCUMENTO AS NRO_DOC_NACIDO,
RP.NUMERO_DOCUMENTO AS DOCUMENTO_OTORGADO,
SS.DESCRIPCION AS SEXO_NACIDO,

'Argentina' AS DOM_NACIDO_PAIS, 
'Buenos Aires' AS DOM_NACIDO_PROVINCIA, 
DOMPM.MUNICIPIO AS DOM_NACIDO_MUNICIPIO, 
DOMPM.LOCALIDAD AS DOM_NACIDO_LOCALIDAD, 
DOMPM.CALLE_ALTURA AS DOM_NACIDO_CALLE_ALTURA, 
ASEPM.NOMBRE AS DOM_NACIDO_VILLA_ASENTAMIENTO, 
DOMPM.MANZANA AS DOM_NACIDO_MANZANA, 
DOMPM.CASA AS DOM_NACIDO_CASA, 
DOMPM.OBSERVACIONES AS DOM_NACIDO_OBSERVACIONES,
    
CERT.NUMERO_CERTIFICADO AS NRO_CONSTRACCION_PARTO,
CERT.NUMERO_OBLEA AS NRO_OBLEA,
TO_CHAR(CERT.FECHA_EMISION, 'YYYY-MM-DD') AS FECHA_EMI_CONSTRACCION_PARTO,
PROV6.NOMBRE AS PROVINCIA_EXPEDICION,
CERT.CIUDAD_EXPEDICION AS CIUDAD_EXPEDICION,
RD.INTERVINIENTE AS INTERVINIENTE,
RP1.ID_PERSONA AS "ID_MADRE_PADRE1",
STD2.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE1",
RP1.NUMERO_DOCUMENTO AS "NRO_DOC_MADRE_PADRE1",
CONCAT(RP1.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP1.SEGUNDO_NOMBRE), CONCAT (' ', RP1.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE1",
CONCAT(RP1.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP1.SEGUNDO_APELLIDO), CONCAT (' ', RP1.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE1",
NACPM1.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_MADRE_PADRE1",
SEXPM1.DESCRIPCION AS "SEXO_MADRE_PADRE1",
RP1.EMAIL AS "MAIL_MADRE_PADRE1",
RP1.TELEFONO AS "TELEFONO_MADRE_PADRE1",
TO_CHAR (RP1.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_MADRE_PADRE1",
RP1.CUIL AS "CUIL_MADRE_PADRE1",
RP1.ESTADO_CIVIL AS "ESTADO_CIVIL_MADRE_PADRE1",
RP1.PROFESION AS "PROFESION_MADRE_PADRE1",
  
CASE DOMPM1.FK_TIPO_DOMICILIO
  WHEN 1
  THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM1.LOCALIDAD, CONCAT (', ', DOMPM1.CALLE_ALTURA)))))
  WHEN 2
  THEN TO_CHAR (DOMPM1.OBSERVACIONES)
  WHEN 3
  THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 4
  THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEPM1.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM1.MANZANA, CONCAT (', Casa: ', DOMPM1.CASA)))))
  WHEN 5
  THEN CONCAT (DOMPM1.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 7
  THEN CONCAT ( DOMPM1.MUNICIPIO, CONCAT ( ' - ', CONCAT (dompm1.LOCALIDAD, CONCAT (' - ', dompm1.CALLE_ALTURA))))
END AS "DOMICILIO_MADRE_PADRE1",
  
RP2.ID_PERSONA AS "ID_MADRE_PADRE2",
STD3.DESCRIPCION AS "TIPO_DOC_MADRE_PADRE2",
RP2.NUMERO_DOCUMENTO AS "NRO_MADRE_PADRE2",
CONCAT(RP2.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP2.SEGUNDO_NOMBRE), CONCAT (' ', RP2.TERCER_NOMBRE))) AS "NOMBRES_MADRE_PADRE2",
CONCAT(RP2.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP2.SEGUNDO_APELLIDO), CONCAT (' ', RP2.TERCER_APELLIDO))) AS "APELLIDOS_MADRE_PADRE2",
NACPM2.DESCRIPCION_NACIONALIDAD AS "NACIONALIDAD_MADRE_PADRE2",
SEXPM2.DESCRIPCION AS "SEXO_MADRE_PADRE2",
RP2.EMAIL AS "MAIL_MADRE_PADRE2",
RP2.TELEFONO AS "TELEFONO_MADRE_PADRE2",
TO_CHAR(RP2.FECHA_NACIMIENTO, 'YYYY-MM-DD') AS "FECHA_NACIMIENTO_MADRE_PADRE2",
RP2.CUIL AS "CUIL_MADRE_PADRE2",
RP2.ESTADO_CIVIL AS "ESTADO_CIVIL_MADRE_PADRE2",
RP2.PROFESION AS "PROFESION_MADRE_PADRE2",
  
CASE DOMPM2.FK_TIPO_DOMICILIO
  WHEN 1
  THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ', ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (', ', DOMPM2.CALLE_ALTURA)))))
  WHEN 2
  THEN TO_CHAR (DOMPM2.OBSERVACIONES)
  WHEN 3
  THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 4
  THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP2.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOMPM2.MANZANA, CONCAT (', Casa: ', DOMPM2.CASA)))))
  WHEN 5
  THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 7
  THEN CONCAT ( DOMPM2.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOMPM2.LOCALIDAD, CONCAT (' - ', DOMPM2.CALLE_ALTURA))))
END AS "DOMICILIO_MADRE_PADRE2",

SAL.DESCRIPCION AS ESTABLECIMIENTO_LUGAR,
  
CASE DOM3.FK_TIPO_DOMICILIO
  WHEN 1
  THEN CONCAT ( 'Argentina, Buenos Aires, ', CONCAT ( DOM3.MUNICIPIO, CONCAT ( ', ', CONCAT (DOM3.LOCALIDAD, CONCAT (', ', DOM3.CALLE_ALTURA)))))
  WHEN 2
  THEN TO_CHAR (DOM3.OBSERVACIONES)
  WHEN 3
  THEN CONCAT (DOMPM2.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 4
  THEN CONCAT ( 'Nombre de la Villa_Asentamiento: ', CONCAT ( ASEP3.NOMBRE, CONCAT ( ', Manzana: ', CONCAT (DOM3.MANZANA, CONCAT (', Casa: ', DOM3.CASA)))))
  WHEN 5
  THEN CONCAT (DOM3.CALLE_ALTURA, ' - Ciudad de Buenos Aires')
  WHEN 7
  THEN CONCAT ( DOM3.MUNICIPIO, CONCAT ( ' - ', CONCAT (DOM3.LOCALIDAD, CONCAT (' - ', DOM3.CALLE_ALTURA))))
END AS DOMICILIO_ESTABLECIMIENTO,
  
CIR.NOMBRE AS DELEGACION,
CERT.CIUDAD_EXPEDICION AS LUGAR_NACIMIENTO,

RP3.ID_PERSONA AS "ID_DECLARANTE",
STD4.DESCRIPCION AS "TIPO_DOC_DECLARANTE",
RP3.NUMERO_DOCUMENTO AS "NRO_DOC_DECLARANTE",
CONCAT ( RP3.PRIMER_NOMBRE, CONCAT (CONCAT (' ', RP3.SEGUNDO_NOMBRE), CONCAT (' ', RP3.TERCER_NOMBRE))) AS "NOMBRES_DECLARANTE",
CONCAT ( RP3.PRIMER_APELLIDO, CONCAT (CONCAT (' ', RP3.SEGUNDO_APELLIDO), CONCAT (' ', RP3.TERCER_APELLIDO))) AS "APELLIDOS_DECLARANTE",
PROF.PROFESION AS PROFESION_MEDICO,
MED.TIPO_MATRICULA AS TIPO_MAT_MED,
MED.MATRICULA AS MAT_MEDICO,
MED.NOMBRE AS NOMBRE_MEDICO,
MED.APELLIDO AS APELLIDO_MEDICO,
OBS.DESCRIPCION AS ACLARACIONES,
DECODE(CR.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS "AMBOS_PADRES_PRESENTES",
DECODE(CR1.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS "CON_CONSTATACION_DE_PARTO"	,
DECODE(RV.ID_REGISTRO_ANTECESOR, NULL, 'NO TIENE', 'SI') AS "CON VINC. REGISTRO ANTECESOR",
RV.ID_REGISTRO_ANTECESOR,
DECODE(CR3.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"DECLARANTE_PRESENTA_DOCUMENTO",
DECODE(CR4.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"ENTRE_0_40_DIAS",
DECODE(CR5.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"ENTRE_0_365_DIAS",
DECODE(CR6.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"ES_MENOR_DE_14_AÑOS",
DECODE(CR7.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"ES_PARTO_MULTIPLE",
DECODE(CR8.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"MADRE_PADRE_2_PRESENTA_DOC",
DECODE(CR9.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	 "POR_INSTRUMENTO",
DECODE(CR10.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"PRESENTA_DOCUMENTO",
DECODE(CR11.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"QUIEN_DIO_A_LUZ_PRESENTA_DOC",
DECODE(CR12.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"RECONOC_MAYOR_MADRE_PRESENTE",
DECODE(CR13.VALOR, 0 , 'NO',1, 'SI',NULL, 'NO TIENE')AS	"THRA"

---------------------------------------------------------------------------------------------------

FROM RCE_GED.RCE_REGISTRO RR
LEFT JOIN RCE_GED.RCE_DIGITAL DIG ON DIG.ID_REGISTRO = RR.ID_REGISTRO
LEFT JOIN RCE_GED.RCE_VINCULACION RV ON RR.ID_REGISTRO = RV.ID_REGISTRO_SUCESOR
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RRP ON (RR.ID_REGISTRO = RRP.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR ON CR.FK_REGISTRO = RR.ID_REGISTRO AND CR.FK_TIPO_CONDICION = 421
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR1 ON CR1.FK_REGISTRO = RR.ID_REGISTRO AND CR1.FK_TIPO_CONDICION IN (401,397)
LEFT JOIN  RCE_GED.RCE_CONDICION_REGISTRO CR3 ON CR3.FK_REGISTRO = RR.ID_REGISTRO AND CR3.FK_TIPO_CONDICION  = 422
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR4 ON CR4.FK_REGISTRO = RR.ID_REGISTRO AND CR4.FK_TIPO_CONDICION  IN (423,400,396)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR5 ON CR5.FK_REGISTRO = RR.ID_REGISTRO AND CR5.FK_TIPO_CONDICION  IN (441,442,443)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR6 ON CR6.FK_REGISTRO = RR.ID_REGISTRO AND CR6.FK_TIPO_CONDICION  IN (450,451)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR7 ON CR7.FK_REGISTRO = RR.ID_REGISTRO AND CR7.FK_TIPO_CONDICION  IN (448,449)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR8 ON CR8.FK_REGISTRO = RR.ID_REGISTRO AND CR8.FK_TIPO_CONDICION  IN (403,399)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR9 ON CR9.FK_REGISTRO = RR.ID_REGISTRO AND CR9.FK_TIPO_CONDICION  = 427
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR10 ON CR10.FK_REGISTRO = RR.ID_REGISTRO AND CR10.FK_TIPO_CONDICION  IN(453,452)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR11 ON CR11.FK_REGISTRO = RR.ID_REGISTRO AND CR11.FK_TIPO_CONDICION  IN(402,398)
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR12 ON CR12.FK_REGISTRO = RR.ID_REGISTRO AND CR12.FK_TIPO_CONDICION = 428
LEFT JOIN RCE_GED.RCE_CONDICION_REGISTRO CR13 ON CR13.FK_REGISTRO = RR.ID_REGISTRO AND CR13.FK_TIPO_CONDICION IN (445,444)
LEFT JOIN RCE_GED.JBPM4_TASK F ON RR.ID_FLUJO_JBPM = F.EXECUTION_ID_
LEFT JOIN RCE_GED.RCE_ACTA_REGISTRO RAR ON (RR.ID_REGISTRO = RAR.FK_REGISTRO)
LEFT JOIN RCE_GED.RCE_DATO_TOPOGRAFICO DATOP ON DATOP.ID_DATO_TOPOGRAFICO = DIG.FK_DATO_TOPOGRAFICO

LEFT JOIN RCE_GED.RCE_PERSONA RP ON (RRP.FK_PERSONA = RP.ID_PERSONA)
LEFT JOIN RCE_GED.RCE_NACIDO NAC ON NAC.ID_REGISTRO_PERSONA = RRP.ID_REGISTRO_PERSONA
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD ON (RP.FK_TIPO_DOCUMENTO = STD.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_SEXO SS ON (RP.FK_SEXO = SS.ID_SEXO)
LEFT JOIN RCE_GED.RCE_NACIMIENTO RD ON (RR.ID_REGISTRO = RD.ID_REGISTRO)
LEFT JOIN RCE_GED.RCE_OBSERVACIONES OBS ON OBS.ID_OBSERVACIONES = RD.FK_OBSERVACIONES
LEFT JOIN RCE_GED.RCE_CERTIFICADO_MEDICO CERT ON CERT.ID_CERTIFICADO = RD.FK_CERTIFICADO_MEDICO
LEFT JOIN EU_GED.EU_PROVINCIA PROV6 ON (PROV6.ID = CERT.FK_PROVINCIA_EXPEDICION)
LEFT JOIN RCE_GED.RCE_LUGAR_NACIMIENTO LUG ON RD.FK_LUGAR_NACIMIENTO = LUG.ID_LUGAR_NACIMIENTO
LEFT JOIN RCE_GED.SYS_ESTABLECIMIENTO_SALUD SAL ON LUG.FK_ESTABLECIMIENTO_SALUD = SAL.ID_ESTABLECIMIENTO_SALUD
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION CIR ON CIR.ID_CIRCUNSCRIPCION = SAL.FK_CIRCUNSCRIPCION
LEFT JOIN EU_GED.EU_LOCALIDAD LOL ON CIR.FK_LOCALIDAD = LOL.ID
LEFT JOIN EU_GED.EU_DEPARTAMENTO DEP ON DEP.ID = LOL.ID_DEPARTAMENTO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOM3 ON DOM3.ID_DOMICILIO = SAL.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP3 ON ASEP3.ID_ASENTAMIENTO = DOM3.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.RCE_MEDICO MED ON MED.ID_MEDICO = RD.FK_MEDICO
LEFT JOIN RCE_GED.SYS_PROFESIONAL_MEDICINA PROF ON PROF.ID_PROFESION = MED.FK_PROFESIONAL_MEDICINA

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM1 ON RPM1.FK_REGISTRO = RR.ID_REGISTRO AND RPM1.EVENTO     = 'onPadre1'
LEFT JOIN RCE_GED.RCE_PERSONA RP1 ON (RPM1.FK_PERSONA = RP1.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD2 ON (RP1.FK_TIPO_DOCUMENTO = STD2.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM1 ON NACPM1.ID_NACIONALIDAD = RP1.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM1 ON SEXPM1.ID_SEXO = RP1.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM1 ON DOMPM1.ID_DOMICILIO = RP1.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM1 ON ASEPM1.ID_ASENTAMIENTO = DOMPM1.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM2 ON RPM2.FK_REGISTRO = RR.ID_REGISTRO AND RPM2.EVENTO     = 'onPadre2' 
LEFT JOIN RCE_GED.RCE_PERSONA RP2 ON (RPM2.FK_PERSONA = RP2.ID_PERSONA) 
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD3 ON (RP2.FK_TIPO_DOCUMENTO = STD3.ID_TIPO_DOCUMENTO)
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM2 ON NACPM2.ID_NACIONALIDAD = RP2.FK_NACIONALIDAD
LEFT JOIN RCE_GED.SYS_SEXO SEXPM2 ON SEXPM2.ID_SEXO = RP2.FK_SEXO
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM2 ON DOMPM2.ID_DOMICILIO = RP2.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEP2 ON ASEP2.ID_ASENTAMIENTO = DOMPM2.FK_ASENTAMIENTO

LEFT JOIN RCE_GED.RCE_PERSONA PM ON PM.ID_PERSONA = RPM1.FK_PERSONA
LEFT JOIN RCE_GED.SYS_NACIONALIDAD NACPM ON NACPM.ID_NACIONALIDAD = PM.FK_NACIONALIDAD
LEFT JOIN RCE_GED.RCE_DOMICILIO DOMPM ON DOMPM.ID_DOMICILIO = PM.FK_DOMICILIO
LEFT JOIN RCE_GED.SYS_ASENTAMIENTO ASEPM ON ASEPM.ID_ASENTAMIENTO = DOMPM.FK_ASENTAMIENTO
LEFT JOIN RCE_GED.SYS_SUBTIPO_REGISTRO SSR ON (RR.FK_SUBTIPO_REGISTRO = SSR.ID_SUBTIPO_REGISTRO)
LEFT JOIN RCE_GED.RCE_REGISTRO_PERSONA RPM3 ON RPM3.FK_REGISTRO = RR.ID_REGISTRO AND RPM3.EVENTO     = 'onIntervinienteNacimiento'
LEFT JOIN RCE_GED.RCE_PERSONA RP3 ON (RPM3.FK_PERSONA = RP3.ID_PERSONA)
LEFT JOIN RCE_GED.SYS_TIPO_DOCUMENTO STD4 ON (RP3.FK_TIPO_DOCUMENTO = STD4.ID_TIPO_DOCUMENTO)

LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON RR.FK_ID_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.SYS_CIRCUNSCRIPCION C ON DATOP.FK_CIRCUNSCRIPCION = C.ID_CIRCUNSCRIPCION
LEFT JOIN RCE_GED.EU_LOCALIDAD L ON C.FK_LOCALIDAD = L.ID
LEFT JOIN RCE_GED.EU_DEPARTAMENTO DL ON L.ID_DEPARTAMENTO = DL.ID

WHERE     
    RRP.ROL = 'Hijo' AND REPARTICION_USUARIO != 'TESTGDEBA'
    AND TO_CHAR(COALESCE(RAR.FECHA_CREACION,RRP.FECHA_CREACION), 'YYYY-MM-DD') = TO_CHAR(SYSDATE,'YYYY-MM-DD');